### ISSUE TITLE
Password should be stored in the keychain

### ISSUE THREAD

**Issue by jonasreinsch** [deltachat/deltachat-ios#1]
Currently, the IMAP password is stored in SQLite. Store it in the keychain instead.

**Comment by r10s** [comment]
Would it be possible to access the password if the device is _locked?_
We would need this for getting notifications.

**Comment by jonasreinsch** [comment]
@r10s AFAIK it is possible, but I need to read a bit more to understand how to do this right. Perhaps better to postpone this a bit still:

> `kSecAttrAccessibleAfterFirstUnlock`
> The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
>
> After the first unlock, the data remains accessible until the next restart. This is recommended for items that need to be accessed by background applications. Items with this attribute migrate to a new device when using encrypted backups.

- https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlock
- http://asciiwwdc.com/2013/sessions/709

**Comment by tudormunteanu** [comment]
@r10s by "getting notifications" do you mean iOS push notifications? They shouldn't theoretically require the device to be unlocked, as the notification itself contains the required payload to be displayed.

**Comment by jonasreinsch** [comment]
@tudormunteanu you are right of course, but push notifications cannot be used in a straightforward way because Deltachat has no server that could contact APNS (Apple Push Notification Service). I.e. the current thinking is to use some kind of background mode (e.g. background fetch) and then let the app do a local notification (which looks similar to a push notification by APNS for the user). But the whole topic of notifications is a bit postponed atm until the rest of the app is up to par.

**Comment by jonasreinsch** [comment]
closing this for now, as I think it has rather low prio (perhaps will open it later)
