### ISSUE TITLE
content sometimes hidden behind input-bar

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1011]
in the chat-view, the chat-content is sometimes hidden behind input-bar.

to reproduce, do the "back" gesture, swipe from left to right and stop and cancel at 1/4th.

<img width=320 src=https://user-images.githubusercontent.com/9800740/100149472-85d56f80-2e9e-11eb-9723-13d532053380.png>

**Comment by dignifiedquire** [comment]
still happening on current testflight
