### ISSUE TITLE
sometimes messages are sent without text

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1013]
it happens to me two times that i typed in some text and the message was sent empty, without text.

the second time, i quoted another message - the quote was sent, but not the text. in both cases, the message was encrypted - but as the quote could be decrypted, this is probably not the issue.

the message is shown as empty also on the sending device, so it seems not be related to message/receiving, my current theory is that `dc_msg_set_text()` was given an empty string, for whatever reason.

i am currently failing to find a way how to reproduce that.

maybe the input-field goes away, before the text is grabbed? as the message is sent in a thread? sort of race condition?

i anyone has an idea, this is very welcome :)

**Comment by r10s** [comment]
the sending takes place in https://github.com/deltachat/deltachat-ios/blob/d1ded588948d0117e1e7dddd0e2754a43bf115d2/deltachat-ios/Chat/ChatViewController.swift#L918 - this is probably the part that needs a closer look.

**Comment by r10s** [comment]
i found a way to reproduce: it is a race condition, the `self.draft.draftText` may be empty by some other call cleaning up the input line. 

if you force a delay using `DispatchQueue.global().asyncAfter(deadline: .now() + 1) {` instead of `DispatchQueue.global().async {` this happens every time. i think, the bug is in "forever" :)

**Comment by cyBerta** [comment]
great catch! 
I didn't test it yet but I think it might be sufficient to move the line `if let draftText = self.draft.draftText {` outsite of the async block. The resetting of the input field happens on line 1194, just after the call self.sendTextMessage()

**Comment by r10s** [comment]
yip, i do a pr, i think it is better to give text and the quote to send as parameter.
