### ISSUE TITLE
Linking with cc failed ios, maybe because of "Big Sur"

### ISSUE THREAD

**Issue by sandeesaripalli** [deltachat/deltachat-ios#1020]
- Device:Simulator Xcode 12
- iOS version: IOS13
- Delta Chat version: Latest
- Expected behavior:Should build
- Actual behavior: Build is failing
- Steps to reproduce the problem: Follow the instructions on the page, do pod install and open the app in xcode and do build
- Screenshots:
- Logs:Building "deltachat_ffi" for "aarch64-apple-ios"
   Compiling proc-macro2 v1.0.24
   Compiling syn v1.0.42
   Compiling libc v0.2.78
   Compiling memchr v2.3.3
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64"

**Comment by r10s** [comment]
did you also set up rust as described and does `cc` is running otherwise? is there some more detailed log? did you try to search for the error? what do you want to achieve?

**Comment by sandeesaripalli** [comment]
> did you also set up rust as described and does `cc` is running otherwise? is there some more detailed log? did you try to search for the error? what do you want to achieve?

Thank you for the reply. Yes I did install rust, I have detailed log but my computer name is there hence I didn't post it here yes it's been 3 days since I am facing this issue finally I had to raise the bug. I haven't found any solution yet I am super confused if I am missing any step.

**Comment by r10s** [comment]
`cc --version` for me prints:
```
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
maybe your version is just too new :) new version often come with new problems, tbh, i am already a bit afraid of "Big Sur" :) - are you using "Big Sur"? if so, and if you find a solution, it would be great, if you can post it here :)

**Comment by sandeesaripalli** [comment]
> `cc --version` for me prints:
> 
> ```
> Apple clang version 11.0.3 (clang-1103.0.32.62)
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> ```
> 
> maybe your version is just too new :) new version often come with new problems, tbh, i am already a bit afraid of "Big Sur" :) - are you using "Big Sur"? if so, and if you find a solution, it would be great, if you can post it here :)

cc --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

is it because of installation directory i am having issue?

Yes sir I am using Big Sur yes will try to find the solution I have been trying this last 3 days.

**Comment by r10s** [comment]
i am not yet on "Big Sur" (and i will postpone that as long as possible) - so, sorry, i cannot directly help on that issue (assuming it is related to "Big Sur")

**Comment by r10s** [comment]
closing this, there is no direct actionable item.

@sandeesaripalli if you have more information wrt building on "Big Sur", if course, they are very welcome here!

**Comment by nstax** [comment]
[fix-big-sur-building.patch.txt](https://github.com/deltachat/deltachat-ios/files/6056781/fix-big-sur-building.patch.txt)

**Comment by r10s** [comment]
thanks a lot!

@nstax so, in general, building works on BigSur?

**Comment by nstax** [comment]
@r10s yes
![Screenshot 2021-02-28 at 18 14 24](https://user-images.githubusercontent.com/79792014/109428879-e8d02880-79f0-11eb-8df2-8a1d0618eb46.png)

**Comment by r10s** [comment]
great, that's good to know, sooner or later we have also to update, however, after all experiences with that, i try to do that generally more later than sooner :) cc @cyBerta
