### ISSUE TITLE
In IOS it's showing "No such module 'DcCore

### ISSUE THREAD

**Issue by cheerios911** [deltachat/deltachat-ios#1022]
We are in the process of loading iOS DC application and have run into an issue where the library labeled, 'DcCORE' can not be found.  I went through rust and the other packages and can not find this for the life of me.

Can you guys help direct to where it is?

we are on the current build: 1.14.4

**Comment by r10s** [comment]
> We are in the process of loading iOS DC application

what do you mean with that? have you installed the app from the app store? or are you trying to build the app on your own?

**Comment by cheerios911** [comment]
sorry, maybe I wasn't clear, yes we are trying to build the iOS app on our end and run into this issue that DCcore is not available.

**Comment by cyBerta** [comment]
It might be that you didn't compile the core library.
did you do a `git submodule update --init --recursive`?

**Comment by r10s** [comment]
closing this, there is no direct actionable item.
