### ISSUE TITLE
Add multi-select in chats

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1024]
* add an option in the context menu to enable multi-select mode
* when multi-select mode enabled, replace messageInputBar by a control containing a 'delete' button, in a further iteration we'll add 'forward there as well
* add an option to cancel multi-selection: @r10s I would propose to add another 'cancel' button next to the delete button, what do you think?
* highlight selected messages, but for now there's no need to implement fancy UI to indicate the selection
* delete multiple messages on tap on 'delete'

**Comment by cyBerta** [comment]
depends on #1009

**Comment by r10s** [comment]
> add an option to cancel multi-selection: @r10s I would propose to add another 'cancel' button next to the delete button, what do you think?

telegram/signal/ios-messenger add the cancel button in the upper right corner of the title bar; whatsapp does not have multi-select (or i did not found it :) - however, i also do not find that too meaningful - usually the upper right corner has the meaning "ok", "forward", "continue", sth. like that, also in telegram/signal/ios-messenger.

so, i'd say, having the "cancel" in the lower-left corner of the input-bar seems to be at least as reasonable, esp. as this is probably easier to implement.
