### ISSUE TITLE
weird enlarging of image in gallery

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1025]
for the new gallery-context-menu, at https://github.com/deltachat/deltachat-ios/pull/985#issuecomment-726792484 i suggested that a tap inside the preview-image of the context-menu should directly enlarges the image; similar to the ios gallery.

some changes were done, however, the current state is not really nice :)

a tap on the preview-image first closes the preview with some animation and then, with another animation, the fullscreen-view is opened. this looks weird and is imho unexpected to the user. normally, animations should help to follow what is going on, this is not the case here.

so, we should either:
1. get rid of the useless stopover - the mentioned ios gallery does not do this stopover as well. please heave a look at the system gallery or on whatsapp, EDIT: i would not do 1. for now, see reasoning below
2. or close the context menu on a tap as before - that would be better as the current state as well. telegram does the same, just closes the context-menu

for 2., that is probably just some code-removal. so, i would be fine with 2. as well :)

**Comment by cyBerta** [comment]
https://developer.apple.com/documentation/quicklook/qlpreviewcontrollerdelegate/1617007-previewcontroller?language=objc looks promising to improve the transition animation for all previewed items (e.g. documents, images in the chat, too). I'll play with that a little bit

**Comment by r10s** [comment]
> I'll play with that a little bit

great! if that gets too complicated, however, as said, just closing the preview is also fine for now.

**Comment by r10s** [comment]
playing around with that for a day, i'd say it is fine to just always close on pressing preview-image/docs/whatever. our preview is probably not integrate enough to make this really a smooth ux.

but even when this is the case: there are also large images, texts etc. that may make it hard to close the preview. eg. also other apps close the preview on pressing preview-image (whatsapp), so it is not unexpected.

therefore, my suggestion:
- leave closing preview in chat as it is now (just close)
- do the same for the preview in the gallery

this is probably very easy to implement and does not raise new issues as the inability to close preview.
