### ISSUE TITLE
Add multi-select in document and image gallery

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1029]
similar to  #1024

* add an option in the context menu to enable multi-select mode
* when multi-select mode enabled, show a control at the bottom of the screen, containing a 'delete' button
* add an option to cancel multi-selection:add another 'cancel' button left to the delete button
* highlight selected messages, but for now there's no need to implement fancy UI to indicate the selection
* delete multiple messages on tap on 'delete'

**Comment by r10s** [comment]
depends a bit on the effort, but i assume that will need more than, say, a handful hours. if so, i'd say there are issues that have a larger impact, eg. #1032 #1039 and of course bugs.

just to priorise things a bit :)

**Comment by r10s** [comment]
moving issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
