### ISSUE TITLE
Add button to scroll to the bottom of the chat

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#1032]
Almost all other messengers have this, and I found myself wishing for this recently again. 

- Hidden by default.
- When scrolling up, such that the last message is not visible anymore, show a button at the right bottom corner, above the input field, that when tapped scrolls to the bottom of the chat again.

**Comment by r10s** [comment]
yip, this is missing, we have the same on android.

the button will become even more important if we start opening the chat at the first unread message (also, as on android :)
