### ISSUE TITLE
failure when connecting to gmail account

### ISSUE THREAD

**Issue by gotcha** [deltachat/deltachat-ios#1034]
- Operating System (Linux/Mac/Windows/iOS/Android): IOS 14.3
- Delta Chat Version: 1.14.4
- Expected behavior: Success when using gmail account for the initial server connection.
- Actual behavior: I see two behaviors when I try it from scratch - uninstall app and delete all data.
1) When trying with just username and password, the ```server connection 80%``` dialog is shown then the process stops and connection screen remains shown.

2) When using advanced setup, I specify SSL for both imap.gmail.com and smtp.gmail.com, I get:
Setup error Please check email address and password.
The email in the error message is the one I use.
```no response: code: None, info: Some("[AUTHENTICATIONFAILED] Invalid credentials (Failure)")```

 I tried more than 10 times after confirming the password in standard gmail UI. I checked again in gmail UI after DeltaChat setup failure to confirm that the password is not blocked.

**Comment by gotcha** [comment]
If I fiddle with the advanced setup by not specifying all fields, I get both behaviours described above: stopping at 80% without success or authenticationfailed.

**Comment by gotcha** [comment]
I dug deeper and found the FAQ page about providers.
I had missed the "less secure app" setup.

Nevertheless, after enabling "less secure app", connection still does not work.
See attached screenshot
<img width="281" alt="Screen Shot 2021-01-18 at 17 36 06" src="https://user-images.githubusercontent.com/105204/104942106-4ca81000-59b4-11eb-99f7-889ba0b05d4f.png">

The URL points to email clients setup for gmail which I followed step by step.

Any pointers ?

**Comment by gotcha** [comment]
My last attempt succeded. I installed the desktop client then managed to setup connection to my gmail account.

When going back to IOS, connection did work right away.

Any hint about what could have happened ?

**Comment by gotcha** [comment]
After a while, the IOS app sets a message that it cannot connect to the server anymore.

IOW, no functionality anymore.

**Comment by gotcha** [comment]
FTR, setting up 2FA and adding an app password enabled the functionality.

**Comment by r10s** [comment]
thanks for diving into the issue and to document that here 👍 

iirc, we "solved" that on android by making urls in the error messages clickable, that helped a lot. i think, this part is missing on ios. and, of course, oauth2 is still missing for gmail as well https://github.com/deltachat/deltachat-ios/issues/92
