### ISSUE TITLE
Cannot select highlighted phone number

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#1037]
Currently only the bubble is activated, but I can't directly interact with highlighted phone numbers

**Comment by cyBerta** [comment]
yes, it's nothing implemented there yet (besides a debugging message). We should define how the interaction should look like.

**Comment by r10s** [comment]
i'd say open the phone app with that number (i assume dialing is not started automatically)

**Comment by dignifiedquire** [comment]
there is a dialog thing which asks if you want to call or copy the number usually

**Comment by cyBerta** [comment]
For now we just do the bare minumum, open a tel:// url containing the phone number. iOS handles the rest (e.g. the confirmation dialog)
