### ISSUE TITLE
improve forward workflow

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1039]
- when forwarding is cancelled already in the "select-forward-destination chatlist", one should get back to the chat where forwarding was started.  
currently, one just stays in the "main chatlist".  
(cancelling forwarding later in a selected chat is fine - that brings one back to the "select-forward-destination chatlist")

- when "saved messages" is selected in the "select-forward-destination chatlist", the message is saved without further questions,  which is great.  
however, it would be even better when, after saving, the user comes back to the original chat from where forwarding was started. this allows "saving" a message quickly by two taps without leaving the context.  

- there should be some feedback on the screen after "saving" - [on android, we're using a "toast"](https://github.com/deltachat/deltachat-android/pull/1651), that does not exist on ios, however, there are probably alternatives (sth. easy without extra additional libs, if possible)

esp. the last two points will give usability a boost :)

**Comment by cyBerta** [comment]
> there should be some feedback on the screen after "saving" - on android, we're using a "toast", that does not exist on ios, however, there are probably alternatives (sth. easy without extra additional libs, if possible)

that's another usecase for https://github.com/SwiftKickMobile/SwiftMessages

having in mind https://github.com/deltachat/deltachat-ios/issues/1188 and https://github.com/deltachat/deltachat-ios/issues/878 I think it is worth it to use the library for our needs.

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
