### ISSUE TITLE
improve chat list accessibility

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1041]
User feedback:

>  In der Liste der Chats sieht man glaube ich nicht, ob in einem Verlauf 
(also mit einem Kontakt) eine ungelesene Nachricht ist.

That's not correct, the last element that is read out is the number of unread messages. 
However we whould change the order of read elements, first the title, then the number of unread messages, then last message time, then the last message content. 
The number of unread messages accessibility should contain some context like: "$d unread messages" instead of only the number.

**Comment by r10s** [comment]
moving feature request to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
