### ISSUE TITLE
Cant log in on compiled client

### ISSUE THREAD

**Issue by BlackjackFury** [deltachat/deltachat-ios#1045]
I builded new client using guide. But i cant log in into my server. It freezes after i press login button. In the xCode logs i`m getting the message "Ignoring careless call on dc_configure()" Do u have any idea what is wrong?
 
Im using iphone 7 with IOS 14.2 and XCode 12

**Comment by r10s** [comment]
just had a closer look, for whatever reason, the contextPointer is released.

do you have ios coding skills? i would try to debug that in an emulator, then you will see better what is going on.
if you find the problem, it would be great if you report it here.

in geneal: do you want to contribute to the ios delta chat client? why do you want to compile?

**Comment by BlackjackFury** [comment]
Yes, i can do some coding in Swift and i think it is something with DcCore. I tried to look through c code but didnt find where it was generating this error. I can try to debug it if you have any advise what i have to look for. 

I want to compile my own client so i can implement background push through APN and fetch new messages from server or just notify user that he has a new message (without message text). Right now it is not always notify user about messages on default client.

**Comment by r10s** [comment]
thanks for the explanations. 

you would need a token from apple to do APN, or?  
how do you plan to get that?  
or is there kind of "playground" if you just compile the app for your own?

> I tried to look through c code 

no sure what you mean here, there is only rust-code and swift-code, the error is generated at https://github.com/deltachat/deltachat-core-rust/blob/master/deltachat-ffi/src/lib.rs#L269

**Comment by BlackjackFury** [comment]
I will make a p8 certificate on the apple dev site and using it and some extra info (project bundle name , team id .. etc ) I can make an authorization token. Using authorization token and device id which I'll get from device when i'll start app, I can send a remote push notification with any data I want. To get info like p8, teamID and bundleId I have to compile project on my own. 

I was looking at the old C core. Already figured it out that now it is on rust. I compile rust core on my Mac and it is working ok (at least I can make a configuration and login to the server using commands in the terminal). I check dcContext in runtime and it is "nil" in the login function in the AccountSetupController.

**Comment by BlackjackFury** [comment]
Got it working!
Problem was that group identifier is hard coded in DatabaseHelper but after opening Xcode project you have to change Team and bundleId (because they have to be unique for every user). Changing group id in the DatabaseHelper to mine solved the problem

**Comment by r10s** [comment]
thanks for coming back and reporting. indeed we are also thinking about getting APN work somehow. would be great if you can contact me at r10s at b44t.com (address from my github profile), maybe we can have a call or so.
