### ISSUE TITLE
add option to view full (html) message

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1046]
this should be targeted after merging https://github.com/deltachat/deltachat-android/pull/1763, so that strings are available and we're already through most pitfalls :)

once merged, however,
1. add a button "Show full message" (string `show_full_message`) inside the bubble of messages when [`dc_msg_has_html()`](https://c.delta.chat/classdc__msg__t.html#aab7b069edb647e01311ee675b267d99a) is true (this can happen also for _outgoing_ messages, eg. when html-messages are forwarded or messages sent with another mua support)

2. a tap in the button shall open sth. as a `FullMsgViewController` that can display HTML, similar to the one we're already using for the `HelpViewController`. the latter has surprisingly little code, however, it is probably still reasonable to use a common base class as `WebViewViewController` (sic!) - sooner or later we will add sth. as "search", that way, all HTML-views will benefit from that (naming scheme is borrowed from android, btw, makes sense to keep that)

3. once `FullMsgViewController` is opened, configure the used [`WKWebView` to disable scripts](https://stackoverflow.com/questions/34404481/swift-wkwebview-disable-javascript) (they're enabled by default) and somehow to not load remote content (unless configured by the user differently, see below).  then, the HTML can be retrieved using [`dc_get_msg_html()`](https://c.delta.chat/classdc__context__t.html#aaedfc31d404f1adbd266cfd663ee78bc). i suggest to do this async to not block the ui.

4. in the upper-right-corner, add a button to toggle loading remote content. the button shall opens a `safeActionSheet` with the title=`load_remote_content`, text=`load_remote_content_ask` and the buttons `always`, `never`, `once` and the obligatory `cancel`. see the [android screenshot](https://github.com/deltachat/deltachat-android/pull/1763) to get an idea.
a setting as `Bool AlwaysLoadRemoteContent` should be persisted somewhere and respected on subsequent openings of the `FullMsgViewController`

related: https://github.com/deltachat/deltachat-desktop/issues/2078, https://github.com/deltachat/deltachat-android/pull/1763, https://github.com/deltachat/deltachat-core-rust/pull/2125

**Comment by cyBerta** [comment]
>     4\. a setting as `Bool AlwaysLoadRemoteContent` should be persisted somewhere and respected on subsequent openings of the `FullMsgViewController`

Shouldn't that also be acessible from the settings menu? It might be unexpected that the user needs first to open a message in order to change the settings back to never for example.
