### ISSUE TITLE
date/delivery display sometimes hidden in new multi-select mode

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1053]
when starting multi-select mode, the bubbles get a bit less width to make place for the checkmarks.

as the height of the rows stays as is (which is correct!), depending on the bubble-content, text may be wrapped differently, resulting in the last line becoming invisible.

as we cannot modify the height of the rows (that would make things shifting around and result in really bad ux), we could:

1. leave also the width of the bubbles but reduce the margin, that should make enough place for the checkmarks (the margin is used to distinguish better between incoming and outgoing bubbles, for a nicer view)

2. move bubbles a bit right outside (that could be needed in addition to 1. as well)

3. ignore the issue

not sure how hard it is, 3. is only an option if that is really hard :) otherwise i would be in favor to 1.

EDIT: here are two screenshots (i was disturbed while filing the issue . if i would have added them right away, @Hocuri would be less confused probably :)

as you can see below, the first and the last date/delivery display in selection mode is missing.

what i would also consider: unless there are reasons to do otherwise, i think, both modes should have the same input-bar-height. this would lead is smoother animations when hitting eg. cancel as nothing needs to be shifted  vertically (currently, there are some pixel difference)

<img width=300 src=https://user-images.githubusercontent.com/9800740/107572959-383ee800-6bed-11eb-9dde-26786d4aed88.png> <img width=300 src=https://user-images.githubusercontent.com/9800740/107572948-34ab6100-6bed-11eb-83dd-ca7907345d21.png>

**Comment by cyBerta** [comment]
What telegram seems to do is to constraint the width of the selection accessory view so that the message bubbles always keep the same size and are just shifted. I'll try to figure out how to archieve that.

**Comment by r10s** [comment]
that would be a great  solution 👌

if it is not doable or too complicated, well, we can probably also life with the current thing and go for point 3. :)
