### ISSUE TITLE
Display contact status in the profile

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-ios#1055]
See related core PR: https://github.com/deltachat/deltachat-core-rust/pull/2218

New API is `dc_contact_get_status`

**Comment by r10s** [comment]
meanwhile, there are [screenshots from android](https://github.com/deltachat/deltachat-android/pull/1805) and a [mockup from desktop](https://github.com/deltachat/deltachat-desktop/pull/2126#issuecomment-793999988).

for ios, i think, 

- we should add a complete section to the contact-profile with the usual upper-case title of the string `pref_default_status_label`

- the section should be placed between the first section and second section, so between "Send message" and "Shared chats"

- the section will have only one item, the signature-text. if would be great if links in this text are clickable.

- if dc_contact_get_status() returns an empty string, the whole section can disappear. 

- wrt scrolling: it is okay if the signature-text grows in height, the most-important functions are above this section and the whole ViewController is scrollable anyway
