### ISSUE TITLE
background missing for input bar

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1063]
the input back lacks a background, there is just the thin line above.

the background should be white/lite or black/dark.

imu the bug is new and not released, might be introduced in https://github.com/deltachat/deltachat-ios/pull/1060

**Comment by r10s** [comment]
appendment: also the background for the quote preview is missing.

**Comment by r10s** [comment]
the issue is still there, happens everytime i open a chat without a draft. it happens in lite and darkmode.

![image_2021-03-02_12-59-27](https://user-images.githubusercontent.com/9800740/109652155-b2fd8200-7b5f-11eb-97ce-99dcdc4d4d3b.png)
![image_2021-03-02_12-59-40](https://user-images.githubusercontent.com/9800740/109652168-b5f87280-7b5f-11eb-890a-95f30928d8f7.png)

it is only okay, when i open a chat with a draft. i will double-check, it is really introduced by #1060

iphone7 with ios14

**Comment by r10s** [comment]
> i will double-check, it is really introduced by #1060

i can confirm that, removing the line 

```
messageInputBar.backgroundColor = DcColors.chatBackgroundColor
```

that was added in #1060 to stop flashing, fixes this issue.

**Comment by cyBerta** [comment]
Can you please double check, that you run latest master? It's not happening for me anymore. 
The reason for the bug was that chatBackgroundColor was transparent but that's fixed, I checked on my phone with latest master and I cannot reproduce that bug anymore. 
Otherwise. how exactly do you get into that transparent state? You just enter a chat that has a draft?

**Comment by r10s** [comment]
yip, i will double check later and rebuild from scratch to be really sure.

**Comment by r10s** [comment]
i rebuild from scratch, and the issue is gone. or there is another reason causing the issue :) however, closing this again :)
