### ISSUE TITLE
Call stop_io()/start_io() before/after backup export

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-ios#1065]
See https://github.com/deltachat/deltachat-core-rust/pull/2255

For Android, I already made a PR: https://github.com/deltachat/deltachat-android/pull/1822/files

For backup import it's not necessary as IO is not running before doing an import.

For key import/export, it doesn't hurt but isn't necessary.

**Comment by r10s** [comment]
is it only about export or also import? or just all calls to dc_imex?

**Comment by Hocuri** [comment]
Whatever is the easiest to implement :)

Before import the IO is probably not running anyway (if it is, then it needs to be stopped, too)
