### ISSUE TITLE
missing items in chat-list-view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#107]
the chat-list-view misses some items:
- time
- number of unread messages
- state of last message (delivered, sent, read, failed)

**Comment by nayooti** [comment]
![IMG_3061](https://user-images.githubusercontent.com/5249565/59350381-3b991680-8d1c-11e9-934d-fcb2f43789ea.png)

That's how it currently looking.
Time and state is showing. 

@r10s Where shall the number of unread messages be displayed?
