### ISSUE TITLE
read receipts are sent too soon

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1074]
read receipts are already sent when the message is displayed in the chatlist, came over that when trying to find out the bug for https://github.com/deltachat/deltachat-core-rust/issues/2285

**Comment by cyBerta** [comment]
I couldn't reproduce the described behavior. I've pushed a branch adding some logs when markSeenMessages() is called. 
Codewise it looks more or less ok. The check for completely visible cells could be improved. It is used to mark all messages as read that are "rendered" (but currently not necessarily visible) after scrolling ended.

**Comment by cyBerta** [comment]
I've created a PR that you could check out for further debugging. #1077 
It also contains a small fix for marking messages that are immediately visble after the chat view appears. It is basically the same as on Android now: https://github.com/deltachat/deltachat-android/blob/720f553717a91b77327ef29289dc5bdbf5ce92ee/src/org/thoughtcrime/securesms/ConversationFragment.java#L240

**Comment by cyBerta** [comment]
For some reason the [WIP] PR was merged, by me? I cannot recall how this happened. Anyways. I'll do another PR removing the logs.

**Comment by cyBerta** [comment]
@r10s can it be that this was an multi-device issue and another client marked the messages already as marked? I stumbled over a similar issue today while working on notifications

**Comment by r10s** [comment]
that might be, i did not came to further investigations ...

**Comment by cyBerta** [comment]
@r10s I would like to suggest to close this ticket. I couldn't reproduce the issue.

**Comment by r10s** [comment]
k, might be, the issue was on android, and i mixed sth. up :)

**Comment by r10s** [comment]
i could reproduce that in a slightly different way, filed a new issue at https://github.com/deltachat/deltachat-ios/issues/1178
