### ISSUE TITLE
Notifications are not always cleared

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#1080]
Not sure what triggers this, but sometimes when going into deltachat after seeing a notification and leave, the notification stays around in ios and is not cleared, even though I read the message.

**Comment by cyBerta** [comment]
What we didn't do before at all was to delete programmatically notifications if the user entered a chat that has unread notifications. That feature/fix will land with #1124 

I'm not sure if that is exactly the case you mean here though.

**Comment by r10s** [comment]
as with #1124 the notification adding/removing is completely revamped, with pretty good chance, this is fixed as well.

#1124 will land in the next testflight, 1.19 these days then. closing this issue as there is no actionable item left.
