### ISSUE TITLE
too long uptimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1088]
theoretically, the app should be terminated after few minutes after the window is closed, with location streaming enabled, there is an exception.

however, i encountered on my device, that the app does virtually not end, i had location streaming enabled some days ago, however, it is disabled now and the app was restarted and even rebuild several times since then.

the DebugToolkit still shows long uptimes:

<img width=300 src=https://user-images.githubusercontent.com/9800740/111766742-2d3f3d80-88a6-11eb-830e-949e66e2a9ae.png>
(this is from just now, before, i had uptime of 5h, the values comes from core, maybe also uptime is buggy :)

i noticed that since some time, but i did not take care too much about it.
however, i also have the feeling, that the app gets slower, if it runs for hours, maybe a memory leak, stale viewcontrollers or so (that could also be fixed, however, usually, the app won't run that long)

i am also wondering, that even with that uptime, messages do not arrive instantly (they arrive with the new notification-server faster than ever) - so maybe `stop_io` is called but the app is not stopped?

@cyBerta @dignifiedquire do you have an idea? can you check your uptime? it should not be longer than a few minutes.

**Comment by cyBerta** [comment]
The app get's in a kind of freezed state when it is suspended. network traffic is closed gracefully before, so that the system doesn't kills the app.
