### ISSUE TITLE
Issue building DeltaChat-ios on macOS 11.2.3: ld: library not found for -lSystem

### ISSUE THREAD

**Issue by jem5519** [deltachat/deltachat-ios#1097]
- Operating System iOS
- Build Environment: macOS Big Sur 11.2.3 (20D91)
- Xcode Version 12.4 (12D4e)
Getting build error:  ld: library not found for -lSystem

Looks like I need to add  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib to the search path but don't know
where to do that.

Thanks for your help - Jim Malak

Log attached
[Build target DcCore_2021-03-21T10-43-33.txt](https://github.com/deltachat/deltachat-ios/files/6177764/Build.target.DcCore_2021-03-21T10-43-33.txt)

**Comment by cyBerta** [comment]
this has been fixed with #1125
