### ISSUE TITLE
Hidden chat list

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1111]
when the search bar in the chat list is active, the user taps on 'QR-Code' and taps back on 'Chats', the chat list is hidden.

**Comment by cyBerta** [comment]
@Jikstra do you have an iOS12 device? if so, could you please try to reproduce the bug?

**Comment by Jikstra** [comment]
Nope cannot reproduce on ios12. Version is v1.17.0 but with some commit of @r10s i guess for the notification things.

**Comment by cyBerta** [comment]
closing for now, as I only saw it on an ios12 emulator.
