### ISSUE TITLE
make emoji-only messages bigger

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1118]
on android/desktop, messages containing only emojis are shown bigger:

<img width="376" alt="Screen Shot 2021-03-31 at 10 49 06" src="https://user-images.githubusercontent.com/9800740/113117870-2c47cd80-920f-11eb-9ffa-8f2f3b1d8c61.png">

would be great to have that on ios as well.

**Comment by cyBerta** [comment]
https://gist.github.com/krummler/8aac35e2446d34791ad8e95d792aaa38

**Comment by r10s** [comment]
moving  feature request to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/1807
