### ISSUE TITLE
DBDebugToolkit logs incomplete

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1131]
the logs shown in DBDebugToolkit are incomplete from time to time, they miss recent loglines sometimes.

these lines will be added later, so, my assumption is that there is some kind of flush() missing (logging itself is done using the SwiftyBeaver toolkit).

this is especially disadvantageous for the crash reports - here the log ends a minute before the crash ... see eg. #1129

**Comment by cyBerta** [comment]
I'll update the dependencies and investigate then further. When I'm at it I would like to change the way we're handling them generally, because updating a single pod became very cumbersome. Just try pod update SwiftyBeaver for example. You'll see that almost all depedecies are affected by changes. Currently we're committing the pods, instead I would like to go for this recommended way: https://guides.cocoapods.org/using/pod-install-vs-update.html

**Comment by r10s** [comment]
yip, tbh, i also have no good idea how these pods are really handled correctly, any improvement there is welcome.

if you're on it, maybe also add some documentation on that to `docs/pods.md`or so - not so much about which pods are used, but how to update or delete them, or at least a link. that seems not to be that simple ...

**Comment by cyBerta** [comment]
interesting log entry:
`[DBDebugToolkit] The app is running under the debugger. It may not generate crash reports correctly.`

**Comment by cyBerta** [comment]
I've created a ticket upstream : 
https://github.com/dbukowski/DBDebugToolkit/issues/49

**Comment by cyBerta** [comment]
The ticket https://github.com/dbukowski/DBDebugToolkit/issues/49 was closed, however there are newer versions. Let's update the lib and check if the issue persists.

**Comment by cyBerta** [comment]
@r10s the latest DBDebugToolkit requires ios13 as minimal ios version. I think we could drop ios11 soonish, but I'm not sure about ios12. Unfortunately statistics often add up all ios versions prior to ios 14 to one category called 'other versions': 
https://developer.apple.com/support/app-store/
https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide

**Comment by r10s** [comment]
according to https://de.wikipedia.org/wiki/Liste_von_iOS-Ger%C3%A4ten , setting minimal iOS version to 13 would drop support for iPhone 6 (2014), iPod Touch 6 (2015), iPad Mini 3 (2014), iPad Air 1 (2013) - all other devices were not supported before or are still supported.

**Comment by r10s** [comment]
let's move that out of 1.30, we worked around the issues with https://github.com/deltachat/deltachat-ios/pull/1560 and https://github.com/deltachat/deltachat-ios/pull/1542 somehow.

**Comment by r10s** [comment]
closed by the removal of DBDebugToolkit in https://github.com/deltachat/deltachat-ios/pulls?q=is%3Apr+is%3Aclosed
