### ISSUE TITLE
Very slow notification

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-ios#1143]
- Operating System (Linux/Mac/Windows/iOS/Android): iOS 14.4.2
- Delta Chat Version: 1.16.0
- Expected behavior: Notification within a minute or two
- Actual behavior: No notification at all on the iPhone for received messages, sent messages are notified at the addressees Android after about 10 minutes.
- Steps to reproduce the problem: Install and test sending and receiving messages.
- Screenshots: none
- Logs:

Running on an Iphone 8.
It's important to get notifications. They are enabled in the settings, but no notifications are received. (Works for other apps.)
If 10 minutes is the normal time for checking the account, please make it possible to check more frequently. (Might that influence the battery usage very badly?)

**Comment by r10s** [comment]
this is improved since 1.17, if the phone is "in use" (so, not laying on the table, low battery or so), the app checks for new messages about every 20 minutes, in practice even faster, on my phone about every 6 minutes.

1.17 is available in apples "testflight" app store, see https://delta.chat/en/download#preview-builds

**Comment by havet** [comment]
Is it possible to close the duplicate? Without closing the issue?

**Comment by r10s** [comment]
> Is it possible to close the duplicate? Without closing the issue?

not sure what you mean :)

as far as i can see, there is no actionable item for notifications currently, there are hints that it is not working sufficiently on ios12, however, we should file a dedicated issue for that as soon as we have more precise information.

**Comment by havet** [comment]
OK to discuss a closed issue?

I just thought about a crazy work around for iOS users who experience great problems:
add an option to send e-mail notifications!

Rational: the e-mail app checks the account very frequently.

If a dedicated account is used for Delta Chat, the user should enter an other e-mail address for notifications.

The notification might look somewhat like e.g.
Subject: New Delta Chat message to read
Body: You have received a new Delta Chat message. Please open Delta Chat to read it.

The notification messages in the inbox might be removed when the user has the Delta Chat app open. (Easy if the same account is used for Delta Chat and notifications - otherwise skip it!)

Yes, I know. This is crazy, but it works!

Eventually, when the notifications work OK no-one will use this option and it can be removed. In the meantime it would make Delta Chat useful for all iOS users.

**Comment by r10s** [comment]
> OK to discuss a closed issue?

sure :)

> I just thought about a crazy work around for iOS users who experience great problems:
> add an option to send e-mail notifications!

not sure if i got the idea correctly - you are suggesting to send and additional mail to the "real" email account when using a dedicated delta account? so that apple mail will notify about the new chat message?

hm - but who shall send that message? and woudn't it be better in that case to just use the same account for email and chat - also in that case, apple mail usually will notifiy sooner.

**Comment by havet** [comment]
Hi,
it would work somewhat like this:

1. The user doesn't get any notifications (or get them with too much delay) from Delta Chat on his iPhone. But his e-mail app checks mail quite often and notifies OK.
2. He/She sets the option: 'Send e-mail notifications' and adds an e-mail address for notifications (Default: the same as used in Delta Chat. If he uses a dedicated account for Delta Chat, different from his mail account, he must enter his e-mail account instead.)
Optional: a test-mail is sent to the notification e-mail address, for verification.
3. DC puts the option "send e-mail notification to 'notification address'" in outgoing chat messages.
e.g. something like "Preference: Send e-mail notification to ***@***.***"
4. The receiving Delta Chat app notices that the other part wants e-mail notifications and sends a notification e-mail to the notification address after each chat message.
5. The original user gets notified by his e-mail application and opens Delta Chat to begin the chat.

**Comment by r10s** [comment]
i see, interesting :)

**Comment by havet** [comment]
Just a thought. I noticed that notifications works for ChatSecure (XMPP).  (But not icon badges, though.) Can we learn something from them?

**Comment by r10s** [comment]
> Can we learn something from them?

ChatSecure is using usual push notifications, it seems, https://github.com/ChatSecure/ChatSecure-iOS/issues/1017#issuecomment-405072167 , so, for sure, it cannot harm to have a more detailed look at that code.

for the background-fetch as we are using, the code looks logically quite similar https://github.com/ChatSecure/ChatSecure-iOS/blob/6a5d4b32b72c552f88a5a0a7ed14fe4b92c3b465/ChatSecureCore/Classes/OTRAppDelegate.swift at a first glance.

**Comment by helmut72** [comment]
Maybe it's possible to use ActiveSync on iOS with Z-Push on the server?

**Comment by r10s** [comment]
> Maybe it's possible to use ActiveSync on iOS with Z-Push on the server?

you mean these ones: https://en.wikipedia.org/wiki/ActiveSync and https://z-push.org ? 

i do not know much about that, maybe i missed something, however, as a first glance i do no see how that could solve the issue that we need a push from a random mail-server _without_ having active support on that server. so - how would eg. web.de or gmx.net communicate with ActiveSync/Z-Push?

**Comment by havet** [comment]
Yes, the notifications are improved in v. 1.20.2. The notifications are still slow, but the app is now usable.
Notifications are shown (but with a great delay) and now icon badges also work. The later is an important achievement.

**Comment by r10s** [comment]
thanks for testing and reporting back, @havet
