### ISSUE TITLE
add support for webp, stickers

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1146]
- webp stickers are already sent around here and there, it seems as if SDWebImage can support that by a plugin, so we should enable that at some point.
cc @adbenitez - or did i get sth. wrong?

- when on that, we should also show the stickers as such, so transparent, without surrounding bubble, currently stickers are displayed as images.

- the emoji keyboard can send stickers, we should consider to send them as such, cmp. #1170

**Comment by cyBerta** [comment]
for reference: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#awebp-coder

**Comment by cyBerta** [comment]
from #1170:

> question is what to do with the text, stickers should not have text. i think, the best would be not to allow adding text at all, eg. whatsapp sends selected stickers directly.

**Comment by cyBerta** [comment]
It seems there's no way to display animated webp files in our PreviewController which inherits from Quick Look QLPreviewController. We could exclude webp files completely from being previewed. In addition to that we could handle webp file always as stickers.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/1245
