### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#115]
hi, would be awesome if every time a new ios release is out, you add a tag on the releases page, it is ok if you just link to testflight (or apple store in a future) so it is easy to track new ios releases for example with delta bots, or for people like me wanting to promote new releases.
Regards,
adb

**Comment by r10s** [comment]
yip, I think we will do this in the way we do it for core and for android.

**Comment by r10s** [comment]
trying to do that now ;)

**Comment by r10s** [comment]
nb: 0.3.3 does not do autoconfigure, so there is no official testflight link. i will try to fix that today.
