### ISSUE TITLE
show-in-chat inaccurate

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1150]
the show-in-chat function in the gallery is inaccurate, at least if you try to go to the message of an older image in a larger chat.

**Comment by cyBerta** [comment]
> the show-in-chat function in the gallery is accurate,

@r10s do you actually mean **_inaccurate_** ?

**Comment by r10s** [comment]
yip, i fixed that typo :)

nb: ChatViewController  works correctly when jumping to search results;  so it is maybe more an issue on the caller side.
