### ISSUE TITLE
Video-Cells should display thumbnails

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#117]
I spend couple hours trying to implement this (using MessageKit) and didn't get any success.

In Utils you can use `generateThumbnailFromVideo` to generate a thumbnail from a video url.

**Comment by r10s** [comment]
there are reports, that ios (not only delta) cannot play the mp4 files generated by android at all, see https://support.delta.chat/t/mp4-video-sent-from-android-does-not-play-on-ios/617/6
