### ISSUE TITLE
send stickers and memojis as stickers

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1170]
you can select stickers and memojis from the apple keyboard; they are sent as images.

it would be nice, if we can sent them as stickers (afaik, stickers are displayed correctly).

question is what to do with the text, stickers should not have text. i think, the best would be not to allow adding text at all, eg. whatsapp sends selected stickers directly.

**Comment by cyBerta** [comment]
closing in favor of #1146

**Comment by r10s** [comment]
this issue was more about sending selected stickers as such, while #1146 was about the supported file formats.

but, yes, we can add a note to #1146
