### ISSUE TITLE
make links in error messages clickable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1188]
error messages sent from the server may contain links as "click here to do this-and-that", therefore, if we show the error messages after configure fails, we should make the links inside the message clickable, if possible. 

on android we did that at https://github.com/deltachat/deltachat-android/pull/1282

this was the outcome of https://github.com/deltachat/deltachat-ios/issues/1034

**Comment by cyBerta** [comment]
This is not possible on iOS without using private APIs in a UIAlertController. 
Our choices are
- using private APIs, unlikely (doesn't affect's the users privacy for example) but not impossible that we get rejected when publishing a release
- using a replacement for UIAlertController, like https://github.com/SwiftKickMobile/SwiftMessages (or an own implementation)

**Comment by cyBerta** [comment]
using a framework like https://github.com/SwiftKickMobile/SwiftMessages would also help us here:  #878

**Comment by cyBerta** [comment]
> using a framework like https://github.com/SwiftKickMobile/SwiftMessages would also help us here: #878

also here: #1039

**Comment by r10s** [comment]
if we do not want to add more frameworks for minor things, assuming this is mainly and issue in the configure-dialog and assuming most times there is only one url, we could also just get the first url from the message and add a "Open Link" button.

**Comment by r10s** [comment]
moving stale feature request to resurrection
