### ISSUE TITLE
are both build scripts needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1192]
@cyberta in Xcode, there is nearly the same script at 

DcCore/Targets/DcCore/Build Phases/Run Script

and at

deltachat-ios/Targets/deltachat-ios/Build Phases/Run Script

the only difference are the relative paths.

- are really both scripts needed?
- if so, i suggest to add a comment atop of each script that changes are required at both places

**Comment by cyBerta** [comment]
so the answer to this question is no :)
