### ISSUE TITLE
[New Chat] - Scan new group feature missing

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#122]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cyBerta** [comment]
@r10s @nayooti is #239 a duplicate of this ticket?

**Comment by r10s** [comment]
i think so; to clearify: the scanners are always the same, the qr-code makes the difference, there are qr-codes for creating a 1:1 chat and qr-codes for joining a group.
