### ISSUE TITLE
Appstore refuses iOS/Rust-core builds because of _mach_vm ...

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-ios#123]
So uploading the current master to appstore (via xcode) triggers a mail that states this: 

> ITMS-90338: Non-public API usage - The app references non-public symbols in deltachat-ios: _mach_vm_allocate, _mach_vm_deallocate, _mach_vm_remap. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/ 

We filed a support request with apple developer support and eventually got this response (after three iterations): 

> I understand from your email that the upload of you build failed and you received an email from no_reply@email.apple.com explaining that it failed due to the presence of the following API calls:
> _mach_vm_allocate, _mach_vm_deallocate, _mach_vm_remap                                                 
> 
>  If you are unable to resolve the issue based on the information provided in the above-mentioned email, or if you believe that the use of those API calls shouldn’t be considered an issue, I would suggest that you get in touch with the Developer Technical Support team.  

@dignifiedquire can we get rid of the use of these API symbols for iOS somehow?  There have been many mails about this now with apple, and failed uploads, so i think for now, if we can somehow remove the use of these APIs (IIRC it's from RPGP or one of its deps), that's the preferable way to go here.

**Comment by r10s** [comment]
I did a grep over  `~/.cargo` and got matches for `mach_vm_allocate`, `mach_vm_deallocate`, `mach_vm_remap` (_without_ underscores) in `vm.rs` which is probably equal to https://github.com/fitzgen/mach/blob/master/src/vm.rs#L26

- these functions are declarations to use the external api, not totally sure where the leading underscore comes from, might belong to the calling convention; at least rust seems not to call into `_mach_vm*()` (with underscore). the premise that there are really `_mach_vm*()`  functions that are disallowed _and_ `mach_vm*()` that are allowed is bit doubtful imho.

- these functions are then called from [`slice-deque-0.1.16/src/mirrored/macos.rs`](https://github.com/gnzlbg/slice_deque/blob/master/src/mirrored/macos.rs#L15)

**Comment by hpk42** [comment]
there is no _mach_vm problem anymore, thanks @dignifiedquire

**Comment by r10s** [comment]
yeah, thanks a lot @dignifiedquire!
