### ISSUE TITLE
photos taken in delta should not appear automatically in the files app

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#124]
not sure why this happens and if it can be prevented, however, if possible, i'd prefer a photo taken from within delta chat not to appear automatically in the files app.

**Comment by dignifiedquire** [comment]
this would drastically break expectations in regards to taking photos under ios. All photos taken can be found in the Photos app in ios by default

**Comment by hpk42** [comment]
On Thu, Jul 04, 2019 at 07:15 -0700, Friedel Ziegelmayer wrote:
> this would drastically break expectations in regards to taking photos under ios. All photos taken can be found in the Photos app in ios by default

curious ... is it possible for a user to disable sharing of Photos with Apple cloud?

**Comment by dignifiedquire** [comment]
> curious ... is it possible for a user to disable sharing of Photos with Apple cloud?

it is

**Comment by r10s** [comment]
> this would drastically break expectations

k, thanks for the info. maybe we should close this issue for now and break expectations at a later point then :)
