### ISSUE TITLE
Keyboard hides and reappears on some devices after sending a message

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1243]
with #1227 and #1232 we've introduced an attempt to keep the keyboard visible even if the send button has been tapped. 
The current implementation leads to a flickering keyboard because it hides and reappears right after tapping on the send button on some devices (reported for iPhone 7), so we need to find another solution to keep the keyboard open.

it might work to overwrite the UI element used as send button and set the value for `canBecomeFirstResponder` to false.

**Comment by cyBerta** [comment]
@r10s could you provide a video just as in #1253 so that I can see the effect you mentioned?

**Comment by r10s** [comment]
i can try, maybe first merge the other open pr in, they are also related to keyboards. we'll see if that happens again then :)

**Comment by r10s** [comment]
cmp #427 , closing this issue as a duplicate
