### ISSUE TITLE
port etc. is disabled during onboarding

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#126]
(or i didn't get something :)

**Comment by r10s** [comment]
the problem is that the coordinator eg. in coordinator?.showImapPortOptions() is nil. the coordinator is only set up in showAccountSetupController() (from the settings screen) but not in presentLoginController()(the initial login screen)

**Comment by nayooti** [comment]
I will take care of this later the day.

**Comment by nayooti** [comment]
I created a branch 'portFix' and tried to fix the issue. 
I can not build DC ATM due #137 so I could not test the fix.

**Comment by r10s** [comment]
cool, i created a pr from that at https://github.com/deltachat/deltachat-ios/pull/139 , will try that out
