### ISSUE TITLE
Video Chat invitation

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1273]
- [x] render video chat invitation correctly (same as on Android)+ (message type is [`DC_MSG_VIDEOCHAT_INVITATION`](https://c.delta.chat/group__DC__MSG.html#ga4289e30c154f83ee76c56bb1fcd8fe85))
- [x] add video chat provider settings to settings menu (setting name is [`webrtc_instance`](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d))
- [x] react to [`DC_QR_WEBRTC_INSTANCE`](https://c.delta.chat/classdc__context__t.html#a34a865a52127ed2cc8c2f016f085086c) on scanning a qr-code (using the existing scanner) and call  [`dc_set_config_from_qr()`](https://c.delta.chat/classdc__context__t.html#ac95d7275f01862fba70169b8cbb937c0)
- [x] add entry "Video chat" to attach menu to allow sending video chat invitations via [`dc_send_videochat_invitation()`](https://c.delta.chat/classdc__context__t.html#aa2995e39153c5007485541da6b5b0f1a)

**Comment by cyBerta** [comment]
related former PR https://github.com/deltachat/deltachat-ios/pull/846

**Comment by r10s** [comment]
i added some links to the first post.

> related former PR #846

i think, this pr is related to #829
