### ISSUE TITLE
Simulator build on not working on m1

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1277]
<img width="836" alt="Screenshot 2021-06-21 at 15 59 45" src="https://user-images.githubusercontent.com/18725968/122774915-e8161780-d2a9-11eb-8f95-b6e20063b7b6.png">

Looks like it needs the `aarch64-apple-ios-sim` target (https://doc.rust-lang.org/nightly/rustc/platform-support/aarch64-apple-ios-sim.html), but that isn't installable via rustup yet:
```
% rustup target add aarch64-apple-ios-sim
error: toolchain '1.50.0-aarch64-apple-darwin' does not contain component 'rust-std' for target 'aarch64-apple-ios-sim'
note: not all platforms have the standard library pre-compiled: https://doc.rust-lang.org/nightly/rustc/platform-support.html
```

I haven't found out how to compile and install it manually yet.

Building DeltaChat core to that target with the option to build the std-lib results in an error, asking us to do what we already did. I't likely some error in the `num-bigint-dig` crate.
```
cargo +nightly build -Zbuild-std --target aarch64-apple-ios-sim
```

```
error: failed to run custom build command for `num-bigint-dig v0.6.1`

Caused by:
  process didn't exit successfully: `/Users/user/Coding/deltachat-ios/deltachat-ios/libraries/deltachat-core-rust/target/debug/build/num-bigint-dig-5f5cfdfb542ad58c/build-script-build` (exit status: 101)
  --- stderr
  error[E0463]: can't find crate for `std`
    |
    = note: the `aarch64-apple-ios-sim` target may not be installed
    = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  error[E0463]: can't find crate for `core`
    |
    = note: the `aarch64-apple-ios-sim` target may not be installed
    = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  warning: autocfg could not probe for `std`
  error[E0463]: can't find crate for `std`
    |
    = note: the `aarch64-apple-ios-sim` target may not be installed
    = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  thread 'main' panicked at 'i128 support was not detected!', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-dig-0.6.1/build.rs:10:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Simon-Laux** [comment]
with upgrading the rustoolchain to 1.57, the std lib is available and I get a bit further:
```
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `/Users/bb/Coding/deltachat-ios/deltachat-ios/libraries/deltachat-core-rust/target/debug/build/openssl-sys-12921f580864fc8e/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_APPLE_IOS_SIM_OPENSSL_NO_VENDOR
  AARCH64_APPLE_IOS_SIM_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset

  --- stderr
  thread 'main' panicked at 'don't know how to configure OpenSSL for aarch64-apple-ios-sim', /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.17.0+1.1.1m/src/lib.rs:283:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Simon-Laux** [comment]
looks like we can't use cargo lipo in the future, we might need a different solution

**Comment by r10s** [comment]
i am getting the following error when trying to build for an simulator on m1:

>  In [...]/deltachat-ios/deltachat-ios/libraries/deltachat-core-rust/target/universal/release/libdeltachat.a(deltachat.deltachat.967d8094-cgu.7.rcgu.o), building for iOS Simulator, but linking in object file built for iOS, file '[...]/deltachat-ios/deltachat-ios/libraries/deltachat-core-rust/target/universal/release/libdeltachat.a' for architecture arm64

there are some hints at https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f , will go through that later on ...

**Comment by r10s** [comment]
found a fix: you have to _exclude_ arm64 for Any iOS Simulator SDK at "View / Navigators / Project / deltachat-ios / Project: deltachat-ios / Excluded Architectures":

![Screenshot 2022-12-08 at 00 05 13](https://user-images.githubusercontent.com/9800740/206316599-7ac8451d-3971-43cb-8dd5-6c309be075db.png)

Same for DcCore and for the Pods.

then, the app works in the simulator on apple silicone :) no totally sure _why_ this fixes the issue :)
