### ISSUE TITLE
Overlapping messages

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1278]
<img src="https://user-images.githubusercontent.com/18725968/122780675-5b6e5800-d2af-11eb-9d73-68a466c03286.jpg" width="50%" />

sometimes messages overlap

**Comment by cyBerta** [comment]
Does it happen on a simulator?

**Comment by Simon-Laux** [comment]
> Does it happen on a simulator?

I don't know, this screenshot is from a real device.

> Which iOS Version are u using?

14.5.1 can also be seen in the screenshot.

> Is the overlapped message a completely different message or is the it the same message that is shown twice?

two different messages.

> Do you have any idea how to reproduce this? I think, I didn't see this before.

unfortunately no, this appeared in normal usage. scrolling did not make it disappear. after reentering the chat the bug was gone and the 3 messages were correctly shown.

**Comment by r10s** [comment]
closing this as there is no actionable item left.
