### ISSUE TITLE
fix share layout for ipads

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1285]
tested on an ipad simulator:

![simulator_screenshot_5CF797B1-18DE-420E-8EFE-EB1D2F601B20](https://user-images.githubusercontent.com/2614900/123321946-eb243880-d533-11eb-980b-f3d62e154f82.png)

**Comment by r10s** [comment]
the greyed out background does not really match phone layouts as well, see https://github.com/deltachat/deltachat-ios/issues/722

**Comment by cyBerta** [comment]
> the greyed-out background does not really match phone layouts as well, see #722 - so, maybe just remove it, there already seems to be some grey-out from the system, the additional grey-out seems not to be needed.

It's the iOS default background, nothing we're altering right now. Also maybe as a reference: https://github.com/deltachat/deltachat-ios/pull/723#issue-419546256
