### ISSUE TITLE
Use UIAccessibility to support disabled people

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#129]
iOS presents very lot of features to make easier usage the apps. For example, VoiceOver users hears accessible hints and uses labeled buttons in the app. Can we use this APIs in Delta Chat?

We can start with [the page](https://developer.apple.com/documentation/uikit/accessibility/supporting_voiceover_in_your_app).

**Comment by r10s** [comment]
hi @OzancanKaratas , thanks for your post.

yip, accessibility is important. do you have experiences in supporting the APIs? are you up in helping there?

**Comment by OzancanKaratas** [comment]
Unfortunetely I don't know Swift or Objective-C, but I can research and I can do something. At least I think so.

**Comment by OzancanKaratas** [comment]
Unfortunately I don't know Swift or Objective-C, but I can research and I can do something. At least I think so.

**Comment by bdorer** [comment]
One small enhancement is a send lable for the message send button. At the moment VO reads plane.

**Comment by cyBerta** [comment]
We'll add first improvements with version 1.0

**Comment by OzancanKaratas** [comment]
The camera controller has unlabeled items. I noticed when I entered the QR scanning screen.

**Comment by bdorer** [comment]
Furthermure, voiceOver isn't able to speak while sending a speech message. May you could allow VO to speak using the phone speaker.

Mit freundlichen Grüßen

Bernd Dorer

**Comment by nayooti** [comment]
I just implemented VoiceOver in another project. 

I could take care of it, but do we already have translations for this?

**Comment by r10s** [comment]
@nayooti why do we need additional translations for making voiceOver make working when sending speech message?

but anyway, l this issue gets a bit out of order. i think, we should add the labels mentioned in this issue and, if voiceOver works in general, and it is an easy fix, we can do this as well. for everything else, we should do an a/v before.

**Comment by nayooti** [comment]
@r10s This can be closed, right?
