### ISSUE TITLE
UI for Quota Report 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1296]
- [ ] A toggle switch in the settings to turn off the automatic(daily) check: config key is `disable_quota_check`
- [ ] (Optional) a button to request a quota report `dc_request_quota_report(context)`

see desktop pr: https://github.com/deltachat/deltachat-desktop/pull/2294

## References
- core pr: https://github.com/deltachat/deltachat-core-rust/pull/2462
- android issue: https://github.com/deltachat/deltachat-android/issues/1973

**Comment by r10s** [comment]
i would postpone that until it is settled which ui is really wanted/needed and until core is merged. might be that at the end, there is no ui needed at all (info goes to connectivity, and maybe quota reports are "good enough" or we can detect wrong ones)

there is a pending desktop-implementation, it makes sense to wait until things are prototypes there.

**Comment by Simon-Laux** [comment]
closing this here not needed anymore, the finished feature won't need extra ui features
