### ISSUE TITLE
add connectivity view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1299]
- [x] in the chatlist's title bar, show the current state as returned from the new api [`dc_get_connectivity()`](https://c.delta.chat/classdc__context__t.html#a80bf9812eb5a50f8eb097cbe72df1096).  
for the state DC_CONNECTIVITY_CONNECTED we show the string "Delta Chat" as before, for the other states, show the strings `connectivity_getting_new_msgs`, `connectivity_connecting` and `connectivity_not_connected` 
we do not want to show dots or other icons currently.
the text should be updated on [`DC_EVENT_CONNECTIVITY_CHANGED`](https://c.delta.chat/group__DC__EVENT.html#ga3ced1bbde752feba46ab089611287d71).
(corresponding [android code](https://github.com/deltachat/deltachat-android/blob/b3fea81bed308275425e0136233465f589cf4fe0/src/org/thoughtcrime/securesms/connect/DcHelper.java#L79))

- [x] a tap on the chatlist's title bar text (so also on "Delta Chat") should open `ConnectivityViewConroller` (based on `WebViewViewController`) that just shows the html-code returned by [`dc_get_connectivity()`](https://c.delta.chat/classdc__context__t.html#a98d41f00d9a96d83a662f39d0fc23afb).  
the page should be updated on [`DC_EVENT_CONNECTIVITY_CHANGED`](https://c.delta.chat/group__DC__EVENT.html#ga3ced1bbde752feba46ab089611287d71).

- [x] the same `ConnectivityViewConroller` should be accessibe from the settings (entry above "help") (maybe with disclosureIndicator and textLabel from `dc_get_connectivity()`, if so, it should also be updated on `DC_EVENT_CONNECTIVITY_CHANGED`)

all that is implemented on android at https://github.com/deltachat/deltachat-android/pull/1860 (cc @Hocuri - did i missed an important point?)

**Comment by Hocuri** [comment]
No, seems to be everything.

Copy-pasting this function because you may need something similar, maybe it speeds things up for you:

```java
  /**
   * Gets a string you can show to the user with basic information about connectivity.
   * @param context
   * @param connectedString Usually "Connected", but when using this as the title in
   *                        ConversationListActivity, we want to write "Delta Chat" there instead.
   * @return
   */
  public static String getConnectivitySummary(Context context, int connectedString) {
      int connectivity = getContext(context).getConnectivity();
      if (connectivity >= DcContext.DC_CONNECTIVITY_CONNECTED) {
          return context.getString(connectedString);
      } else if (connectivity >= DcContext.DC_CONNECTIVITY_WORKING) {
          return context.getString(R.string.connectivity_getting_new_msgs);
      } else if (connectivity >= DcContext.DC_CONNECTIVITY_CONNECTING) {
          return context.getString(R.string.connectivity_connecting);
      } else {
          return context.getString(R.string.connectivity_not_connected);
      }
  }
```

**Comment by cyBerta** [comment]
thanks @Hocuri

**Comment by cyBerta** [comment]
as discussed with @r10s during forwarding we'll keep the 'Forwarding to...' title instead of showing the connection state

**Comment by Hocuri** [comment]
> as discussed with @r10s during forwarding we'll keep the 'Forwarding to...' title instead of showing the connection state

Yes, that's the way it is on Android, too
