### ISSUE TITLE
rename Back button

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1305]
In chat profile we want to have 'Chat' instead of 'Back' as string on the back button

**Comment by r10s** [comment]
nb: a separate view is not needed, there is the option to set the title only, which has some advantages, see https://github.com/deltachat/deltachat-ios/pull/1300/commits/5e39d421088974462ec8241f86c296c20fa21bee

when on it, `backBarButtonItem` is also set probably unnecessarily in SettingsController.
