### ISSUE TITLE
implement search in WebView

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1322]
Especially when reading long HTML emails a search functionality as implemented in Android is very useful.
My use case: I've subscribed a mailing list and get a summary email containing all messages sent over the mailing list each day. The email has a first section showing the topics and below each message added. Having a search allows to easily jump to the message I'm interested.

Also for the help pages / FAQ, a search feature would be a nice improvement.

**Comment by r10s** [comment]
what is the idea ui-wise? maybe we can also target that together with an in-chat search, things as the up/down arrows, maybe a hit-counter are similar; on android, we also targeted [these two things together](https://github.com/deltachat/deltachat-android/issues/1217).

i filed an additional issue for the in-chat-search: https://github.com/deltachat/deltachat-ios/issues/1323 (@cyBerta if you agree on targeting these issues together, feel free to close #1323, we can track both things in one issue then)

**Comment by cyBerta** [comment]
I think it's fine to keep both issues, they target different areas in our code even though the UX ideas shall be consistent. 
That said, I think for the WebView a scroll-over gesture should be sufficient to open the search. Contrary to the chat, in the WebViews the scrollable content starts from the top, so that scroll-over gesture is easily accessible.

**Comment by cyBerta** [comment]
there's an api for iOS 14+ to implement search in WKWebview without any external libraries or extension like https://github.com/sstahurski/SearchWKWebView.

I would prefer to implement that feature for iOS14+ only.

**Comment by r10s** [comment]
yip, having that for  iOS 14+ only is totally fine.

**Comment by r10s** [comment]
moving issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

**Comment by cyBerta** [comment]
Reopening, I would like to keep that on my radar, the lack of search in the webview annoys me too much :)
