### ISSUE TITLE
"Show full message" button overlaps quote if there is no text

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1335]
if there is no text but only a quote and a "Show full message" button, quote and button overlap:

<img width=320 src=https://user-images.githubusercontent.com/9800740/129922764-45cdc5e8-ec1a-469e-80ab-9a42d6d48960.png>

the second message shows the issue - the first one was sent before https://github.com/deltachat/deltachat-core-rust/issues/2475 was fixed - which results in a missing "Show full message" button, which is even worse :)

these kind of message arrive eg. when sending a webpage via apple mail.

maybe core could also be improved in picking up parts, however, the button should be rendered correctly anyway.

**Comment by cyBerta** [comment]
![Simulator Screen Shot - iPhone 12 mini - 2021-09-20 at 16 06 21](https://user-images.githubusercontent.com/2614900/134016369-c318bd34-47ed-4a6d-bd96-8c5eaf44047d.png)



as you can see in the screenshot, I'm currently not able to reproduce the bug.

**Comment by r10s** [comment]
did the quote contain at least one image? maybe this is the combination that causes the issue? image+quote but no text.
