### ISSUE TITLE
get rid of boilerplate headers

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#134]
i suggest to remove all headers in the plain-deltachat-ios files that are maintained by us.

the headers give few information (filename and creator, maybe last editor) that are also out-of-sync in many cases, eg. files are renamed and the header was not updated etc.

i think, as we're using git, this gives a much better overview about the [history](https://github.com/deltachat/deltachat-ios/commits/master) and [contributors](https://github.com/deltachat/deltachat-ios/graphs/contributors).

also, this is in-sync with the current practice in core, core-rust and android.

**Comment by dignifiedquire** [comment]
yes please!
