### ISSUE TITLE
stucked app-badge-counter when archiving a chat with fresh messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1347]
- receive a message, app-badge-counter and chat-badge-counter each shows "1"
- archive the chat with the message without opening

=> chat-badge-counter is removed, however, app-badge-counter stucks at "1".

the "1" is even not removed when the app is restarted.

might be a core issue, that has to be figured out, maybe by just checking if android has the same bug (however, not all android-ui have app-badge-counter)

**Comment by cyBerta** [comment]
So, if I get this right, when archiving chats, we'll mark the corresponding messages as seen.
