### ISSUE TITLE
message-input-bar overlaps bubbles, unneccessary scrolling

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1349]
reported by @paulaluap: the following needs an **iphone x** or a newer device with space below input bar:

- open a chat
- open profile
- go back

-> the input is scrolled down a line or so and overlaps the bubble. i bet, that is exactly the amount of space below the input bar (that is mostly free due to the rounded corners:

<img width=320 src=https://user-images.githubusercontent.com/9800740/132499185-6927149a-ad5e-4edc-af4e-99948fe1a9ab.png>

EDIT: i just tested, this is repoducible eg. in the iphone12mini simulator.

also, there is just unneeded scrolling. i am wondering why we scroll at all (we might have discussed that, but i forgot :) and not just pop the profile.

this unneeded scrolling is visible on all devices: things move in from the top.

**Comment by Gh0stz0x** [comment]
This happens sometimes on Android too, so I think it's a bug not related to the OS 🤔

**Comment by r10s** [comment]
then this is a similar bug on android, ui parts are not shared among systems.

**Comment by Simon-Laux** [comment]
I think there are constraints for this.

**Comment by r10s** [comment]
@cyBerta will know :)
