### ISSUE TITLE
qr code joining broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1362]
eg. on desktop:
- New Chat -> New Group -> enter name -> and hit "QR Invite Code"

on ios:
- scan the QR code -> the process returns much too fast and no group is created, no error is shown

tested on current master, android on ~current master works.

~~did not test the released version yet.~~ EDIT: the bug is not released, so qa seems to work so far 😬

**Comment by cyBerta** [comment]
hm.. works like a charm for me
I've went this path

> New Chat -> New Group -> enter name -> and hit "QR Invite Code"

and a new group was created . I tried several times. For iOS I've compiled the latest version 1fba0598a1f97ea91ea27fa340981a9db1dcbc37.
I also tried the same procedure using another iOS device to create the group and show the QR-code with the same successful result. Do you have any logs?

**Comment by r10s** [comment]
hm, i will try over later on.

did you try to scan a qr code with ios, generated on desktop?

> New Chat -> New Group -> enter name -> and hit "QR Invite Code"

that has to be done on another device, eg. desktop, not on ios.

**Comment by cyBerta** [comment]
> that has to be done on another device, eg. desktop, not on ios.

I did that on desktop, yes

**Comment by cyBerta** [comment]
> did you try to scan a qr code with ios, generated on desktop?

yes

**Comment by r10s** [comment]
k, i cannot reproduce that on current master any longer, maybe a temporary hickup or master was buggy at some point.

thanks for verifying that it works, @cyBerta
