### ISSUE TITLE
can not build latest master - 'no such subcommand: lipo'

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#137]
Building delta-chat from scratch following the README instructions won't build on latest master - get this: 

`info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
info: component 'rust-std' for target 'x86_64-apple-ios' is up to date
error: no such subcommand: `lipo`
`

I remember that I ran into these **lipo**-issues a while back.
@dignifiedquire maybe due to changes on rpgp?

**Comment by dignifiedquire** [comment]
did you install cargo-lipo? (https://github.com/deltachat/deltachat-ios#how-to-build-with-xcode) and is it in your path?

**Comment by nayooti** [comment]
My bad. Obviously I did not! Tx, will try later and close issue.
