### ISSUE TITLE
add qr code scanning

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#138]
the system-camera-app as such can detect qr-codes, however, it does not know how to handle the OPENPGP4FPR-scheme that is used for the contact verification and for the group join.

maybe we can add a hook or somethink like that, would be interesting what the api for that is, for a first step, this might be sufficient - @cyBerta maybe you can do some research on that?

in mid-term, however, i think a dedicated qr-scan button in the bottom-bar would be nice. but that would be the next step.

**Comment by dignifiedquire** [comment]
There is already qrcode scanning built in, which just needs to be extended.

**Comment by dignifiedquire** [comment]
https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/Controller/QrCodeReaderController.swift

**Comment by r10s** [comment]
cool, thanks for the hint, maybe a generic "New Chat / Scan QR code" instead a "New Chat / Scan Group QR code" is just fine - and does not waste place in the bottom-bar.

**Comment by Simon-Laux** [comment]
Registering a custom uri scheme could help:
https://support.delta.chat/t/custom-deltachat-url-uri-scheme/346
For now we could also simply add the OPENPGP4FPR scheme.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/164
