### ISSUE TITLE
Import existing private key?

### ISSUE THREAD

**Issue by fschulze** [deltachat/deltachat-ios#14]
I haven't followed Delta Chat and Autocrypt development very closely. Is there a way to import my existing PGP private key into Delta Chat iOS? Is it at all possible and only the support is missing? I don't mind doing stuff by hand. I remember some talk about setup messages, but I don't know if that is implemented yet or ever will be.

**Comment by hpk42** [comment]
On Mon, Oct 01, 2018 at 23:56 -0700, Florian Schulze wrote:
> I haven't followed Delta Chat and Autocrypt development very closely. Is there a way to import my existing PGP private key into Delta Chat iOS? Is it at all possible and only the support is missing? I don't mind doing stuff by hand. I remember some talk about setup messages, but I don't know if that is implemented yet or ever will be.

Delta/Android and Delta/Desktop can send/receive ASMs (autocrypt setup messages that contain the private key)
between each other.  It's a function of the c-core but an UI needs to implement 
showing/inputting of a 36 digit transfer code. That's not on the immedaite roadmap of
deltachat-ios i think. 

In Android you can also import a private key from the internal storage -- but i let @r10s elaborate on this.
Not sure how it maps to iOS.

Quickly, a higher-level note: likely we'll recommend in the future to use
a dedicated e-mail account for DeltaChat and introduce features that
make the interplay between "regular" and "Delta" account nicer.
Transfering a private key between "regular" and "delta" is then not an issue
then as each e-mail account has its own private key.

**Comment by jonasreinsch** [comment]
There is no UI yet there for iOS and it isn't planned for the minimum viable version (see README).

**Comment by r10s** [comment]
as @fschulze mentioned, we did not plan this for the minimum viable version as there are tons of other things to do that have a broader impact when implemented.

when these things are done, however, i think the Autocrypt Setup Message is possibly one of the first things to be implemented then. as Autocrypt Setup Messages do not require the user to access the filesystem, this is probably superior to import/export file-based keys from internal storage (which is hard on ios, iirc, @hpk42 the core function would be [dc_imex()](https://c.delta.chat/classdc__context__t.html#ab04a07bb49363824f6fe3b03e6aaaca7)).

**Comment by Jikstra** [comment]
Just installed delta-ios on a friends iphone and it works fine but without having a way to share the key in at least on direction this is not really usable in a multi device setup ^^

**Comment by dignifiedquire** [comment]
there is an import backup option, but yes the key sharing protocol is not yet implemented

**Comment by r10s** [comment]
closing this as, meanwhile, we have autocrypt-setup-message support, so there is a way to import a key.

not sure, if a manual key import is needed and rational on devices where things go easily to some clouds, however, in general, feature requests should better be discussed [in the support forum](https://support.delta.chat).
