### ISSUE TITLE
talk about: code indentation

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#140]
currently, the code is indented with tabs, partly with 2 spaces.

in contrast to what i claimed in the past wrt indentation, i suggest to use space-indentation all over. 

if we reformat this, i also suggest to use 4 spaces for indentation, not only 2. iirc, this would be in-sync with rust-core and also more or less with c-core.

**Comment by dignifiedquire** [comment]
Well I don't know where the tabs come from. I setup `swiftformat` to fix exactly this :( https://github.com/deltachat/deltachat-ios/blob/master/.swiftformat

(In regards to 2spaces vs 4spaces I don't mind, just add a check to CI and enforce it, otherwise this will continue to be a mess)

**Comment by r10s** [comment]
> In regards to 2spaces vs 4spaces I don't mind, just add a check to CI and enforce it, otherwise this will continue to be a mess

i don't really mind as well, just scanned through some swift libs (as MessageKit) and 4 spaces seems to be a bit more usual, not sure, however.

**Comment by hpk42** [comment]
+1 on +4 space-indenting in general ;)

**Comment by nayooti** [comment]
I vote 4 spaces just because it is 4 spaces by default in iOS/Xcode.

In case we decide to keep it as it is (2 spaces) it is very easy to configure Xcode using 2 spaces on a specific project.
