### ISSUE TITLE
Clicking a notification banner removes your unsent draft (if any) in the same chat thread

### ISSUE THREAD

**Issue by snan** [deltachat/deltachat-ios#1408]
I have "Persistent banners" notifications on, got two emails from the same person, clicked the first, started writing a reply, needed to look something up, clicked the other banner to get rid of it, but it refreshed the chat with her and removed my unsent draft, I had to start over writing it.

**Comment by cyBerta** [comment]
That is weird, I checked the code, notifications don't interfere with drafts. Drafts are saved as soon as the viewcontroller disappears or the app goes to background.  

I couldn't reproduce the bug with the following settings:
![Screen Shot 2021-12-08 at 12 19 55 PM](https://user-images.githubusercontent.com/2614900/145199999-a978fd90-a8fb-4ab8-9fcd-0f68306f42a1.png)

For some reason saving the draft seemed fo fail in your case. Can you reproduce the bug?

**Comment by cyBerta** [comment]
also: what device / iOS version are you using?

**Comment by snan** [comment]
iPad OS 15.1 on iPad pro 2021. I don't have lockscreen or notification center on, only (persistent) banners, sounds, and badges.

So to reproduce the bug I need to wait for a situation when the same person has emailed me twice while I didn't have Delta Chat open.

I'll tap the banner, it'll take me to the thread, and then I'll type something, and then I'll get bugged by the banner for the next notification in the same thread, tap it, and, if the same bug happens again I'll lose my draft (so ideally I'd just type "test words" or something safely losable like that).

**Comment by cyBerta** [comment]
> and then I'll get bugged by the banner for the next notification in the same thread,

That is what puzzles me. If you are already in the chat, you shouldn't get any new notification, if new emails arrive, you should only see them directly in the message thread. 
If you received two emails of the same person and jump into the corresponding chat (no matter if you tap on the first notification or tap on the corresponding cell in the chat list) _all_ notifications of that chat should be deleted, not only the first one. The situation that you get bugged by a notification of the same email contact while being in that chat _should_ never happen.
(I'm mainly writing this down, to sort my thoughts)

**Comment by cyBerta** [comment]
> I don't have lockscreen or notification center on, only (persistent) banners, sounds, and badges.


Thanks I will retry with these settings.

**Comment by snan** [comment]
You just sent me two notifications ♥ via this GitHub mailing list (which, weirdly, I can't even reply to at all so I couldn't check if drafts disappear) and the second notification persisted even after having tapped the first to get to the chat.

**Comment by snan** [comment]
I just managed to reproduce the bug as described in this threads OP. This is on a newer version of Delta Chat but same behavior; draft disappears as I tap the second banner.

**Comment by cyBerta** [comment]
Perfect, I can reproduce that error now! Thanks a lot for your help!
