### ISSUE TITLE
Weird animation when switching between protrait and landscape 

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1413]
when switching between protrait and landscape 
* in the chat view
* on phone layout
* if the keyboard is not visible in portrait: 

- the accessibityInputBar takes all available space for a part of a second and resizes back to the intended size.

another, somehow related bug:
in chat view, on phone layout, if keyboard is visible in portrait, the input  bar takes the maximum allowed size (about 8 lines) and you switch to landscape and back to portait, the height the text field is wrong (1 line instead of about 8).

**Comment by r10s** [comment]
is that really on purpose in portrait mode:

<img width=320 src=https://user-images.githubusercontent.com/9800740/148599762-23699ccd-8d1c-4bb2-b937-b2c631d8ac1c.PNG>

i find that unexpected, none of the other messengers i tried behave like that. i'd prefer the old view that contains all controls as usual. iirc we also switched away from these views on android (esp. as screens on phones get larger and larger)
