### ISSUE TITLE
speed up opening chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1414]
with recent commits, we speed up going back to the chatlist (#1395) and going back to the chat (#1358).

with these great changes, other slow things are more visible now (before, most things were slow :)

- opening a chat, even an empty (!) chat takes at least half a second on an iphone7 - there is no reason for that, esp. an empty chat should be opened instantly.  
but even for chat with thousands of messages, the bottleneck is probably not the core: we log these timings in `Wrapper.swift` at `logger?.info("⏰ getMessageIds: \(diff) s")` - that takes noticable time, however, it seems to be always a small fraction of overall timing.

i suggest to add temporary more ⏰-logs and see where really the bottleneck is - might be, we cannot do much or not without reasonable effort, however, that would be good to know.

to make it clear: opening a chat is not super-slow, the mentioned iphone7 is quite old. however, if we can get better here, that would still be nice. 

once this is done, we can file an issue to check how the contact-profile opening can be speed up (however, that is even less urgent :).

**Comment by cyBerta** [comment]
example output 

13:56:16.203 💙 INFO ⏰ ChatViewController init diff: 8.094310760498047e-05 s
13:56:16.213 💙 INFO ⏰ ChatViewController loadView diff: 0.0014230012893676758 s
13:56:16.388 💙 INFO ⏰ getMessageIds: 0.14438104629516602 s
13:56:16.584 💙 INFO ⏰ ChatViewController viewDidLoad diff: 0.3716210126876831 s
13:56:16.619 💙 INFO ⏰ ChatViewController viewWillAppear diff: 0.00855398178100586 s
13:56:17.727 💙 INFO ⏰ ChatViewController viewDidAppear diff: 0.001649022102355957 s

Some results: 
Appearantly viewDidLoad takes most of the time. 1/3 - 2/5 of the time in viewDidLoad is spend by the call to core's getMessageIds.
Even though viewDidAppear finishes over a second after viewDidAppear (see timestamps), the time to run the code within viewDidAppear takes much less. The measurements always start **AFTER** the call to the corresponding super method, so that we measure only our own code.
The views already appear after viewWillAppear finished, so the delay in viewDidAppear seems not to have an visual effect.

**Comment by r10s** [comment]
did you also measure for an totally empty view? maybe start with that before trying to tweak tableview.

**Comment by cyBerta** [comment]
yes I did, I can post an example of that, too

**Comment by cyBerta** [comment]
Some more insights:

**Testing Delta Chat group**
17:44:51.767 💙 INFO ⏰ ChatViewController viewDidLoad start

// ------ checking load messages Method...
17:44:51.797 💙 INFO ⏰ ChatViewController viewDidLoad loadMessages
17:44:51.878 💙 INFO ⏰ getMessageIds core: 0.08037793636322021 s
### _17:44:52.050 💙 INFO ⏰ getMessageIds UI: 0.17225301265716553 s_

// call to unread messages has no influence
17:44:52.051 💙 INFO ⏰ getUnreadMessages: 0.00030100345611572266 s

// loading cells is reasonable fast
17:44:52.079 💙 INFO ⏰ ChatViewController reloadData diff: 0.027853965759277344 s
17:44:52.079 💙 INFO ⏰ ChatViewController viewDidLoad loadMessages finished
// ------- done

17:44:52.079 💙 INFO ⏰ ChatViewController viewDidLoad diff: 0.3125300407409668 s

**An empty group**

17:50:36.229 💙 INFO ⏰ ChatViewController viewDidLoad start
17:50:36.262 💙 INFO ⏰ ChatViewController viewDidLoad loadMessages
_17:50:36.289 💙 INFO ⏰ getMessageIds core: 0.027203083038330078 s_
_17:50:36.290 💙 INFO ⏰ getMessageIds UI: 1.0967254638671875e-05 s_
17:50:36.290 💙 INFO ⏰ getUnreadMessages: 0.00013005733489990234 s
_17:50:36.291 💙 INFO ⏰ ChatViewController reloadData diff: 0.00015294551849365234 s_
17:50:36.292 💙 INFO ⏰ ChatViewController viewDidLoad loadMessages finished
17:50:36.292 💙 INFO ⏰ ChatViewController viewDidLoad diff: 0.06277799606323242 s


As you can see, the growth of a message thread not only results in slower loading the message IDs from core, but also the time copying the c data into an swift array increases significantly. Until the UI _really_ has the array of massageIds, it takes about 250ms, which is 80% of the time used in running all methods of viewDidLoad.

**Comment by cyBerta** [comment]
One option would be that we (re)implement kind of lazy loading in case
1. we are not entering the ChatView with the aim to highlighting a particular message (search scenario)
2. we have only few unread messages

Restricting lazy loading as mentioned above to make things easier, we could load the first 50 messages in viewDidLoad and the rest in viewDidAppear (only first time!).

Alternatively, we could research if there's a better way to copy big arrays from c to swift.

**Comment by cyBerta** [comment]
using raw pointers in swift - a nice overview: https://www.raywenderlich.com/7181017-unsafe-swift-using-pointers-and-interacting-with-c

**Comment by cyBerta** [comment]
@r10s preinitializing arrays doesn't have any performance effect

**Comment by cyBerta** [comment]
13:12:50.143 💙 INFO ⏰ getMessageIds core: 0.0810079574584961 s
⏰ dc_array_get_id UI: 0.16287493705749512 s
⏰ append UI: 0.16431808471679688 s
⏰ dc_array_get_id and append UI: 0.16595804691314697 s


I've measured in 3 different loops calling dc_array_get_id, appending to an array and calling both methods within 1 loop.
As you can see, what is costly is iterating over the array itself, not the call to either dc_array_get_id or to append the value to the array. This means that we would gain most from improving the way we're copying the values from the c array to an swift Int array, by avoiding to iterate over the array but using pointer logic.

**Comment by r10s** [comment]
k, i played around a bit, the costs are in dc_array_get_id() calls, the creation of the array in swift is negligible.

in my test with the testing group, which has about 13k messages, btw, the loop took 0.119s without the switf part and 0.120s including the swift part (average, measured multiple times).

unfortunately, we cannot really access dc_array in a faster way, we had some "direct memory" functions in the past for android, however, they were too error prone wrt different cpu etc. and we removed them.  
however, what we could maybe do is to not concert to swift int but keep a DcArray and use that, i will check out the effort.

in general, on my iphone7, the core-db call is always slower btw, so sth. between 200ms and 900ms - on my phone, the bottleneck is not so much the dc_array_get_id()-look therefore. however, of course, it is still worth optimizing that.

**Comment by r10s** [comment]
> however, what we could maybe do is to not convert to swift int but keep a DcArray and use that, i will check out the effort.

it is not too much effort, we already retrurn `DcArray` at some other places, so the general functionality is already there.

what i did:
- returning DcArray from getChatMsgs()
- enhancing dcArray by some functions:

```
    public var isEmpty: Bool {
        return dc_array_get_cnt(dcArrayPointer) == 0
    }

    public subscript(index: Int) -> Int {
        return Int(dc_array_get_id(dcArrayPointer, index))
    }
```

that way, 60 errors i had before were gone :) all that much easier than expected.

there is still the "find-id" missing, but that could be added easily, maybe even in core for speed.

_more complicated_ is that we alter the array by adding/removing DC_MSG_ID_MARKER1 - we cannot do that any longer and need to do that differently somehow; that should be done in preparation, if we want to follow that path.

independently, i have prepared https://github.com/deltachat/deltachat-ios/pull/1418 that should be merged in.

**Comment by cyBerta** [comment]
> k, i played around a bit, the costs are in dc_array_get_id() calls, the creation of the array in swift is negligible, even in the current "stupid" implementation.
> 
> in my test with the testing group, which has about 13k messages, btw, the loop took 0.119s without the switf part and 0.120s including the swift part (average, measured multiple times).

Have you measured the loop only using the swift part, without the call to core too? If you have a look at https://github.com/deltachat/deltachat-ios/issues/1414#issuecomment-989798803 you can see in the 3. log line that looping _**only**_ through the swift array takes about the same time as loopling _**only**_ through the core call (2. log line). Calling both within one loop (4. logline) takes about the same time like looping through a single call, which is also confirmed by your findings ("0.120s"). But that means that **_looping itself_** is costly, not the call to the core.

**Comment by r10s** [comment]
> Have you measured the loop only using the swift part, without the call to core too?

you are right, removing the c-part does not make much difference as well, it seems to be _the loop_ that is expensive as such :/

using this snippet: https://gist.github.com/r10s/45f91f9ae820b7a3835690515383ced3 ...
```
21:56:42.502 💙 INFO ⏰ getChatMsgs: 0.928900957107544 s
21:56:42.619 💙 INFO ⏰ copyAndFreeArray: nix 0.11768209934234619 s
21:56:42.734 💙 INFO ⏰ copyAndFreeArray: c only 0.1142730712890625 s
21:56:42.850 💙 INFO ⏰ copyAndFreeArray: swift only 0.11629307270050049 s
21:56:42.962 💙 INFO ⏰ copyAndFreeArray: both 0.1123499870300293 s
21:56:48.644 💙 INFO ⏰ getChatMsgs: 0.14664506912231445 s
21:56:48.754 💙 INFO ⏰ copyAndFreeArray: nix 0.10958492755889893 s
21:56:48.864 💙 INFO ⏰ copyAndFreeArray: c only 0.10980498790740967 s
21:56:48.976 💙 INFO ⏰ copyAndFreeArray: swift only 0.11209607124328613 s
21:56:49.090 💙 INFO ⏰ copyAndFreeArray: both 0.11427199840545654 s
```
... i get roughly the same timing even for an _empty_ loop (the first getChatMsgs() is probably slower because of startup, next ones are much faster and nothing is cached)

**Comment by r10s** [comment]
it is waaaayyyyyyy faster when optimizing for speed, which we are not doing for debug mode :)

**Comment by r10s** [comment]
```
22:08:28.842 💙 INFO ⏰ getChatMsgs: 0.17404496669769287 s
22:08:28.842 💙 INFO ⏰ copyAndFreeArray: nix 2.9802322387695312e-06 s
22:08:28.842 💙 INFO ⏰ copyAndFreeArray: c only 6.401538848876953e-05 s
22:08:28.843 💙 INFO ⏰ copyAndFreeArray: swift only 0.0001150369644165039 s
22:08:28.843 💙 INFO ⏰ copyAndFreeArray: both 0.00028896331787109375 s
22:08:35.163 💙 INFO ⏰ getChatMsgs: 0.14992690086364746 s
22:08:35.163 💙 INFO ⏰ copyAndFreeArray: nix 1.9073486328125e-06 s
22:08:35.164 💙 INFO ⏰ copyAndFreeArray: c only 5.996227264404297e-05 s
22:08:35.164 💙 INFO ⏰ copyAndFreeArray: swift only 0.0001150369644165039 s
22:08:35.164 💙 INFO ⏰ copyAndFreeArray: both 0.00017702579498291016 s
```

so, nothing to worry about, the core calls are just fast enough, even 13k are hardly measureable. i still suggest to merge https://github.com/deltachat/deltachat-ios/pull/1419 in and then to enable "optimize for speed" also for debug - if we run into issues for that, we can disable it again, however, it is good that the testing devices are at roughly the same speed as the final releases.

**Comment by cyBerta** [comment]
I think we can close this ticket for now.
