### ISSUE TITLE
add multiselect in Chat List

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1426]
multiselect should include options to:
* pin chats
* archive chats
* delete charts
* select all 

just like on DC Android

**Comment by r10s** [comment]
if the menu gets full, "pin" can probably be left out as this is usually not done in batch for lots of chats.

**Comment by r10s** [comment]
moving issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/1604
