### ISSUE TITLE
qr code title bar is sort of gone

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1432]
with the recent qr code changes that remove the UITableViewController, the title bar, while staying functional is visually a bit lost, esp. in case of scanning a qr code:

<img width=320 src=https://user-images.githubusercontent.com/9800740/146935950-1ea70e16-c441-4f90-b871-437d5e358081.png>

is that on purpose? before we had a white area there, as for the other views.

**Comment by cyBerta** [comment]
I think this is an iOS15 thing. We can force having the old (better) pre iOS15 look though.

**Comment by r10s** [comment]
k, maybe it is okay then, i thought it comes from the recent qr-code-changes.

the black font is better readable if the photo is not black, btw.

**Comment by cyBerta** [comment]
@r10s shall we close this issue?

**Comment by r10s** [comment]
yeah, we can reopen if there come other complains :)
