### ISSUE TITLE
Save to and retrieve secrets from KeyChain

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1434]
It seems like it is possible to store in and retrieve passwords from the iOS keychain without any app specific user authentication. 
This is what we're aiming for our initial prototype in order to store secret keys. 

On app start we'll create query with fixed properties and check if the app KeyItem is stored. If it is available we can pass it to the core. If not we'll generate a random password and write it [to the keychain](https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain).

We need to [adapt the access rules]( https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility) to the keychain. Since we're running in background our default setting should probably be [kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlockthisdeviceonly). The default behavior would allow access to the keychain only if the device is unlocked. 

some useful links:

https://developer.apple.com/documentation/security/keychain_services/keychain_items/using_the_keychain_to_manage_user_secrets
https://www.andyibanez.com/posts/using-ios-keychain-swift/
https://www.andyibanez.com/posts/ios-keychain-touch-id-face-id/

**Comment by r10s** [comment]
this seems to be closed with https://github.com/deltachat/deltachat-ios/pull/1438
