### ISSUE TITLE
show webxdc messages

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1439]
counterpart of https://github.com/deltachat/deltachat-android/pull/2174

* [x] create basic webxdc view, possibly derived from existing WebViewViewController, open that with `/index.html`when tapping on a webxdc message
* [x] intercept requests from webview and get files only via `dc_msg_get_webxdc_blob()`. add a special behaviour for `webxdc.js` that should implement the api as in https://github.com/deltachat/deltachat-android/blob/master/res/raw/webxdc.js (no need to be a separate file, we can use whatever is easy here)
* [x] use core for sending and receiving updates when the corresponding methods are called in `webxdc.js`
* [x] nicer in-chat-presentation with icon and app name - here, wait until that is settled on android
* [x] show app name in title bar

optional (might get into a separate PR)
* allow configuration from staging area (cmp. AttachmentManager, that requires a draft to be set much sooner)

**Comment by Simon-Laux** [comment]
- [ ] deny web requests

**Comment by r10s** [comment]
>  deny web requests

i think, this is included in "intercept requests from webview", however, yes, it's good to have that mentioned implicitly.

**Comment by Simon-Laux** [comment]
> i think, this is included in "intercept requests from webview", however, yes, it's good to have that mentioned explicitly.

It is not, the "interception" is actually creating a handler for a custom scheme, there is no way anymore to intercept web requests on iOS (according to my research of the documentation)

**Comment by Simon-Laux** [comment]
I made webxdc.js work, first I tried escaping the string to pass it to js, but my method only worked sometimes, so after wasting my time trying to figure it out without a js debugger, I just used base64 encoding 😈.

> - [ ] deny web requests

Looking at the code it looks like @cyBerta already implemented it, but it might make sense to run the acid test once we have it, anyways I don't see it as blocker as we did not test it on the other platforms either. So I'll mark this as done for now

**Comment by cyBerta** [comment]
@Simon-Laux you don't need any extra remote debugging tool, it's already working out of the box. I used the approach described here so far: https://stackoverflow.com/questions/6508313/javascript-console-log-in-an-ios-uiwebview
