### ISSUE TITLE
no messages are fetched in background sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1444]
while playing around with https://github.com/deltachat/deltachat-ios/pull/1428 , i am getting pretty stable wakeups every 10 minutes, however, no messages are fetched in these slots (testing on  iphone7 with
ios 15.2.1).

i am pretty sure that worked before, but i cannot say when it broke, eg. if 1.26 is fine or not..

we got similar reports also far before, eg. from @dignifiedquire , but we could not get a grip on that, so that issue may be even older.

cmp. https://github.com/deltachat/deltachat-ios/issues/1157

**Comment by cyBerta** [comment]
We should also double check it's not related to db encryption

**Comment by r10s** [comment]
after little more observing, it seems _sometimes_ messages are fetched in background, but not as often as possible it seems.

as by the new notification-info in the connectivity-view, we know the wakeup is called quite regulary - might be, that it does not finish within the 10 seconds before we leave background.

**Comment by cyBerta** [comment]
this needs to be retested with latest core now, that https://github.com/deltachat/deltachat-core-rust/pull/3041 and https://github.com/deltachat/deltachat-core-rust/pull/3040 has been merged

**Comment by r10s** [comment]
seems, fetching is again available as before, at least on my device.

reconnection still takes longer, roughly double time, i did not measure in details, but that is in sync with measurements at https://github.com/deltachat/deltachat-core-rust/issues/3035#issuecomment-1025616355).

closing this issue as there are more concrete ones for the remaining options, https://github.com/deltachat/deltachat-core-rust/issues/3035 and #1157
