### ISSUE TITLE
info messages look bad on dark mode with image background

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1462]
<img width="580" alt="background" src="https://user-images.githubusercontent.com/18725968/152660240-aef73035-19c2-44d5-abed-b2c4814acabd.png">

**Comment by r10s** [comment]
the font should probably be just white, same as in lite mode. we should just use the same transparency and coloring as on android (that is pretty well tested with all kinds of backgrounds there)
