### ISSUE TITLE
Add code formatting for swift

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1464]
In Xcode you can fix indentation using `control` + `I` after selecting all source code in a file with `cmd` + `A`.

On core we use `cargo fmt` and for desktop we use `prettier`.

I believe we should consider (auto) formatting our swift code too, as having a standard code style makes git diffs smaller.

There are multiple options, some of them are listed at https://nshipster.com/swift-format/
apple is also making a tool: https://github.com/apple/swift-format

There does not seem to be any standard/default option yet, so we can choose.

**Comment by r10s** [comment]
in therory, i think, it is a good idea, if it does not come at additional costs wrt tooling etc (as cargo fmt)

in practise, afaik, we do not have many issues with the current tooling, git diffs are just fine, and also the linter shows some issues in the editor. so, tbh, i would not think much about that unless it is sth. that xcode comes with and is just enabled by a tap.

**Comment by r10s** [comment]
> In Xcode you can fix indentation using control + I 

for now, please do not do so on existing code. indeed, that seems to insert spaces and makes diffs larger (also, not sure of the inserted diffs are "wise", cmp. https://github.com/deltachat/deltachat-ios/pull/1440/commits/084052393384c1c41aeab2f2f2e351ccba64c3df )
