### ISSUE TITLE
improve webxdc tapping

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1466]
i suggest to target this issue once https://github.com/deltachat/deltachat-ios/pull/1440 is merged:

- a tap on a info-message created by a webxdc should move upwards to the webxdc message
- a tap on `WebxdcPreview` should open the `WebxdcViewController` similar to the Start-button (i would open also on tap on title and summary as we may show sth. as "Tap to open" at some point there) (if tapping only icon is easier, that's also fine, however)

**Comment by cyBerta** [comment]
If we allow to tap on the icon and on the title and on the summary as well as on the "start..." label, why don't we just open the `WebxdcViewController` on tap on the whole bubble?

**Comment by r10s** [comment]
yes, maybe that's fine as well, esp. if that is easier.

however, between icon/title/summary and the start-button is also the user-entered text - in comparable situations (images, html-view), this is not tapable as well.

**Comment by cyBerta** [comment]
I forgot about the additional text. My proposal would be to allow tapping on the image and on the start label as long as we don't change the summary text.
