### ISSUE TITLE
sendUpdate() without summary pops up in chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1467]
updates without summaries should not be visible in the chat, however, they're shown on the sending device until the chat is re-entered.

**Comment by cyBerta** [comment]
@r10s We receive both DC_EVENT_MSGS_CHANGED and DC_EVENT_MSG_DELIVERED. I'm not sure if that is really what we want, if we don't track the sent state for webxdc updates in the UI. 
I can filter those updates out, but I think  it should considered to adapt the core actually.

**Comment by cyBerta** [comment]
> updates without summaries should not be visible in the chat

@r10s do we want any outgoing webxdc info messages?

**Comment by r10s** [comment]
> @r10s do we want any outgoing webxdc info messages?
 
yes. the chat one sender and receiver side should have the same information. 
the core adds the info messages as needed - however, not every sendUpdate() results in an info-message.
