### ISSUE TITLE
Delta Chat doesn't start after migration from phone to phone

### ISSUE THREAD

**Issue by michaelherger** [deltachat/deltachat-ios#1471]
- Device: iPhone 13 Mini
- iOS version: 15.3
- Delta Chat version: 1.28.1 (and before
- Expected behavior: starts
- Actual behavior: shows start screen for a split second, then disappears
- Steps to reproduce the problem: try to start the app
- Screenshots: 

https://user-images.githubusercontent.com/2789989/153177702-4f85f5e6-8ed4-4a90-a6e4-27b9e537dad0.MP4

The app worked on my old iPhone 7. I then installed the new phone using the old phone. All apps and settings etc. were "migrated" from the old to the new phone. Ever since I haven't been able to start the app on the new phone. Even with the version before the recent update to 1.28.1.

**Comment by r10s** [comment]
can you say if you deinstall the app and reinstall it from scratch - does it work then?

iirc, there were some issues with ios backup and migration.

**Comment by michaelherger** [comment]
Yep, that worked. I obviously tried to avoid the re-installation (and re-configuration). But it worked. Thanks!
