### ISSUE TITLE
double webxdc info messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1476]
if a webxdc sends a status update containing an info-message, in the sending device, that messages is shown tince in the chat.

when the chat is left and re-entered, only one message is shown.

this is reproducible, eg. when doing a new triska highscore (take care, each test gets harder ;)

nb: iirc, there was a similar issue where a status update was shown on the sending device that should not appear at all (after re-entering, it is gone), i did not checked that part in detail.

**Comment by cyBerta** [comment]
related to https://github.com/deltachat/deltachat-ios/issues/1467

**Comment by cyBerta** [comment]
That isn't the case anymore I think. @r10s did you see double outgoing status updates with the latest core on the current master branch?

**Comment by r10s** [comment]
not recently iirc - but there is an [update missing now](https://github.com/deltachat/deltachat-ios/issues/1519), so sth. seems to be wrong :)
