### ISSUE TITLE
Update testflight Link and QR code

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#148]
https://support.delta.chat/t/stable-ios-version/251/10
The previous one expired.

- [x] Update Testflight link
- [x] Update Testflight qr code

https://testflight.apple.com/join/uEMc1NxS

**Comment by Simon-Laux** [comment]
I just updated the one on the website

**Comment by OzancanKaratas** [comment]
Why is this required?

**Comment by Simon-Laux** [comment]
because the old testflight expired and there will be no updated version on the old one, because we have a new apple developer account now.

**Comment by OzancanKaratas** [comment]
Hmmm, I want to remove the beta tag in the app. Can you add me into team? Because the beta tag is unnecessary. iOS already displays beta beside beta apps.

**Comment by cyBerta** [comment]
> I just updated the one on the website

@Simon-Laux so what is necessary here now? 
the link here https://delta.chat/de/download still points to https://testflight.apple.com/join/uEMc1NxS
Is the website-update just not deployed yet? 
I'm still trying to figure out how to generate those invites on testflight. Did you do that before?

**Comment by Simon-Laux** [comment]
@cyBerta the current one in the readme doesn't work: https://testflight.apple.com/join/WVoYFOZe
> I'm still trying to figure out how to generate those invites on testflight. Did you do that before?

yes I did, but this one(https://testflight.apple.com/join/uEMc1NxS) comes from @r10s

**Comment by r10s** [comment]
i updated the readme in this repo.
