### ISSUE TITLE
show .xdc in profile / files

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1484]
for now, just adding DC_MSG_WEBXDC to the filter should be good enough, that way, one can easily find the .xdc and use "Show in chat" to do actions on it.

at some later point, we will probably tweak the view, but that is sth. for the next iteration when most other things are settled.

**Comment by cyBerta** [comment]
Do we want to disable the gallery view that normally opens if you tap on a file? Instead we could directly open the WebxdcViewController (the webview).

**Comment by r10s** [comment]
> Do we want to disable the gallery view that normally opens if you tap on a file? Instead we could directly open the WebxdcViewController (the webview).

let's decide that at a later point, i think for now, it is super-helpful that the files are shown, even if you have to go to the chat to use it. but you will also have a better experience there, as eg. summary is not yet shown in the gallery, so, i think we should merge #1484 in and go forward.

next iteration will  improve gallery view of webxdc, maybe with direct opening then.
