### ISSUE TITLE
remove superfluous call to dc_get_chatlist()

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1499]
on app start, there are two calls to `dc_get_chatlist()`:

- one in `ChatListViewModel::init()` -> `ChatListViewModel::updateChatList()` [1]

- one in `ChatListController::viewDidLoad()` -> `ChatListViewModel::refreshData()` -> `ChatListViewModel::updateChatList()` [1]

as this seems to significantly slow down startup, we treat that as a bug.

nb: these two calls are blocking the main thread, subsequent updates are scheduled to background using  
`ChatListController::refreshInBg()` -> `ChatListViewModel::refreshData()` ->   `ChatListViewModel::updateChatList()` [1] -
maybe we can also do the initialisation non-blocking. but at least one call should go away.

---

[1] `ChatListViewModel::updateChatlist()` then calls    `DcContext::getChatlist()` -> `dc_get_chatlist()` in a blocking way

**Comment by cyBerta** [comment]
the second call to `refreshInBg()` comes from `applicationDidBecomeActive(_ notification: NSNotification)`. It is called whenever the app gets to foreground. I would like to avoid tweaking that method for the initialization case, also because it is not blocking the UI.
