### ISSUE TITLE
Autodetection of mailserver fails for testrun.org addresses.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#150]

**Comment by hpk42** [comment]
could you provide the log lines?

**Comment by Simon-Laux** [comment]
I don't have the log anymore, but it tried `imap.testrun.org` which probably indicates that it doesn't do the automatic stuff to find out what the server is like it does on the other platforms.

**Comment by Simon-Laux** [comment]
After removing the app from the device and reinstalling autoconfig worked as expected... strange

**Comment by Simon-Laux** [comment]
Also the info I forgot:
delta-iOS `master f99eb49999e4efb45852d3fec5e047e620ef1736`
dcc-rs `master 11eb86c77fd7c0cffa8ca466fcec975141683adf`
