### ISSUE TITLE
Chat-background-selection is not intuitive

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1502]
The selection crops out a square while the chat background area is a high rectangle.
This makes it impossible for users to select what exact section of an image they want to select.

![image_2022-03-19_12-30-42](https://user-images.githubusercontent.com/18725968/159128093-18d5a2ea-4413-4ffd-aed1-51b9753ef8a4.png)

**Comment by r10s** [comment]
> while the chat background area is a high rectangle.

this is not always true, there is also landscape. cropping out a rectangle is a not-so-bad and simple solution therefore.

maybe things can be done differently and maybe even better, however, the current behavior is on-purpose and no bug; esp. when it comes to making things more "advanced", that will introduce all kind of bugs, we had that on android.

closing this issue fir now, when everything else is fine, we can iterate over it.

**Comment by Simon-Laux** [comment]
ipad is not something we target, If we would do so we would have a special layout for ipad that would always show the chatlist in landscape mode similar to desktop.

**Comment by r10s** [comment]
> ipad is not something we target

we allow installations on ipads. sure, a combined layout would be nice, and sooner or later we will probably go for that. but not having that is no blocker to use an ipad with delta chat. small ipads are not much bigger than large phones :)

however, for the issue, even if we leave out ipads, also iphones have a landscape mode.

**Comment by Simon-Laux** [comment]
landscape mode on phones is not something we need to respect here, it would be better to have portrait background work perfectly and landscape being a bit ugly, than having both modes be halfway good/bad IMO.

**Comment by r10s** [comment]
> When do users really use landscape mode? on a phone in an chatapp

this is not so rare, esp. quick rotation to get another overview. also, on ipad, things would not be portrait, even with a fixed layout as on desktop.
