### ISSUE TITLE
webxdc status messages not shown immediately in chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1519]
the chat is not updated when a webxdc status message is generated on the same device.

once the chat is left and re-entered, the status message is shown.

**Comment by r10s** [comment]
cmp https://github.com/deltachat/deltachat-ios/pull/1518 wrt missing updates, maybe this is the same issue.

**Comment by cyBerta** [comment]
It's related to https://github.com/deltachat/deltachat-ios/issues/1467 and https://github.com/deltachat/deltachat-ios/pull/1482

We need to improve the check when we want to show outgoing webxdc uodates and when not.
