### ISSUE TITLE
string truncated in login screen

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#152]
if the advanced "show" button contains more than a few characters in localized versions, the text is truncated.
i suggest to right-align the text.

<img width="538" alt="Screen Shot 2019-07-29 at 23 44 19" src="https://user-images.githubusercontent.com/9800740/62085093-0b212380-b25b-11e9-8800-5f9d1da856de.png">

**Comment by nayooti** [comment]
I’ll take care of this.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>

________________________________
Von: björn petersen <notifications@github.com>
Gesendet: Montag, Juli 29, 2019 11:47 PM
An: deltachat/deltachat-ios
Cc: Subscribed
Betreff: [deltachat/deltachat-ios] string truncated in login screen (#152)


if the advanced "show" button contains more than a few characters in localized versions, the text is truncated.
i suggest to right-align the text.

[Screen Shot 2019-07-29 at 23 44 19]<https://user-images.githubusercontent.com/9800740/62085093-0b212380-b25b-11e9-8800-5f9d1da856de.png>
