### ISSUE TITLE
share-to-delta not always working on iphone13

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1521]
share-to-delta is not always working on iphone13.

while sharing text seems to work, sharing an image from the gallery fails - the "share to" dialog is shown shortly and is terminated after half a second or so then.

not sure if that is only related to iphone13, however, i noticed the bug there - while iphone7 works.

**Comment by cyBerta** [comment]
on the iphone13, does the bug occour always with the same image, or does sharing work randomly with the exact same image?   did you test on the iPhone7 with the same image? 
What I would like to figure out if this bug is related to the image size, we had issues/restrictions wrt that in the past.

**Comment by r10s** [comment]
it happens always, i cannot share _any_ image on iphone13. did not test, however, if sharing the same image works on iphone7.

> What I would like to figure out if this bug is related to the image size, we had issues/restrictions wrt that in the past.

i will try to check that out. however, sending the same image by select-from-gallery works, so there is no direct hint that image size is an issue here.

**Comment by cyBerta** [comment]
>  however, sending the same image by select-from-gallery works, so there is no direct hint that image size is an issue here.

when sending photos from within the app we're not running into this app-extension RAM restriction issue, which we discussed here: https://github.com/deltachat/deltachat-ios/issues/1330#issuecomment-917405117 

it might be that the iphone 13 has a better camera and therefore images have a bigger image size.

**Comment by cyBerta** [comment]
> it happens always, i cannot share _any_ image on iphone13.

Hm, not only photos but any jpeg/png, also downloaded ones?  That would speak against the image size theory...

**Comment by r10s** [comment]
i can share screenshots, so, may be related to image size - but probably not relate to core as the share activity quits immediately - i assume, there is not much core envolved at that point. but maybe the generation of the thumbnail fails.
