### ISSUE TITLE
memoji-picker not working on iphone13

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1522]
the memoji- (and sticker-) picker-keyboard is not shown in Delta Chat on iphone13 - where it is visible on other apps on iphone13 and on Delta Chat eg. on iphone7.

not sure if that is only related to iphone13, however, i noticed the bug there.

probably not the most important bug, however, sth. seems to be wrong here so it is worth checking as it may also affect other sections.

**Comment by cyBerta** [comment]
btw. @r10s did you resolve this issue on your phone? Or does it still exist?

**Comment by r10s** [comment]
at least currently, the memoji-picker is there :)
