### ISSUE TITLE
Delta Chat pasted from …

### ISSUE THREAD

**Issue by snan** [deltachat/deltachat-ios#1528]
If I have something in my clipboard from any other app, even if it's just text from Safari or Notes, but also any other kind of data, I get these messages constantly as soon as I enter Delta Chat. Several in a row until the originating app swaps out.

![Screenshot 2022-04-10 at 08 17 47](https://user-images.githubusercontent.com/309417/162605248-9221273d-4f36-4714-8b23-8b9a698c86bc.png)

It comes across as if Delta Chat were snooping on the clip board + it's annoying + it's wasteful (in this case it's a 3d scene with tons of polygons and rigs and angles).

**Comment by cyBerta** [comment]
@snan I cannot reprocudce that behavior. Also I'm not sure where this text comes from. It's not part of our sources. 
These 'Toasts' look almost like Android UI, it's weird. 
I tried it with an iOS 15.4, iPhone7  

Can you give more details about iOS version, device and maybe you have another app in mind that might interfere (e.g. a clipboard app)?

**Comment by snan** [comment]
This is on iPad OS 15.5!

**Comment by snan** [comment]
On iPad OS 16.1, the problem is both better and much worse.

Because on this version, at least with lockdown mode on, it asks to confirm each paste. This means that using Delta Chat with something in the pastebuffer pops up a ton of such questions. (The workaroudn is to copy something from inside Delta Chat itself.)

**Comment by r10s** [comment]
> Because on this version, at least with lockdown mode on, it asks to confirm each paste

so, if "lockdown mode" is turned off, the message is not shown?

i just tried "lockdown mode" with an iphone13 and ios 16.1.2 and things look good to me, we are still lacking a way to reproduce this (i currently have no ipad at hand :)

so, might be related to ipad+lockdown mode only, maybe this is even regarded as a feature from apple?

**Comment by snan** [comment]
I'm still getting it and I was getting it before I applied lockdown mode too.

Only difference is that it used to be "Delta Chat pasted from Safari" and now there's a dialog where I can deny it (although that dialog keeps popping up).

**Comment by r10s** [comment]
k, so we have to check if that happens on ipad only.

**Comment by snan** [comment]
Maybe went away on 16.2? 🤷🏻‍♀️

**Comment by r10s** [comment]
> Maybe went away on 16.2? 🤷🏻‍♀️

i was testing using 16.1.2 :)

**Comment by snan** [comment]
Yes, and I could reproduce on 16.1.2
