### ISSUE TITLE
add searchbar to chatlist

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#154]
* reuse implementation in contacts view

**Comment by nayooti** [comment]
What exactly should be searched through?

**Comment by cyBerta** [comment]
it should search through all messages over all chats and through all contacts using the DC core API

**Comment by cyBerta** [comment]
by reuse I don't mean the search implementation itself but the way the UI is built.

**Comment by nayooti** [comment]
the search UI in contacts etc. is native and is about two lines of code.

**Comment by r10s** [comment]
as a first iteration, i think it is fine to search only over the chatnames, i think this is pretty easy and can be done by a simple filtering of the exiting items (similar to the contact list)

**Comment by nayooti** [comment]
there is a pending PR on this.

**Comment by r10s** [comment]
closed in https://github.com/deltachat/deltachat-ios/pull/577, there are subsequent issues with minor things to do, #578, #579
