### ISSUE TITLE
empty enum argument violation

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1540]
i have no idea what these warnings wants to say to me:

WelcomeViewController.swift:

<img width=99% src=https://user-images.githubusercontent.com/9800740/163420650-5dfb275f-15db-407c-8558-932a0a616045.png>

AppDelegate.swift:

<img width=99% src=https://user-images.githubusercontent.com/9800740/163420979-fd0234df-ad27-4dc9-8e81-a77cad119473.png>

these are just two examples, there are more corresponding warnings.

imu, the functions have just no arguments. is this a false positive of the linter?

**Comment by cyBerta** [comment]
I also stumbled over these lint warnings and I'm actually a little bit confused by them, these methdos are obviously not enums. I ignored them so far :P

**Comment by r10s** [comment]
maybe then, we should switch off the warning `empty_enum_arguments`.
