### ISSUE TITLE
Crash on Startup after using iOS-build-in method to setup new device

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#1541]
This happens on every startup atm 

<img width="1549" alt="Screen Shot 2022-04-14 at 20 00 03" src="https://user-images.githubusercontent.com/790842/163450018-204f1b8d-ce8b-4cdf-b624-41b86eccb227.png">

**Comment by r10s** [comment]
some debug ideas:

1. a few lines above, we iterate over `dcAccounts.getAll()` - is it already empty there?
2. if so, is the secret retrieved from `KeychainManager` 
3. i assume, the account is not encrypted? (just an upgrade, no export -> import-encrypted involved?)
4. maybe the log shows what is going on in core?
5. finally, can the database be opened in the repl tool or in dc40/dreamer as suggested by @Simon-Laux ? however, not sure how this is easily doable, [_Xcode / Window / Devices and Simulators / Installed Apps / Delta Chat / ... / Download container_](https://stackoverflow.com/questions/6121613/browse-the-files-created-on-a-device-by-the-ios-application-im-developing-on-w) does not extract the "shared data" we are using to make the share extension possible.

however, maybe 5. is not needed, 1.-4. may already give some hints. also, the list is probably not complete, i am sure there are good debug ideas i've overseen.

**Comment by dignifiedquire** [comment]
yes to 1
no encryption, this db was last used before that was a thing

**Comment by cyBerta** [comment]
@dignifiedquire did you import your database? I vaguely remember you said you uninstalled the app in between? I'm asking because if it is an backup, it might help to reproduce/debug the issue outside of ios. 

What puzzles me is that dcAccounts.add() fails even. That might be a corrupted db.

**Comment by dignifiedquire** [comment]
I did not import in the dc sense, I copied over my whole storage, through iOS, as I switched phones

**Comment by cyBerta** [comment]
If you're in debugging mood: could you try to create a breakpoint just before the fatalError is shown and enter in the lldb debug console

`po FileManager.default.contentsOfDirectory(at: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.chat.delta.ios")!.appendingPathComponent("accounts"), includingPropertiesForKeys: nil)`

it should show you the accounts folders, like:

```
▿ 3 elements
  ▿ 0 : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/59b8cd0277c4430896525c3430d020b0/
    - _url : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/59b8cd0277c4430896525c3430d020b0/
  ▿ 1 : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/24c20f2c30ae47c59d28135e79d6sba0/
    - _url : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/24c20f2c30ae47c59d28135e79d6sba0/
  ▿ 2 : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/accounts.toml
    - _url : file:///private/var/mobile/Containers/Shared/AppGroup/F8F247E7-8465-4389-A280-88D24C2976BF/accounts/accounts.toml
```

could you then please enter 
`po FileManager.default.copyItem(at: FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.chat.delta.ios")!.appendingPathComponent("accounts"), to: FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false).appendingPathComponent("group.chat.delta.ios").appendingPathComponent("accounts"))`

that should copy all account data into the document directory. You can then export the database and we're a step further in debugging.

**Comment by cyBerta** [comment]
@r10s mentioned we should try to reproduce that update path described by @dignifiedquire 
I can try next week, although I would feel more comfortable if I could use  two testing devices instead of one testing device + one daily driver.

**Comment by dignifiedquire** [comment]
xcode is currently not willing to start debug mode anymore on my iphone -.-

**Comment by r10s** [comment]
this is tracked more on-point at https://github.com/deltachat/deltachat-ios/issues/1762 now.
