### ISSUE TITLE
Implement settings bundle

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#156]
In iOS, apps allows to change its own settings outside the app. Can be implement a settings bundle in Delta Chat? For example, this bundle usage may be provide changing the theme and display settings.

Refer the related [Apple Developer page](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html).

**Comment by r10s** [comment]
i think, this is a good idea. however, it would require to open an ViewController or so we provide eg. to unblock contacts.

**Comment by r10s** [comment]
closing this for now, we can re-open it as needed. feature requests should be discussed in the forum at https://support.delta.chat , there is also a broader audience. this issue tracker is more for bugs and for tracking things people are actually working on.
