### ISSUE TITLE
revamp welcome screen

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1563]
- [x] revamp welcome screen similar to https://github.com/deltachat/deltachat-android/pull/2284 , however, keep ios button styles as is (so blue background for primary, blue text without border for secondary)

- [ ] if easily doable, move "restore from backup" to the welcome-screen (it is currently hidden inside "log in") (if that is too complicated, we should do that after 1.30)

**Comment by cyBerta** [comment]
Shouldn't we postpone any new features and bigger UI changes until we release 1.30 ?
However I can already start working on it.

**Comment by r10s** [comment]
> Shouldn't we postpone any new features and bigger UI changes until we release 1.30 ?

maybe do one pr changing the image and removing the subtitle, that can probably go in already to 1.30.

the move of "restore from backup" to the welcome screen can go into another pr.

**Comment by r10s** [comment]
> if easily doable, move "restore from backup" to the welcome-screen (it is currently hidden inside "log in") (if that is too complicated, we should do that after 1.30)

this is targeted in https://github.com/deltachat/deltachat-ios/pull/1577
