### ISSUE TITLE
Chat room not updated after sharing activity

### ISSUE THREAD

**Issue by adan89lion** [deltachat/deltachat-ios#1564]
**Bug description**
When a chat room is opened, switching to other apps' share their content to said chat room, and switch back to Delta Chat, will not appear the shared content.

**Steps to reproduce**
1. Open a chat room in Delta Chat
2. Go to Safari and open a website
3. Share the webpage to the chat room via Share Sheets
4. Go back to Delta Chat, the shared webpage isn't there yet
5. Swipe back to the conversation list and reopen the chat room, and the shared webpage is finally there

**What went wrong**
The chat room isn't immediately refreshed when the app is active again (after coming back from the multitasking menu)

**What is the expected behaviour**
The app should refresh the chat room after the app is active again, to reflect the latest message and to avoid confusion (users like me might think the content isn't shared, so will try to send again)

**Comment by r10s** [comment]
this should be fixed in the next version (coming soon!), see https://github.com/deltachat/deltachat-ios/issues/1513

**Comment by cyBerta** [comment]
closing for now, because #1513 was merged
