### ISSUE TITLE
pulling translations wipes dutch strings

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#157]
see https://github.com/deltachat/deltachat-ios/pull/146

**Comment by r10s** [comment]
@cyBerta i finally found the problem: 
- in transifex, there were the languages (1) `nl_NL` as well as just (2) `nl`
- in tools/.tx/config we map `nl_NL` to `nl` - so we have two sources writing to one directory
- as (2) was empty and unused on transifex, it wipes all data already converted when processing (1)

as a fix, i just removed `nl` on transifex.

in general, it seems better to use `nl` instead of `nl_NL`, however, i fear transifex does not support such a move very well (would require to re-assign translations and translators etc.). also, it might be that `nl_NL` was choosen by some intention. so, for now, this seems just nice.

**Comment by cyBerta** [comment]
nice! Makes totally sense :D, sometimes it's hard to see the obvious.
