### ISSUE TITLE
chatlist not always updated after sharing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1591]
while the chatlist is updated when eg. sharing from gallery -> delta chat, the update is missing when sharing from delta chat -> delta chat.

example:

- go to profile / files of a chat with some webxdc
- long tap a webxdc, select "share to" and share to some other chat

-> the chatlist is not updated.

this may also be buggy for sharing files or other things this way, i tested only for webxdc.

EDIT: also, the message-list is not updated when sharing to the same chat.

**Comment by cyBerta** [comment]
@r10s events like `DC_EVENT_MSGS_CHANGED` are not emitted when sharing from DC to DC. I guess because they are sent from the extension app, which is a different context. 

 A robust solution would be to reintroduce `refreshInBg()` in onViewDidAppear

**Comment by r10s** [comment]
> A robust solution would be to reintroduce refreshInBg() in onViewDidAppear

well, but also an expensive one :) and one with not-so-nice ux as the user will see the old state flashing up.

better we look out for why the update is missing in exactly that case (in other cases, things work as expected)

**Comment by r10s** [comment]
> But maybe the core's dc_send_msg_sync does't emit the event.

i think, this would not even help as we need to update the other instance. 

for other cases, this works by setting the flag `UserDefaults.hasExtensionAttemptedToSend` in the share activity and check the flag from the main activity. we are doing this in `applicationWillEnterForeground()` - probably _this_ is the issue as the main app _is_ already in foreground.
