### ISSUE TITLE
Overly lingering badges

### ISSUE THREAD

**Issue by snan** [deltachat/deltachat-ios#1601]
Sometimes the badge number in the icon shows up when that chat is open and the number doesn't go away until later when a new message arrives or I restart. This started recently.

**Comment by snan** [comment]
It doesn't go away when restarting the app nor when resåbooting the tablet

**Comment by snan** [comment]
It could also be an OS level bug, i.e. on Apple's end🤷🏻‍♀️

**Comment by cyBerta** [comment]
@snan is this still an issue you're experiencing?
