### ISSUE TITLE
implement message resent

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1607]
cmp. Android https://github.com/deltachat/deltachat-android/pull/2278

only for sent messages for now

- cancel button to the top left, EDIT: done
- title: x selected, EDIT: done
- bottom resend

**Comment by r10s** [comment]
one idea was to hide that behind the "More" button - that way, also multi-select would be possible.

(the message menu also lacks "Reply Privately", so with two more items, this would become more confusing)

**Comment by cyBerta** [comment]
partly implemented in https://github.com/deltachat/deltachat-ios/pull/1659 and https://github.com/deltachat/deltachat-ios/pull/1663
