### ISSUE TITLE
Improve Message Info screen

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#162]
Not super useful yet. Also unencrypted messages in verified groups can't be viewed using it.

**Comment by r10s** [comment]
i think we should just display the multi-line string from [dc_get_msg_info()](https://c.delta.chat/classdc__context__t.html#a9752923b64ca8288045e999a11ccf7f4. it's not super-nice yet, but it shows many information and is very easy to implement.
