### ISSUE TITLE
speed regression in pin/archive/delete chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1621]
on swipe-left-chat in chatlist to pin/archive/delete, these action were done nearly instantly in the past, eg. at 82a8b2ca9ce01ad1709967df47532a5475a14a01 .

current master with multi-select (see #1604, #1613, #1618, #1619) is way slower, there is a delay of nearly a second, maybe because some animation is played, not sure.

for testing, compare eg. `git checkout 82a8b2ca9ce01ad1709967df47532a5475a14a01` with `git checkout master`.

**Comment by r10s** [comment]
maybe related somehow: https://github.com/deltachat/deltachat-ios/issues/880 , esp. the hint to swipe-to-info which is much faster.

**Comment by cyBerta** [comment]
If this delay is unacceptable, we need to find another hook for when we check for pending list updates.

**Comment by r10s** [comment]
it is not super-urgent, but we should fine a way to make this nicer. it feels very slow this way.

**Comment by r10s** [comment]
ftr: this has also fixed https://github.com/deltachat/deltachat-ios/issues/880
