### ISSUE TITLE
"Lock" and "√" icons appear blurry in message list

### ISSUE THREAD

**Issue by troilus** [deltachat/deltachat-ios#1646]
- Device:
- iOS version:
- Delta Chat version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by r10s** [comment]
the icons want to stay incognito :)

but yes, this is a longer standing issue ... fixing it was always superseeded by more important things :)

**Comment by Simon-Laux** [comment]
also sending/pending icon is different to the other platforms and lacks the animation. maybe that is easy enough to fix at the same time.

**Comment by Simon-Laux** [comment]
maybe we could use vector icons instead?

**Comment by r10s** [comment]
nb: it is okay in the chatlist, it is blurry only on the message list.

**Comment by r10s** [comment]
the issue probably is the NSTextAttachment, cmp https://stackoverflow.com/questions/27281945/blurry-image-nstextattachment-on-nsattributedstring , svg does not help (tested with SFSymbol images)

we should either not use NSTextAttachment or apply a fix as described on stackoverflow.com above

**Comment by Simon-Laux** [comment]
Only for the padlock icon though in my tests, the other icons were fixable without using svg in #1921

**Comment by r10s** [comment]
maybe #1921 is indeed good enough, i will have a closer look when 1.42 is out and resurrect as needed.

maybe a horizontal stackview is the prober solution, this NSTextAttachment is blurry even for svg of #1921 (although already far better)

<img width=480  src=https://github.com/deltachat/deltachat-ios/assets/9800740/6533ef47-a543-4589-a7a6-9ae2845b93ba>

_the svg are not that share as they could be; still an improvement, though_
