### ISSUE TITLE
wrong question displayed on qr-group-join

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#166]
qr group-joining works like a charme, however, the initial question should read "do you want to join group $groupname" and not "do you want to chat with $person"

**Comment by cyBerta** [comment]
@r10s group join is not intendedly implemented as such yet. It's rather a side effect :).

I created a ticket to generate a qr code for iOS initiated group joining https://github.com/deltachat/deltachat-ios/issues/239 additionaly to this ticket

**Comment by r10s** [comment]
> @r10s group join is not intendedly implemented as such yet. It's rather a side effect :). 

i think group _joining via qr_ (scanning a qr-code from android) already works - of course, the code has to be shown eg. by android.

#239 is needed anyway, however, is this about _inviting via qr_, but i think this is probably what you're meaning :)

**Comment by r10s** [comment]
to be clearer: for both, contact-join and group-join, the same qr-scan-view-controller is used. it depends on the qr-code then, whether a group-join or a contact-join is done. 

technically, it is the same call to the core. but the initial question is just wrong.
