### ISSUE TITLE
webxdc app selector

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1661]
Similar to a sticker selector, we want to have a simple UI to select and paste webxdc's into a chat. 

UI wise we will use a grid layout similarly to the current image selector on iOS. Each grid tile should show the app icon and the application name, the entries in the grid should be sorted by timestamp. 

Changes in core are needed so that 0 for the chat ID can be passed to [dc_get_chat_media](https://c.delta.chat/classdc__context__t.html#a344a82b9f288b5eb5d39c7cf475cddb7). The returned array should contain all messages of a given account containing the requested message type. The corresponding core ticket: https://github.com/deltachat/deltachat-core-rust/issues/3527

Tapping on a grid tile should add the selected webxdc to the draft area, so that it can be edited before it is sent.

**Comment by r10s** [comment]
great stuff!
