### ISSUE TITLE
sticker selector

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1662]
As a follow-up for #1661, we can reuse much of the logic and UI to implement a sticker selector. 

For now we will add another entry to the clipper icon menu. Tapping on the entry will open a ViewController with a grid, similarly to the current image selector or gallery view.

For the beginning only images from messages with the message type `DC_MSG_STICKER` should appear in the grid. 

Tapping on a grid tile should send the sticker immediately, instead of adding it to the draft area.

**Comment by Simon-Laux** [comment]
does that mean we can paste images without them getting converted to stickers eventually?

**Comment by r10s** [comment]
the sticker selector is not about the paste behavior which was introduced to support stickers from the system keyboard. doing that right seemed to be a larger impact that time, however, of course, maybe this can be improved as well and stickers can be detected more on point, but this is another thing.
