### ISSUE TITLE
Sharing contact from contacts app does not show deltachat in the options

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1667]
What works:
- Contacts app -> click on a contact -> share -> save in files -> share resulting vcf file from files app -> shows deltachat in options (BTW deltachat iOS already has a nice preview for vcf files by default, which surprised me)

What does not work:
- Contacts app -> click on a contact -> share -> deltachat is not part of the options

Why is this important:
When I use delta chat as daily driver chat app I need to be able to easily share contacts with friends.
I'm not talking about telegram like contact sharing where one can select what fields exactly to share of that contact, just that I can share from contacts app to deltachat.

**Comment by cyBerta** [comment]
https://developer.apple.com/forums/thread/27383

**Comment by Simon-Laux** [comment]
Adding this line makes it work to share contacts.
```
ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.vcard"
```

BUT there is a potential privacy/press problem of not telling users that this shares the entirety of the contact.
Telegram, signal and even WhatsApp let you select fields you want to share before sharing.
Also their share screens fill the whole screen and don't feel cramped.

Telegram:
<img  height="250px" alt="Telegram" src="https://user-images.githubusercontent.com/18725968/184508445-a8766acd-f431-445d-a490-496fe0ce4084.png" />

Whatsapp:
<img  height="250px" alt="" src="https://user-images.githubusercontent.com/18725968/184508446-e9d445cf-f2f5-4a36-82f9-c9a20b6dd57e.png" />

Signal:
<img  height="250px" alt="" src="https://user-images.githubusercontent.com/18725968/184508654-78f01c18-c315-4658-bbab-58c2fa040b97.png" />


Flow is the same for all 3 mainstream examples above:
1. select chat to send to
2. deselect fields you don't want to send

**Comment by cyBerta** [comment]
That's probably quite some work. It's a nice to have feature, but I will depriotize the whole contact sharing a little bit, it's not  our focus right now. But let's keep this ticket open for later.

**Comment by cyBerta** [comment]
You probably know that, but for anybody else stumbling over this ticket. If you want currently to share a part of a contact by long-tapping e.g. on the phone number or email-address and selecting copy. Afterwards paste it into the message input view of your chat. 
For sharing the complete contact you can tap on share contact -> save in files, open delta chat and the according chat, tap the clip icon, attach file, select the vcf file.
