### ISSUE TITLE
Share dialog glitches/looks wrong when running under macOS

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1670]
<img width="385" alt="Bildschirmfoto 2022-08-13 um 20 45 44" src="https://user-images.githubusercontent.com/18725968/184507033-4c636355-8132-4817-ac94-35789c8be667.png">

- Dialog is too small (height is too small), "forward to" selector is cut out of view.
- transparency is too heigh
- strange visual artefacts in corners

you can scroll down a bit thanks to the bouncing scrolling, but it bounces right back, before I have a chance to click it:

https://user-images.githubusercontent.com/18725968/184507375-d279621c-8728-453d-bf96-703ce915601c.mov

**Comment by cyBerta** [comment]
the app was never ment to run on mac. We should decide that we want and need to support that first of all.

**Comment by r10s** [comment]
on macos we have deltachat-desktop, it is nice to try out the ios app on macos, however, for now, we should not put many resources in polishing that.

how can the normal user install the ios app for macos? if possible and not yet done, we should restrict the app for ios+ipad.

so, is suggest to close this issue and open one for denying ios from macos, if needed.

**Comment by Simon-Laux** [comment]
> how can the normal user install the ios app for macos? if possible and not yet done, we should restrict the app for ios+ipad.

appstore, yeah we could possible restrict it, though the app already mostly works there are just a few edgecases where such bugs appear (like the share extension, which still needs work on iOS too anyway so maybe this problem automatically disappears when we change the share extension design on ios (also it's probably just some layout/constraint thing)).

**Comment by r10s** [comment]
if it is just some minor things, well, maybe. the share-extentsion [is not really nice anyway](https://github.com/deltachat/deltachat-ios/issues/722) [^1] , so needs some revamp at some point anyway - ideally, when this is improved, we should also test it on macox :)

however, please also note, that currently the main ios devs do not have m1+ machines so, afaik,  cannot really try out ios on macos.

@Simon-Laux but on point to the question: does the "macos app store" offer Delta Chat ios on m1?

[^1]: as that popped up off-topic: for closed issues that are not really bugs and might be targeted at some point, we have [resurrection](https://github.com/orgs/deltachat/projects/19) - and it is not (only) an issue graveyard issues actually pop up from there. of course, not perfect, but it seems good enough and is well known in the team.

**Comment by Simon-Laux** [comment]
> @Simon-Laux but on point to the https://github.com/deltachat/deltachat-ios/issues/1670#issuecomment-1214926886: does the "macos app store" offer Delta Chat ios on m1?

yes but as I pointed out above the app mostly already works so we could also keep it until it makes problems.

**Comment by r10s** [comment]
also, an chat-list or message-list update is missing when using "share to" on macOS; the shared content is not directly visible, you have to re-open chat-list or message-list (on iPhone, usually, share-extension and app are not visible at the same time - otherwise, we'd probably have the same issue there.

**Comment by r10s** [comment]
k, i disabled the availability for the iphone app for apple silicone;  M1/M2/M3 macs are fast enough to run the electron desktop, wrt support it is easier to have just one desktop app



![Screenshot 2023-11-24 at 00 39 40](https://github.com/deltachat/deltachat-ios/assets/9800740/a4ea74d9-1b44-4daa-a7a1-22847da81273)


at some point, we can decide whether to make the app nice & available for desktop, but currently this is a non-goal to save costs
