### ISSUE TITLE
(Drag and) Drop support

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1671]
Mainly drag files into the composer, a bit like what desktop has.

For iPhone this helps when I make a screenshot it hovers in the side and I expect to be able to drop it into the composer to send it directly (or better put it into the draft of course). (also you can switch apps which dragging an image/file, which I just found out)

For iPad this is useful when multitasking like files or gallery app one one side and deltachat on the other side.

For running the iOS app on macOS this makes the app more complete and intuitive to use.

https://developer.apple.com/design/human-interface-guidelines/patterns/drag-and-drop
https://developer.apple.com/documentation/uikit/drag_and_drop

**Comment by r10s** [comment]
> For iPhone this helps when I make a screenshot it hovers in the side and I expect to be able to drop it into the composer to send it directly

do you know of an app where this works? i did not manage to drag'n'drop a screenshot that way to some other app.

for ipad, this is probably useful, macos os no goal currently, see https://github.com/deltachat/deltachat-ios/issues/1670#issuecomment-1214437428

so, all in all, first step seems to be to check out if it is simple to do. if not, we should spend the development resources to something else.

**Comment by Simon-Laux** [comment]
> do you know of an app where this works? i did not manage to drag'n'drop a screenshot that way to some other app.

the system apps and apps by apple basically. the trick is dragging with one finger than using a second finger to switch apps.

> for ipad, this is probably useful, macos os no goal currently, see https://github.com/deltachat/deltachat-ios/issues/1670#issuecomment-1214437428

I (as user) want it on iphone, the others are nice but I don't really care.
