### ISSUE TITLE
"share to delta" sometimes defaults to random chats

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1678]
imu, when i select "share to delta" without using a siri-link, the default destination chat should be "Saved Messages".

however, it happens from time to time that another chat is selected, first i thought i clicked wrongly, but meanwhile i can exclude this mostly :)

i sent several times a message to random ppl, where i just wanted to rember sth. for my own, so this is a quite serious issue. i do not have a concrete way to reproduce that, though.

so, we should double-check the initialization of the share dialog and if this can happen. and: we should also show the avatar, at least it would be much more obvious where the message will be sent to then.

**Comment by cyBerta** [comment]
I think maybe this is the moment where we start the general overhaul of the share dialog.

There's no way using the default elements iOS provides for the share context to add an icon next to the chat name in the lower table view cell.

**Comment by cyBerta** [comment]
@r10s I haven't found any obvious bug, however the UI might be misleading anyway. Shall we priotize to rewrite the share controller?

**Comment by r10s** [comment]
maybe let's do an av on that :)

**Comment by r10s** [comment]
as we could not reproducible this at all with any account but mine, and also the code looks pretty straight forward, it might be possible, that the issue is related to a erroneous siri entry, that was added at some point to my device. but this is only a theory, we could not verify nor falsify that ...
