### ISSUE TITLE
setting chat background crops to square

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1688]
probably because it reuses cropping for avatar or sth?

it should crop to screen/device aspect ratio in portrait mode instead, because that would make the preview more accurate to the actual result.

<img src="https://user-images.githubusercontent.com/18725968/190923340-15a5ecce-5ebe-4b69-8a98-1533a81d21fa.png" height=400 />

**Comment by r10s** [comment]
it is not a bug, this is how it is expected to work currently :)

advantage is, that this works fine with landscape and  quick device rotation, this was just the easiest approach.

of course, things can be done differently, but i would not throw resources at that currently.

**Comment by Simon-Laux** [comment]
I don't care about landscape, most people don't.
Yeah I did not re-find that issue.

**Comment by r10s** [comment]
>  don't care about landscape, most people don't.

see https://github.com/deltachat/deltachat-ios/issues/1502#issuecomment-1250368930
