### ISSUE TITLE
just sent message is not always added to chat view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1691]
sometimes, a just sent message is not shown the chat view (it is not only not scrolled down).

leaving and re-entering the chat shows the message and the message is also sent as expected.

i do not know how to reproduce that, but that happens to me every day, so maybe for 1 of 50 messages.

also, i can say that the issue is quite new, i noticed that the last weeks.

**Comment by cyBerta** [comment]
I wonder if that could be related to a missing event in core?

**Comment by Simon-Laux** [comment]
just had this, could also be a scrolling bug, because it was there once I scrolled down.

**Comment by Simon-Laux** [comment]
in #1969 there is a state where events are broken, there it happens all the time, so I also think this is about a missing event.
