### ISSUE TITLE
TLS 1.3 support?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1693]
was reported on the forum:
- https://support.delta.chat/t/tls-1-3-support-on-ios/2239
- https://support.delta.chat/t/does-delta-chat-support-tls-1-3/2231

Can we fix it or is it because we use system ssl or sth like that? Or do we just need to update openssl in DC core?

**Comment by r10s** [comment]
cc @link2xt

**Comment by r10s** [comment]
is this even an ios issue? also, not sure how practical only-tls-1.3 is, according to https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.3 this looks like bleeding edge to me, probably at some point support will get better automatically? cc @link2xt

**Comment by r10s** [comment]
k, so that will probably fade in then.

currently, it seems not advisable to set up a server _only_ supporting 1.3.

closing this issue as there is nothing ios can do about it.
