### ISSUE TITLE
`qrErrorAlert()` does not show account creation error from core

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1701]
https://github.com/deltachat/deltachat-ios/blob/00614004a88e590d8eeeb86e06a0f80c48f78fed/deltachat-ios/Controller/WelcomeViewController.swift#L372-L374

It should show the error too, like android does (android phishes it out of the last events, sure not ideal but I see no other quick way, it's not like we would migrate the whole iOS to jsonrpc over this that would be insane. maybe a new cffi call that writes the error in an error variable or returns a result struct, but I guess that is also too much work for now.).

Especially for `DCLOGIN:` it is needed because it tells the user to update if the version is not supported.

**Comment by Simon-Laux** [comment]
Looks like android also shows a non telling error message 😢, looks like we have to fix it over there too.

**Comment by r10s** [comment]
> maybe a new cffi call that writes the error in an error variable or returns a result struct, but I guess that is also too much work for now.).

such a call is already there :) `dc_get_last_error()` should return the correct error, this is also what android seems to do.

**Comment by Simon-Laux** [comment]
> such a call is already there :) dc_get_last_error() should be used here and should return the correct error, this is also what android seems to do.

yeah found it, and it already works! I added that fix to my new branch that adds support for dclogin
