### ISSUE TITLE
sharing to a one-to-one siri-shortcut faulty

### ISSUE THREAD

**Issue by paulaluap** [deltachat/deltachat-ios#1703]
to reproduce: 
- share a webpage from safari
- select a one-to-one siri-shortcut
- subsequent dialog shows "saved messages" instead of the selected one-to-one chat

same with sharing an image from the gallery and probably other apps.

sharing to a group works.

- Device: iphone x
- iOS version: 16
- Delta Chat version: 1.32

**Comment by cyBerta** [comment]
I can only reproduce that bug in a multi-account scenario if the selected account is not the one the one-on-one chat belongs to. Is that the case for you as well @paulaluap ?

**Comment by paulaluap** [comment]
> I can only reproduce that bug in a multi-account scenario if the selected account is not the one the one-on-one chat belongs to. Is that the case for you as well @paulaluap ?

thanks for taking care. no, i am not using a multi-account.

**Comment by cyBerta** [comment]
stepping back from this ticket for a bit, to focus on #1709, which I can reproduce

**Comment by r10s** [comment]
i found the failing line:

https://github.com/deltachat/deltachat-ios/blob/bf38b19e329c59cbadff66ad2e2cfc5cb97ddd4a/DcShare/Controller/ShareViewController.swift#L103

here, `if let intent = self.extensionContext?.intent as? INSendMessageIntent` fails with `self.extensionContext?.intent` being `nil` - maybe the intent is of another class?

**Comment by r10s** [comment]
i am also failing to reproduce "new chats" with the issue. also, when donating a previously failing contact again, things are fine. maybe this is some hickup from the ios15 -> ios16 upgrade?

**Comment by r10s** [comment]
there is no actionable item left, issues seems to come from previous versions. please reopen, if you manage to reproduce issue on a new installation.
