### ISSUE TITLE
Account Switch View Controller

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#1712]
With https://github.com/deltachat/deltachat-ios/pull/1687 we introduced a way to quickly switch accounts from the chat list ui. This ticket is a follow-up to replace the currently shown alert controller with a custom UIViewController with a similar UI to: 
[Safari's Tab selector](https://support.delta.chat/uploads/default/original/2X/9/986bbba3e9f0e2ad7fc9298610ec5cf440acd4a8.png).

When we're at it, we can also change the location of the unread message counter on the avatar to the upper right, which seems a little bit more common on iOS.

**Comment by Simon-Laux** [comment]
also see https://support.delta.chat/t/account-selector-on-avatar-on-chat-list/2242/2, there more discussions about UI possibilities.

**Comment by r10s** [comment]
yip, we've seen that.
