### ISSUE TITLE
support `mailto:` links inside html messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1724]
this is needed for bots, however, also useful in general.

**Comment by r10s** [comment]
afair, this is not about webxdc but just about normal html-mails.

**Comment by cyBerta** [comment]
ok, right, this is only implemented for webxdc right now. Thanks.

**Comment by cyBerta** [comment]
Shall we (a) always show the alert asking to create a chat with >contact< just as we do it right now, (b) ask to _write_ to a contact (new string involved) in case a chat already exists, or (c) omit the alert in that case?

**Comment by cyBerta** [comment]
since I already added a comment in the code about it: what about `tel://`?

**Comment by r10s** [comment]
i think, we do not need an alert at all.

- there is no network involved in creating a chat
- an accidentally created chat is easily deleted
- in most cases, this saves one tap

this is what we are doing on desktop (just tested) and android (iirc).

so, i suggest to remove the alert for the bubbles and do not add it for the html-view.

> since I already added a comment in the code about it: what about tel://?

would be great if that works in html-view the same way as for bubbles. however, as this part is not needed for bots, this is also less important. but if we can do that while on that area, that'd be great, sure.

**Comment by cyBerta** [comment]
I now remember why we added the alert: it was ment as a countermeasure against phishing attempts. The mailto links can be "forged", by e.g. showing a different address than the actual one that the user is going to write to.  The Alert parses the link and shows the email address which will be used as receiver.

**Comment by r10s** [comment]
> The mailto links can be "forged", by e.g. showing a different address than the actual one that the user is going to write to

but how can a mailto link be forged in the bubbles?

for the new html-view, this may be an issue, but not sure for the existing bubbles where the shown plaintext is what is opened.

but yes, to move forward, maybe do to the same as in bubbles, so show the existing dialog.

**Comment by cyBerta** [comment]
> but how can a mailto link be forged in the bubbles?

That cannot be done. it will only use the displayed text, not the underlying email address that might be different from what is shown. 
The forgery is only related to html emails and thus the change I've implemented here is also only focussing on Webviews.
