### ISSUE TITLE
copy a link from a message on long press

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1729]
This is missing and I need it in day to day usage. telegram, WhatsApp, iMessage, .... have that option and signal does something very weird (long press starts drag and drop for the link 🫤).

**Comment by r10s** [comment]
yip, that's be a useful enhancement.

as an alternative approach, one could allow somehow text selection and copy any arbitrary text to the clipboard - and maybe also allow translate etc. see the mastodon app to get the idea.  
challenge for that would be to not mess up with the normal long-tap, that should stay as is. telegram eg.  allows text selection only in the preview _after_ a long press.

just thinking, not suggesting :) 

the intially suggested long-tap-link-feature seems to be simpler and even telegram has that (and the text selection on top).

**Comment by cyBerta** [comment]
Telegram opens an UIAlertController on long press on a link offering to open the link in a browser of your choice, copying the link or adding it to the reading list which appearantly is a iOS feature. 
I think it's a good idea to give the user the choice to copy a link and not just automatically - and maybe accidentally - copy a link to the pasteboard on long tap.

**Comment by cyBerta** [comment]
> , one could allow somehow text selection and copy any arbitrary text to the clipboard - and maybe also allow translate etc. see the mastodon app to get the idea.

I think that's another nice improvement which could be done in a separate PR.

**Comment by Simon-Laux** [comment]
I mean show an option to copy, ideally not already open it (in a preview), because that could be bad for privacy.

**Comment by adbenitez** [comment]
moving stale almost 1 year old feature request to forum to get more feedback from users:
https://support.delta.chat/t/copy-a-link-from-a-message-on-long-press-in-ios/2755

**Comment by Simon-Laux** [comment]
It is important, I'm just not able to implement it even though I tried https://github.com/deltachat/deltachat-ios/pull/1808

you could close nearly all iOS issues for being stale, because the whole project is in maintenance mode since some time.

Also @r10s told me in a call that he would/can look into it after the message list/composer refactoring (https://github.com/deltachat/deltachat-ios/pull/1810, https://github.com/deltachat/deltachat-ios/pull/1767), so I think this counts as being planned.

**Comment by Simon-Laux** [comment]
@r10s just told me that he will not forget it even though it is now tracked in the forum.
