### ISSUE TITLE
what do do with the old account-switcher?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1732]
in settings there is still "switch account" using a simple alert. we could 

(a) remove it 
(b) also use the new account switch

i have a slight preference for (a) as this would make the whole app more logical, also in-line with android and desktop (upper left switches account).

and one settings line less :)

it is maybe less discoverable, however, i am sure, ppl will find it (cmp, https://github.com/deltachat/deltachat-pages/issues/568) (ftr, signal has settings and whatnot there without naming it as such) - and if not at the first glance, this seems still okay as a second account is usually not the first ppl are doing (and this may even be an advantage as the app appears simpler on first usage).

**Comment by cyBerta** [comment]
The basic version of the new app switcher is already released, right? Then I would agree, we could to (a) since users hopefully had the chance to find the new position for switching accounts.

**Comment by r10s** [comment]
> The basic version of the new app switcher is already released, right?

yes, it is released in 1.34.1.

**Comment by Simon-Laux** [comment]
Is the new account switcher in the top bar accessible with accessibility / screenreader?

**Comment by r10s** [comment]
`accessibilityLabel` is set, so the function is probably even more perceptible than it's visual representation :)

**Comment by cyBerta** [comment]
https://github.com/deltachat/deltachat-ios/issues/1722 is still open

**Comment by cyBerta** [comment]
We should inform in the update message where to find the new account switch
