### ISSUE TITLE
Bottom of message gets cut off

### ISSUE THREAD

**Issue by snan** [deltachat/deltachat-ios#1737]
If I have an external keyboard plugged in over USB, I can't see the lowest part of the most recent message. I can pull it up temporarily to read it, but as soon as I let go, it snaps back. Most importantly, I can not follow links in there.

![IMG_1697](https://user-images.githubusercontent.com/309417/199307338-596bf56d-e418-45df-bd6d-72f04baf4e70.png)

**Comment by cyBerta** [comment]
it looks like this issue also exists on some iphones, which have the long black bottom swipe UI element (I don't recall the name right now) which acts as an replacement of the home btn.  And it seems to be related to ios 16

**Comment by r10s** [comment]
yip, it is not only ipad os meanwhile ... needs to be fixed soon and should go to the next update :)

**Comment by MrPetovan** [comment]
I have witnessed some improvement with regards to this issue: The default view still cuts off the bottom of the conversation, but scrolling it into view now keeps it into view, there's no pull back behind the input bar.

**Comment by Simon-Laux** [comment]
![image](https://github.com/deltachat/deltachat-ios/assets/18725968/a4f8bb3d-dd99-4a18-818b-758d2f12cdf2)
another example of this bug
