### ISSUE TITLE
number of images/files way too large for mailinglist members

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1779]
when tapping the profile of a mailinglist member, at least for some mailinglists, the number shown beside "Images and Videos" and "Files and Private Apps" are way too large. i assume, that these numbers reflect _all_ files of the given type:

<img width=320 src=https://user-images.githubusercontent.com/9800740/209221902-4c06e1c3-92e2-42a4-a4f7-a8dafe4b7f56.jpg>

when tapping the items, nothing happens. also "Last seen" seems to be wrong, we should maybe just hide all these items

reproducible at least in the mailinglist "Delta Chat Community (🇬🇧EN)".

**Comment by cyBerta** [comment]
That issue doesn't occur on Android? I thought this would be a core issue.

**Comment by r10s** [comment]
android/desktop do not show these numbers at all.
