### ISSUE TITLE
indicate that exported backups will be deleted when the app is deleted

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1792]
unless copied somewhere else by the user, exported backups are deleted when the app is deleted (there seems not to be a way around that apart from iclould, dropbox etc. and maybe keychain, which, however, does not allow large files, cmp [here](https://stackoverflow.com/questions/47900511/save-file-in-ios-that-retain-even-the-app-is-deleted-swift) or [here](https://stackoverflow.com/questions/38342220/realm-swift-is-it-possible-to-keep-database-after-the-apps-is-uninstalled))

even if the initial messages says "Keep the backup file in a safe place", this may be unexpected, esp. if you are new to ios.

therefore, we should at least add a more explicit hint to the new "backup success" dialog, currently it just says Backup written successfully to \"Files -> Delta Chat\", which is a bit hacky anyway (`pref_backup_written_to_x` is from android/desktop and usually takes a path.

so, maybe go for a `pref_backup_written_to_ios` string, that way we can also reword the first part, all in all maybe sth. as:

> Backup successfull. As long as the Delta Chat app is not deleted, you can access it using the iOS Files app or, after connecting your phone to a mac, in the macOS Finder.
> 
> If you want to delete the Delta Chat app and keep the backup, you have to copy it to another folder before.

wording suggestions welcome, i'd first only put the strings to "untranslated" so we can easily improve on that.

this is  a successor of https://github.com/deltachat/deltachat-ios/pull/1787

**Comment by cyBerta** [comment]
Backup successful (title)
You can find it with the Files app in the Delta Chat directory.
Move the backup to another folder if you intend to keep it before deleting Delta Chat.

**Comment by r10s** [comment]
yip, that wording and the explicit title is more straight forward.

**Comment by r10s** [comment]
wrt the "move to another folder" - can you please try out that this really helps when using a local folder?

**Comment by cyBerta** [comment]
as long as the backup is not moved to another folder _within_ the Delta chat directory that works, yes. So I am thinking if we need to be more explicit, to move the the backup _outside_ the Delta Chat folder. e.g.:


Backup successful (title)
You can find it in the Delta Chat directory using the Files app.
Move the backup out of that folder if you intend to keep it before deleting Delta Chat.
