### ISSUE TITLE
in-chat-search up-/down-functions missing sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1796]
i've seen the [in-chat-search up-/down-functions](https://github.com/deltachat/deltachat-ios/pull/1372) missing in mailinglists where one cannot write to,
as well as in the device chat.

maybe the buttons are always missing when one cannot write to a chat (as the buttons are part of the keyboard somehow, iirc, there was even some discussion to fix that later :)

**Comment by cyBerta** [comment]
easiest solution would be to disable the search button for read-only chats for now. 
otherwise we'll add more conditions around the input bar logic, which can be done of course.

**Comment by r10s** [comment]
yeah, as one can write to many mailing lists meanwhile, there are not so many read-only chats left, so disabling search for read-only chat, although a pity, seems to be a reasonable thing currently.

maybe add a little comment as "disabled as up/down buttons belong to the keyboard for $reasons and the keyboard is not available in read-only-chats"
