### ISSUE TITLE
Minimum Target is iOS 11

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#18]
If you try to compile to a version before 11 it fails with swift errors.
I got it to compile to iOS 10 by the help of Xcode (`if #available`) but to compile it to 9.0 it needs 3 more of those errors fixed. 
As I'm new to swift and iOS native development I'm not so sure if I should attempt to fix those..

TL;DR;
We should support older devices too - as far as apple allows it (currently iOS 8).

**Comment by jonasreinsch** [comment]
With iOS 11 as minimum target we currently (December 3, 2018) reach 91% of all iOS devices. IMHO targeting older devices can wait until we have the minimum viable version ready (and then, the market share of iOS 11 & 12 will have increased further).

Source: https://developer.apple.com/support/app-store/

**Comment by Simon-Laux** [comment]
I agree with the part, that we should care about older versions after the minimum viable version is done.

And as a Messaging app that could still make use of the network effect (although we have everyone with an email address already), it would be good to support the most devices we can in my opinion.

**Comment by r10s** [comment]
@Simon-Laux thank you for checking this out.

and i agree, we should target as many old versions as possible. in general, i think, versions supported by apple should also be supported by us (in contrast to android, afaik these are not very age-old systems anyway).
also, imho, we should keep in mind that these 91% may be much lower on some markets and countries.

however, i think it is okay if some advanced features simply do not work. but the basic app should work.

i am not sure if if is easily possible to target this issue "at the end of" development. maybe we can change some things then, however, i think it is always good to keep this issue in mind :)

**Comment by Simon-Laux** [comment]
Update: I got it to compile with the build target = iOS 10, but as I ran tried to run it on an Phone with iOS 10 and more errors poped up. Turns out supporting older iOS Versions isn't as easy as I thought xD

**Comment by r10s** [comment]
meanwhile we [target 97%](https://developer.apple.com/support/app-store/) of all ios devices with the current minimum of ios11 - targeting the remaining 3% is possible only partly, and event this seems to introduce several problems.
i think at least for now, we do not have to capacity to handle them.
