### ISSUE TITLE
no back button to return to chat after viewing an image from a chat

### ISSUE THREAD

**Issue by limacycle** [deltachat/deltachat-ios#1800]
- Device: Iphone 12 pro
- iOS version: 16.3
- Delta Chat version: 1.34.10
- Expected behavior: press on a back button, or tap /swipe on image to return to chat after opening an image
- Actual behavior: no back button and no gestures work to leave the image view, only way to return to chat is to kill delta chat and restart the app
- Steps to reproduce the problem: open any image in a chat
- Screenshots: /
- Logs: /

**Comment by r10s** [comment]
i am on 16.3 on a iphone13mini, the back button shows and works as expected. @limacycle can you please double-check, and maybe also post a screenshot? @all someone else having the same issues with a recent delta chat?

**Comment by limacycle** [comment]
I double checked my ios version, the issue was on ios 16.0 indeed. On ios 16.3 everything works as expected. Sorry for wasting your time. Great APP, very grateful for everyone's work. Thank you.

**Comment by r10s** [comment]
thanks for coming back! enjoy the app :)
