### ISSUE TITLE
allow to delete a single message

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#181]
i think this should be done using a UIAlertController - which can then also be used for "info" or other options (do not show two controls as telegram does currently (one abottom of the screen, one beside the message))

**Comment by r10s** [comment]
i would prefer a long click that shows an `UIAlterController(... preferredStyle: actionSheet)` with "delete" and "info" abottom of the screeen. later we will then can "forward" and "copy to clipboard" and maybe other stuff there.
this UIAlterController would appear _instread_ of the current mini-menu-popup shown aplace of the message.

this would also fit perfectly to the existing alert for the contact requests.

**Comment by r10s** [comment]
but if we add "delete" to the existing menu, this would probably be also fine.

it is probably much easier - we can then see how this works out and change it later as needed.

**Comment by cyBerta** [comment]
ok, I've almost finished the first approach, we can refactor the item menu as a whole in the next iteration.
