### ISSUE TITLE
show notifications if the app is in foreground

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1811]
we should do the same as on android:

chat view:

- when a message for a different chat than the one opened is received, the notification should be shown, otherwise not

chat list:

- no notifcations? maybe apart from if you're in archived view? what is android doing here?

all other views: 

- show notifications

EDIT: there is already a `isShowingChat()` that may become handy.

**Comment by adbenitez** [comment]
in my personal experience this popup notification is too intrusive and annoying/frustrating/stressful more if you receive several short messages and your screen will be often covered by that popup notification while you are trying to reply to someone in a chat, I always disable the "show notifications popup" for delta chat on android

is the sound played and the app icon shown in the status bar indicating that there is a new message? then that is more than enough IMHO,

I recommend moving this to the forum to get more feedback from users

**Comment by r10s** [comment]
> I recommend moving this to the forum to get more feedback from users

did so: https://support.delta.chat/t/show-notifications-if-the-app-is-in-foreground/2759

**Comment by r10s** [comment]
for the record, we meanwhile have in-app-badge counters that guide to the new messages, also to other chats. popup notifications are not shown on purpose when Delta Chat itself is open
