### ISSUE TITLE
`Scan QR Code` has no read from clipboard or from image option

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1835]
the displayed qr codes show an option to copy the qr code content, but on the scanning screen the option is still copy (makes not much sense there).
And currently the options for scanning from an image or reding qr data from clipboard are missing.

<img width="175" alt="image_2023-04-06_17-39-46" src="https://user-images.githubusercontent.com/18725968/230454974-b1649605-7a96-4ec0-a482-89ab1d3c6425.png">

**Comment by r10s** [comment]
ftr: see discussion at https://github.com/deltachat/deltachat-ios/issues/1653 why that option was regarded less important compared to other things
