### ISSUE TITLE
more convenient option to attach image from gallery as original

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1840]
One argument for always compressing images was that the send as file option is still available.
I recently needed it and couldn't find it.
When sending files it does not allow me to select images from the gallery, I think that is different from android as it might be possible there to send images from the gallery via the file explorer.

The only work around I could think of it to go into the gallery export the image from there to files and then select it in delta chat with attach file. Though that is hardly convenient and you need to know that this possibility exists to use it as it is not really intuitive for normal users.

**Comment by r10s** [comment]
indeed, this is not that simple. not sure, but i think, this was different in the past, where you could just select gallery images from the file explorer; maybe sth. has changed in the os.

we should check that and maybe add sth. more comfortable, until then, exporting from gallery is inconvenient, but not the end of the world

**Comment by r10s** [comment]
asked some more experienced whatsapp and ios user:

the issue is exactly the same for whatsapp. however, it is be pretty known to advanced ios users that one has to export images as files before they can be send as original with whatsapp. so, going the same path here, is good enough for now.

same for signal, seems at least. telegram has other options.

so, we're as good or bad as whatsapp/signal here, i would not consider this as a bug any longer.  there are more important things to fix and to put our limited resources on :)

**Comment by r10s** [comment]
nb: if someone wants to do sth. about this, i suggest an _unobtrusive_ three-dot-menu top-right of the staging area with the option "Send as original file" - once tapped, the staging area converts to the view usually shown for files, so, showing bytesize etc. the option must not be available for already edited files.

this way, we would not clutter the ui for normal users.

same idea can apply to android/desktop.

but again, i do not see that as important in anyway - even less by the information wrt whatsapp/signal.

**Comment by Simon-Laux** [comment]
Just forgot about the compression, send myself some documents as images and they were unreadable. If there were an option for it in the staging area or while attaching I wouldn't have missed that. really annoying issue when you run into it.

**Comment by r10s** [comment]
moving discussion to the forum https://support.delta.chat/t/more-convenient-option-to-attach-image-from-gallery-as-original/2761/2
