### ISSUE TITLE
bug: you should not be able to swipe on message results in search

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1869]
it's confusing because it acts on the chat and not on the message. especially delete the delete option.

**Comment by r10s** [comment]
i agree with delete, we should  not offer that as false assumptions would be an undoable, destructive action.

for pin/archive things are different: the items look like chats, the action is undoable, and also directly visible (eg. you'll see the "archived" tags on all related messages)

however, it seems to be a very minor thing, and to be in sync with desktop/android here and to not enter nitpicky discussions, i removed also these options at #1870. if there are complains, we'll easily can re-add them.
