### ISSUE TITLE
Embed Safari into Delta Chat

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#187]
Received web links can be opened through Delta Chat using an embedded Safari without additional process is not required. Refer to this [Apple documentation](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller).

**Comment by r10s** [comment]
what would be the advantage compared to the current state where there is a backlink in the upper right corner of safari that brings you back to the app?

anyway, feature request should be discussed in the forum at https://support.delta.chat , there is also a broader audience. this issue tracker is more for bugs and for tracking things people are actually working on.

so, i close this for now, we can re-open it as needed.
