### ISSUE TITLE
verified one-to-one chats

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1910]
summary: https://github.com/deltachat/deltachat-android/pull/2560#issuecomment-1646659408

relevant section in android pr to to update stock strings: https://github.com/deltachat/deltachat-android/pull/2560/files#diff-faaf35bfe16342d72a9547e1666b3da5506ac5ad54f23fef815c3141d3b2e29f

desktop issue: https://github.com/deltachat/deltachat-desktop/issues/3327

**Comment by Hocuri** [comment]
But don't do this yet without also adapting to verified 1:1 chats in general. The relevant comment in the Android code:

```
    // The next two strings should only be set if the UI actually shows more info when the user clicks on the
    // DC_INFO_PROTECTION_{EN|DIS}ABLED info message
```
