### ISSUE TITLE
Some images are not displayed in "All Media" and the local media library

### ISSUE THREAD

**Issue by raiden-social** [deltachat/deltachat-ios#1911]
Some images are not displayed in "_All Media_" and the local media library. 
Instead, there is just an empty field. If you tap on it, the picture will open normally. 
All images are displayed in the list view and in the chat history.
I didn't notice this bug before, so I'm not sure if it could have something to do with yesterday's iOS 16.6 update.

Device: iPhone 14
iOS version: 16.6
Delta Chat version: 1.38.2

Addendum:
The bug also occurs in DC-iOS 1.40 (iOS 17.01).
When I create a backup and load it into DC-Desktop 1.40.4, all images are displayed normally in the media library there.

**Comment by r10s** [comment]
i cannot reproduce this, does that happen for specific images (so always the same images)? if so, maybe you can post/link one of them here or send them to me (email on my github profile)

**Comment by r10s** [comment]
> Maybe it would be helpful to send you the pictures via DC?

yes, that'd be helpful. you can delta me at: r10s at b44t.com

**Comment by r10s** [comment]
thanks a lot, i received the images and could also easily reproduce the issue. i will try to fix that in the next ios issue gardening round

(reminder to myself: the images are stored in folder: ios-image-issue-1911)

**Comment by r10s** [comment]
yeah, finally, i can see the nice bears :) 

![Screenshot 2023-12-14 at 23 55 34](https://github.com/deltachat/deltachat-ios/assets/9800740/c3eba4a8-0def-42cd-b9fe-b372f74a6e7a)
