### ISSUE TITLE
duplicated email validation code (swift and core)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1918]
We have email validation in swift:
https://github.com/deltachat/deltachat-ios/blob/bad499e7bd21ce424f19425abcdfe394b4db8fa5/deltachat-ios/Helper/Utils.swift#L7-L18

And in core: `dc_may_be_valid_addr`

which is backed by this rust function: https://github.com/deltachat/deltachat-core-rust/blob/f94d34c94b5f00aaf3c3571065d3bcf5a4c2021a/src/tools.rs#L517

I propose that we should use the rust function on all platforms and improve it to do better / more correct parsing if necessary.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/1929
