### ISSUE TITLE
qr-code in my-profile broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#192]
not totally sure about the reason, might be that the updated core does not profile a qr-code-string.

<img src=https://user-images.githubusercontent.com/9800740/63786190-dfdd3300-c8f1-11e9-856a-8882ab4a7ae0.png width=320>

**Comment by cyBerta** [comment]
fixed in latest core

**Comment by r10s** [comment]
yeah, things are getting better now :)
