### ISSUE TITLE
App crashes on start - or not?

### ISSUE THREAD

**Issue by Skeeve** [deltachat/deltachat-ios#195]
I used DC for just 3 chats. 2 of which I sent just one message, no reply.

1 I sent a few message and got replies.

I have a gmx.net account, the recipient an online.de account.

The last actions before the. crashing started were:

Without mobile data on, no WLAN connection
- Started to write a reply.
- switched off without sending
- Some minutes later went back to finish the reply but it was gone, so started again to write it
- Sent it
- switched off
- realised I have mobile data off
- switched on
- saw "pending" for the message
- switched on mobile data
- saw "pending" changing to "sent"
- switched off

After that I could never come back to DC. It simply opens and crashes instantly. Or maybe it doesn't crash, but goes away. When Double-pressing the home button I see delta.chat settings. But when clicking them DC comes to front, quickly shows my contacts and goes away.

**Comment by Skeeve** [comment]
Reinstalled and it worked for 2 days. Now back to the crashes without any previous specialties

**Comment by r10s** [comment]
i assume you're using the testflight release?

in fact, this uses a beta-core, currently, there are huge efforts to make this one stable, see https://github.com/deltachat/deltachat-core-rust/commits/master

once done, we'll release a new testflight release which should be much more stable then.

**Comment by Skeeve** [comment]
> i assume you're using the testflight release?
Yes, I do.

> once done, we'll release a new testflight release which should be much more stable then.
looking forward to that as I already advertised DC as an alternative to use instead of WhatsApp.

**Comment by r10s** [comment]
there are lots of improvements wrt sending and various crashes have been fixed.

please reopen if the problem still exists in v0.920.1
