### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1973]
Our current logging system needlessly passes around a logger instance and thus combines logging with dc core wrappers which makes code more complex without providing any benefit.

## A. Unified System Loging
https://developer.apple.com/documentation/os/logging/generating_log_messages_from_your_code - iOS system logging
Pro:
+ used by system and is what apple wants you to use
+ ability to redact private information
+ nice tutorial on https://developer.apple.com/videos/play/wwdc2020/10168/

Contra:
- different syntax for using it
- no pretty emojis I guess.
- the new friendly api is only available since iOS 14, while we still target iOS 11, but os_log is already available (but not so nice syntax and we should not wrap it according to this site: https://steipete.com/posts/logging-in-swift/)

## B. Customisable Logging with swift-log
https://github.com/apple/swift-log - logging in swift like the rust log crate (an interface with many implementations)
one implementation is https://github.com/sushichop/Puppy, which has many options (saving to apples unified logging system, file, stderr and so on) that can also be combined.
Pro:
+ many options
+ we could probably keep our pretty logging output

Contra:
- different syntax for using it
- extra packages to install

## C. Keep out logging system, but turn it into a singleton

our current logging system is passed around through dc contexts, this is not needed as the login system has no dependencies and just is a wrapper function for `print()`.

It would simplify code not to pass it through context, but instead use it globally.

**Comment by Simon-Laux** [comment]
since A is only really nice if we update to min target iOS 14 and looks like this if we don't
```
// Log a message to the default log and default log level.
   os_log("This is a default message.")
            
   // Log a message to the default log and debug log level
   os_log("This is a debug message.", log: OSLog.default, type: .debug)
            
   // Log an error to a custom log object.
   let customLog = OSLog(subsystem: "com.your_company.your_subsystem", 
            category: "your_category_name")
   os_log("An error occurred!", log: customLog, type: .error)
``` from https://developer.apple.com/documentation/os/logging/generating_log_messages_from_your_code#3665951

I would prefer B or C. But I would also be fine with using os_log directly.

**Comment by Simon-Laux** [comment]
![image](https://github.com/deltachat/deltachat-ios/assets/18725968/f053387a-8263-46e2-b6ad-6bde2a165267)
So emojis are possible also in `os_log` so I would opt for using os_log directly.

**Comment by r10s** [comment]
is our current implementation using https://developer.apple.com/documentation/os/logger ? richy did that not so long ago, i forgot a bit about the details, in general it works.

iiuc, there are two smaller improvements in the discussion:

- getting rid of passing logging handles around (that end up in a global logger anyways)

- calling `os_log()` instead of `print()` (do both end up in the local console - or what is the precise advantage?) - we can also replace these 5 calls in SimpleLogger

**Comment by r10s** [comment]
concrete suggestion at https://github.com/deltachat/deltachat-ios/pull/1988#issuecomment-1815625452
