### ISSUE TITLE
Event Loop attempts to store values on ephemeral context object.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1975]
The event handler loop creates a new context object on every iteration:
https://github.com/deltachat/deltachat-ios/blob/35448d189ab5bedba07929811f667fd77ca392be/DcCore/DcCore/DC/events.swift#L28

It then tries to store 2 values on this temporary object:
`dcContext.lastWarningString`:
https://github.com/deltachat/deltachat-ios/blob/35448d189ab5bedba07929811f667fd77ca392be/DcCore/DcCore/DC/events.swift#L42-L45
and `dcContext.maxConfigureProgress`:
https://github.com/deltachat/deltachat-ios/blob/35448d189ab5bedba07929811f667fd77ca392be/DcCore/DcCore/DC/events.swift#L47-L49

## About it's (unreachable) usage

https://github.com/deltachat/deltachat-ios/blob/e586e69cbafdbc67ae30dfe877b53b09e7ca9708/deltachat-ios/Controller/AccountSetup/AccountSetupController.swift#L573-L581

Also the line in question (L578) is not really reachable in practice, because `appDelegate` is normally always available.
Furthermore while adding a print statement outside of that if clause I confirmed that both variables are empty.

The comments here say it's temporary and there are already 4 years old. So also older than multi account, where the context object was still a global singleton.
https://github.com/deltachat/deltachat-ios/blob/40314e72a6c80af3102f0d195ffec96f6aab98b7/DcCore/DcCore/DC/Wrapper.swift#L115-L116

**Comment by r10s** [comment]
thanks for analysis, indeed the two vars were added to get a grip on "future timed out" messages at https://github.com/deltachat/deltachat-ios/pull/712 , that time with a single context.

as "future timed out" was not seen for a long time and the code is indeed dead meanwhile - yeah, let's prune the code :)
