### ISSUE TITLE
Events do not log the account id they belong to

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1977]
This makes debugging with multiple accounts harder.

**Comment by Simon-Laux** [comment]
If we use a logging library (#1973) we could use a scope while logging (like `chat.delta.account.${accountId}`) but maybe it could already be enough to just log it similar to how desktop does it:

As number:
<img width="768" alt="Bildschirmfoto 2023-11-15 um 02 47 16" src="https://github.com/deltachat/deltachat-ios/assets/18725968/dbce6a2d-2d1e-411f-98e1-c8b2c5753fa9">
Or number with emoji (emoji depending on wether the account is the selected one, though desktop also uses css to style it):
<img width="768" alt="Bildschirmfoto 2023-11-15 um 02 49 48" src="https://github.com/deltachat/deltachat-ios/assets/18725968/fbcba270-dc85-4759-a2a2-654be0c52680">

**Comment by r10s** [comment]
we decided in one-to-one chat that this is no bug and we may decide to add logging information as needed and if there is really a benefit

closing for now, if required, we would directly open an issue
