### ISSUE TITLE
🧡  unknown events

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1982]
These events are not implemented to be logged yet:

- 105 DC_EVENT_IMAP_MESSAGE_MOVED
- 106 DC_EVENT_IMAP_INBOX_IDLE
- 2006 DC_EVENT_INCOMING_MSG_BUNCH

**Comment by r10s** [comment]
yeah, we should remove these "unknown event" log lines, they are not helpful and noise-only

**Comment by Simon-Laux** [comment]
so you would not add these events to the log?

**Comment by r10s** [comment]
idk, on android, for example, we do not log any event unconditionally, not sure on desktop. i would see that a bit situation-dependent, but eg. i would not like code that needs maintenance on any event added (that is not even used)

**Comment by Simon-Laux** [comment]
DC_EVENT_INCOMING_MSG_BUNCH and DC_EVENT_IMAP_INBOX_IDLE might be interesting for background task debugging if they don't also already are mentioned in the normal info, error, warning events.
