### ISSUE TITLE
make clearer that "database encryption" is highly experimental and will slow down devices and notifications

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1989]
This delays appstart and thus is annoying at least.
Also could be another contributing factor to our notification problems.

**Comment by r10s** [comment]
in general, iirc, sqlcipher uses key derivation, which is slow by design

this is also the reason that we keep database and app open in background as long as we can

nb: for me even unencrypted desktop takes a handful of seconds to start with a large database (another annecdotical datapoint :) - so 5s on a maybe older phone may be just fine

so, you'd need to provide more information and measurements, however, as the whole thing is experimental, and questionable on iOS at all, not sure if i would throw much time on that currently

**Comment by Simon-Laux** [comment]
> this is also the reason that we keep database and app open in background as long as we can

we can not do that because of #1979, maybe if we change where the db is saved and change how the share-extension works? maybe then apple would allow us to hold the locks in the background?

> nb: for me even unencrypted desktop takes a handful of seconds to start with a large database (another annecdotical datapoint :) - so 5s on a maybe older phone may be just fine

On desktop:
- it is one time, not every time I reopen the app
- it does not look like the app is frozen in desktop during loading
- much of it is probably also due to rosetta emulation


> in general, iirc, sqlcipher uses key derivation, which is slow by design

That's why other programs like keepass offer a way to test how many derivations you can do in one second and apply that value.

**Comment by r10s** [comment]
> > On desktop:
>
> it is one time, not every time I reopen the app
> it does not look like the app is frozen in desktop during loading
> much of it is probably also due to rosetta emulation

sure, sure, sure. i wanted to point out that 5-6 seconds may be normal for larger databases and slower devices

anyways, as discussed one-to-one, sqlcipher discussions, as being an experimental side-thing, should be removed from notification discussions, it is unclear how useful sqlcipher is on iOS at all.

but we can make things clearer in the UI that the feature is not recommended at all and will slow down things (eg. on anroid, we speak of "Highly experimental - use at your own risk")

**Comment by Simon-Laux** [comment]
FTR: I seem to not have this (6 second) problem when there is no debugger attached, but I need to look at this aspect for a few more days using the current version.
