### ISSUE TITLE
Constantly swapping out and getting oomed

### ISSUE THREAD

**Issue by snan** [deltachat/deltachat-ios#2014]
- Operating System: iPad OS
- Delta Chat Version: 1.42.4
- Actual behavior: Delta Chat is slow and I don't get any notifications and whenever I start the app it shows the startup splash screen as if it had been in torpor. Maybe I finally have too many mails? But it started with the recent upgrade to 1.42.4.

**Comment by r10s** [comment]
thank you for your report!

can you please try over with the just [released testflight 1.42.7](https://testflight.apple.com/join/uEMc1NxS) that aims to fix similar issues? the testflight release also shows crashes and offers you to send logs to us easily

**Comment by r10s** [comment]
closing stale issue without actionable item.

if needed, please file a new issue for 1.44 with fresh information.
