### ISSUE TITLE
Using BGAppRefreshTask

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-ios#2030]
While writing an answer to a [forum question](https://support.delta.chat/t/why-cant-delta-chat-use-imap-idle-or-long-polling-as-a-workaround-on-ios-for-long-notification-delay/2859/2) I looked up Apple documentation for correct terminology and noticed that we are not setting up our background tasks according to the latest recommendations.

Looking at the documentation for [background tasks](https://developer.apple.com/documentation/backgroundtasks) and [Using background tasks to update your app](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app) I have found that it mentions [`BGAppRefreshTask`](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask) class which is described as "An object representing a short task typically used to refresh content that’s run while the app is in the background."

I have not found any mentions of this is the code though.

Should we follow the instructions and give our background task an identifier, mark it as a "Background fetch" task and so on? Maybe this will result in running it more frequently?

I have also listed that `fetch` [UIBackgroundMode](https://developer.apple.com/documentation/bundleresources/information_property_list/uibackgroundmodes) is listed in the Info.plist:
https://github.com/deltachat/deltachat-ios/blob/1bd80d9d7fb9c93839276e4e55c93508d8e4f32f/deltachat-ios/Info.plist#L84

It is also stated that

> In iOS 13 and later, adding a BGTaskSchedulerPermittedIdentifiers key to the Info.plist disables the application(_:performFetchWithCompletionHandler:) and setMinimumBackgroundFetchInterval(_:) methods.

We are however still using deprecated `performFetchWithCompletionHandler`.

There is a tutorial describing the changes from iOS 7 to iOS 13 at
https://www.andyibanez.com/posts/modern-background-tasks-ios13/

We still officially support iOS 12, but maybe this new API can be tried and used conditionally?

**Comment by r10s** [comment]
at a first glance, it should indeed be possible to wrap [Apple's example](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app)  into `if #available(iOS 13, *) { }` blocks. not sure, however, if that would  result in more frequent wakeups, that time, we voted for doing the "fallback" only (that would be still needed to target iOS 12).

**Comment by r10s** [comment]
closing and moving to resurrection this as there is not really an actionable item and with https://github.com/deltachat/deltachat-ios/pull/2071 / https://github.com/deltachat/deltachat-core-rust/pull/5104 things are faster and seem to be quite reliable, at least on my devices. we'll see how things perform with the next testflight. the real solution will be the upcoming real push anyways, without that, things seems to be always throttled
