### ISSUE TITLE
creating a backup a second time fails

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#204]
a second click on "settings / backup" fails, the app gets unresponsive, the progress dialog is not closeable. but the app did not crash. maybe some internal "abort" state  used by the progress dialog set wrongly.

nb: i think the progress dialog should use the system-like, not sure if this is the case, configure-account seems to be sth. different, not sure which is the "correct" one.

**Comment by r10s** [comment]
seems to be a core-issue, will have a closer look ...

**Comment by hpk42** [comment]
should be fixed by the recent master merge of async-imap.
