### ISSUE TITLE
VideoInviteCells don't show reactions

### ISSUE THREAD

**Issue by zeitschlag** [deltachat/deltachat-ios#2084]
Either show reactions or disable reactions for video invitations

**Comment by Simon-Laux** [comment]
we hide the option to react on those messages in desktop: 
- [code](https://github.com/deltachat/deltachat-desktop/blob/b466ac146f247936dac97342201968136f7ee8b9/src/renderer/components/ReactionsBar/useReactionsBar.ts#L50)
- https://github.com/deltachat/deltachat-desktop/pull/3642
