### ISSUE TITLE
messages hidden sometimes after context menu was shown

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2095]
the reason for the hiding is to not show the message as blurred as well as in the foreground, which is esp. on iPad not-so-nice.

however, there is a bug or race on unhiding, it is hard to reproduce, but it happens several times a day for me.

unless the issue is obvious and we can fix the hiding/unhiding easily, i suggest to not hide the messages at all, that seems to be the better tradeoff.

@zeitschlag iirc, you know exactly the "two" lines for hiding/unhiding - can you do a PR?

**Comment by zeitschlag** [comment]
The reason I did this was, that it looked weird on iPad, as there's no blur:

![Screenshot 2024-03-01 at 10 34 48](https://github.com/deltachat/deltachat-ios/assets/2580019/4d004c6f-9148-4064-aeb6-a13c197b8aa7)

**Comment by r10s** [comment]
still better than having things randomly disappeared and staying like that, i'd say (in case we have to decide for the one or the other and do not find a fix "soon")

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-ios/pull/2099
