### ISSUE TITLE
unblock blocked contacts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#211]
the settings should have a TapActionRow names "Blocked contacts" (needed strings are already present) that shows a list of all currently blocked contacts and the option to unblock them.

see android to get an idea.

i think the normal contact list and/or items should be reused for this purpose.

**Comment by r10s** [comment]
great, also though that we need this somehow soonish :)

i would add the `Block contacts >` entry as the first item just below settings/communication (before settings/read-receipts as the footer refers just to that item)

**Comment by cyBerta** [comment]
ok

**Comment by r10s** [comment]
closed by #275
