### ISSUE TITLE
make context menu better manageable by devs

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2111]
currently, there is a little abstraction layer for the messages' context menu, that does not help much or avoid double code, but makes "nicer" things harder -eg. having a separator, submenus, or [preferredElementSize](https://developer.apple.com/documentation/uikit/uimenu/4013313-preferredelementsize)

let's make the code there much simpler, and split only between "current iOS, having all nice menu options" (that would be ios15) and a fallback that works also on ios12 (using the old, text-edit-like menus without blurring)

for reactions, it is fine to offer just a simple "react" for ios14 and below that opens the "any emoji selector" (currently, we do not have reactions at all for ios12)

@zeitschlag please correct me if i understood sth wrong :)

**Comment by Simon-Laux** [comment]
We could maybe also build the array with `push` to be able to use if statements, currently some code looks a bit duplicated:

https://github.com/deltachat/deltachat-ios/blob/a4029cf67085cbae1e17a38f9613c8aa39934b10/deltachat-ios/Chat/ChatViewController.swift#L231-L245

At least would be hard to add multiple conditions currently.

In desktop we have arrays that can have `false/null` or `context menu item` so we can construct the array with inline if statements:
```typescript
const items = [
hasSelection ? CopyItem : null,
canReact ? ReactItem : null,
MessageInfoItem,
]
// in javascript you can write this in a shorter manner
const items = [
hasSelection && CopyItem,
canReact && ReactItem,
MessageInfoItem,
]
```

I'm not sure is such tricks are possible in swift so I would suggest building the array with `.push(ContextMenuItem)` and if statements.

**Comment by zeitschlag** [comment]
@Simon-Laux Feel free to give it a try.
