### ISSUE TITLE
scroll down on-sent missing sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2129]
when the message view is already scrolled down completel, sending a new message does not scroll down.

cave: for incoming messages we want to scroll down only if already scrolled down - otherwise the scrolling position should stay as is (otherwise it is hard to read old messages in a chatty chat)

Seems to happen with stickers.

**Comment by r10s** [comment]
ftr: to reproduce, open a somehow filled "Saved Messages" and send sth. as "hi" (in the video, scroll down happens only when tapping the corresponding button);

https://github.com/deltachat/deltachat-ios/assets/9800740/98664981-9a2d-428e-992e-58690f7c5d97

**Comment by r10s** [comment]
it is happening again on current master :/

(the last visible message with the text "3" only became visible after manual scrolling)

for reproducing: it happens quite often, but not _always_ ...

https://github.com/user-attachments/assets/a61f56b7-bdb6-4713-a53c-eeec2611f96b

**Comment by zeitschlag** [comment]
Will close and create a new issue.
