### ISSUE TITLE
Replace 4 weeks with 5 weeks at "Setting / Chats and Media / Delete Old Messages"

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-ios#2152]
Similar desktop issue: https://github.com/deltachat/deltachat-desktop/issues/3509

From the chat:
> I noticed that my iPadOS 1.44 delta chat client offers a server and local device message delete interval of four weeks whereas every other client offers five weeks. Anyone else noticing this?

**Comment by r10s** [comment]
the linked issue is about "disappearing messages", that was already changed at  https://github.com/deltachat/deltachat-ios/pull/2001 and looks like:

<img width=240 src=https://github.com/deltachat/deltachat-ios/assets/9800740/1f5f9aa7-c771-48b7-a0fe-dd074ffb2a49>


the user question is about "delete old message" which is indeed different; was not aware it was changed there as well :)

**Comment by r10s** [comment]
i assume this was closed accidentally. otherwise re-close with a comment

**Comment by zeitschlag** [comment]
Indeed, I didn't look in Settings, but only in Chat-details, my bad.
