### ISSUE TITLE
allow openpgp4fpr scheme links inside webxdc

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#2157]
so iOS users can discover bots and benefit from the [Public Bots Index](https://github.com/deltachat-bot/public-bots) which is also important WRT the new onboarding effort since with chatmail instances, users can not write directly to bots but need to verify them first to be able to write, with this chatmail users will be able to use bots

this is already supported by Delta Chat Desktop and will be supported by Android in https://github.com/deltachat/deltachat-android/pull/3008

**Comment by r10s** [comment]
nb: for testing, ex. write to <mailto:botsindex@nine.testrun.org> and try to click a bot in the list
