### ISSUE TITLE
Alert shows up when scanning QR-Code and going back

### ISSUE THREAD

**Issue by zeitschlag** [deltachat/deltachat-ios#2177]
## Steps to reproduce

1. Open Welcome-screen, i.e. either first start or "Add Profile"
2. "Create new profile" aka go to Instant Onboarding-Screen
3. Tap "Other Chatmail Server"
4. Select one from the website and tap the QR-code so that the Deltachat-app is opened. Technically speaking we replace the entire NavigationStack with a `WelcomeViewController` and a `InstantOnboardingViewController`
5. Go back

Now this alert pop up, that should be there, according to @r10s:

![simulator_screenshot_03759091-FB03-43B5-81AD-5F51A56A9B1D](https://github.com/deltachat/deltachat-ios/assets/2580019/a5caaf1f-8d99-4d8c-8b30-dcbe071fb34f)

It shows up as the `WelcomeViewController` shows an alert in [`viewDidLoad`](https://github.com/deltachat/deltachat-ios/blob/main/deltachat-ios/Controller/AccountSetup/WelcomeViewController.swift#L86-L88) if there's an accountCode (read: QR-code).

**Comment by r10s** [comment]
ftr: it does _not_ happen when really scanning the QR code instead of tapping it
