### ISSUE TITLE
Adaptions to Settings/Signature text 

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#218]
By tapping on Settings -> Signature text, a new view opens that includes both entries 'Your name' and 'Signature text'. Only the latter one should be visible in this context. 
Moreover this Signature text entry should include an expandable multiline textfield because at the moment it is really hard to write an email footer within an about 25 character long single line entry.

**Comment by r10s** [comment]
totally agree with the multi-line issue.

however, i think having name+signature both editable in the same viewcontroller makes  sense. i'd also add the selection of a profile image there (see #153, as on android)

but, of course, the navigation to that viewcontroller may be improved (eg. sth. as on android, or a more clearly named button). but i think for _now_ it is fine and i would not call this a bug :) maybe a ux glitch :)

**Comment by r10s** [comment]
found a nice solution in #221, later on, this should also show the profile image then.

we should keep this issue open until someone makes the signature multiline, however.

**Comment by r10s** [comment]
closing this in favor to the more clear #225
