### ISSUE TITLE
Send vCards

### ISSUE THREAD

**Issue by zeitschlag** [deltachat/deltachat-ios#2186]
- [x] add support for sending vCards (depends on https://github.com/deltachat/deltachat-core-rust/pull/5571)
- [x] display in draft/staging

See #2167.

**Comment by r10s** [comment]
ftr, base class could `GroupMembersViewController`, which is also used for `BlockedContactsViewController`.

apart from the not-matching name, it offers search and probably everything we need for selecting a contact.

**Comment by Hocuri** [comment]
1. after click on "contact" in attachment menu, show a dialog to select _one_ contact
2. Create a message with viewtype VCard
- Steps 3, 4 and 5 can be combined using https://github.com/deltachat/deltachat-core-rust/pull/5677:
  3. get VCard including this contact by calling rpc.makeVcard
  4. save this VCard as temporary file
  5. attach this file to the message like a normal file attachement and set it as a draft. Alternatively, directly send it, staging as a draft can come later.
