### ISSUE TITLE
iOS client instantly crashing with large attachments

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#2210]
Delta Chat version
1.46

Expected behavior

App is working correctly

Actual behavior
iOS app instantly crashes after showing splash screen for a while. Problem can solve by itself after indefinite amount of time (from 10 minutes to 24-36 hours)

Steps to reproduce the problem
0. (To break sender’s side) Enable sending copy to yourself

Send a large video attachment from an Android app via postfix+dovecot server to user at the same server
Open recipient’s iOS app — it crashes
Open sender’s iOS app — it crashes
But it isn’t reproducible every time for both sides: sometimes both clients are broken, sometimes one of the them, sometimes both work correctly.

No logs could be retrieved, because app does not open. Nothing suspicious in the dovecot logs have seen.

originally reported on the forum (as there for more details): https://support.delta.chat/t/ios-client-instantly-crashing-with-large-attachments/3142

**Comment by r10s** [comment]
closing as this cannot be reproduced by anyone. also the thread opener in the forum came back, saying it is not reproducible any longer. the then mentioned "stalled updating" is another thing and maybe related to https://github.com/deltachat/deltachat-core-rust/issues/6108
