### ISSUE TITLE
space between messages are missing

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#224]
in the current dev version, the messages layout is broken under certain circumstances, a picture explains more than thousand words. So see the picture:
![messages_layout_bug](https://user-images.githubusercontent.com/2614900/64171337-b3c23480-ce52-11e9-8f31-a9b78830633f.png)

**Comment by r10s** [comment]
i think, this is closed by https://github.com/deltachat/deltachat-ios/pull/271#pullrequestreview-289995062
