### ISSUE TITLE
share contacts from "contact profile"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2273]
add a share button beside "search" and "mute" or below "send message".

"sharing" here means to select a chat and to stage the vcard

compare https://github.com/deltachat/deltachat-android/pull/3170

**Comment by zeitschlag** [comment]
![2273](https://github.com/user-attachments/assets/89c77d27-35ee-4497-8763-b357cb50d3a3)

Decided to go with an additional cell here as a third button would heavily truncate the email address
