### ISSUE TITLE
tune down "copy to clipboard" from "contact profile"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2274]
remove "copy to clipboard" from primarily visible UI.

instead, show a "copy to clipboard" context menu popup when long-tapping the address

compare https://github.com/deltachat/deltachat-android/pull/3175

**Comment by zeitschlag** [comment]
There's also a `copyToClipboardCell` for Mailing-list it seems. What should be done with that? (Please feel free to just open a new issue.)
