### ISSUE TITLE
Show number of unread messages in Back-button on ChatViewController

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2280]
... if > 0

when Alices chats in "Chat with Bob" for hours, and a new message arrives in "Chat with Claire", Alice won't be aware of Claire's messages until she goes back to the chatlist at some point.

on android, we solved this issue by showing the "normal" notifications in case a message arrives in a foreign chat while being in another chat. this probably requires to track the chat_id in-app (the "Notification Service Extension" (NSE)  is not envolved when the app is in foreground iirc, but not sure) (~~ftr~~ for the record: adding flags to `completionHandler([.badge])` sounds promising)

these additional notification must not be shown when already being in the chatlist (we have the badge counters there) and are also not needed from inside the settings or other screens (either the badge counter abottom is visible - and, usually, one is not that often and for hours in these screens)

if this is not possible at all, an alternative is to show the unread-badges atop of the in-chat back-button

**Comment by zeitschlag** [comment]
If we'd show a TabBar-item indicator, we show the number of unread messages in the back-button of a chat
