### ISSUE TITLE
ios18 beta reported to being crashed

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2281]
we got reports in the user forum that ios18 beta crashes:

> DC iOS test flight version crashes on iOS 18 public beta

> DC iOS test flight build constantly crashes when backgrounded on the latest iOS 18 public beta.  Crash reports submitted

@zeitschlag do you have an option to check that on some device?

**Comment by zeitschlag** [comment]
@r10s No, I don't.

A crashlog would be probably helpful as the Crashes in Xcode Organizer aren't very detailed:

<img width="1296" alt="Screenshot 2024-08-21 at 10 37 52" src="https://github.com/user-attachments/assets/baae740c-3300-45a3-9ec7-79af08b207c0">

"Just doesn't work"

**Comment by r10s** [comment]
the original poster reported on Sep 13th that zhings are fine now:

> iOS 1.46.10 so far so good iOS 18 public beta

so maybe a bug on apple side, or we changed sth without knowing.

still, when ios18 is out, we should try quickly on some devive

**Comment by rinchen** [comment]
De-anonymizing myself so you can tag me directly. 😁 Another day and no crashes on the test flight build. I can't remember the timing of the last crash; there was another beta in there.  Ergo, I can't say for certain if it was Apple or a code fix.  I'll try to report after the official launch tomorrow.  Like me here or in the chat if you don't hear from me by Tuesday EU time.

**Comment by rinchen** [comment]
> I can't say for certain if it was Apple or a code fix

I found the last crash report. It is on the iOS build prior to the one I'm on.

**Comment by rinchen** [comment]
Looks like the build I've been running since last week is the gold master. Since DC has been running fine on the test flight version, we are good to go.

**Comment by rinchen** [comment]
Yet another day working great.  Recommend pushing 1.46.10 to App Store for general use.

**Comment by r10s** [comment]
great, closing this issue now. thanks a lot for reporting and for coming back ❤️
