### ISSUE TITLE
empty messages when quoting a messages and adding a sticker

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2285]
when quoting a message and then selecting a sticker, this results in an empty, _quote-only_ message. this should not exist.

replying with a sticker more times results in _completely_  emtpy messages. this should not exist as well.

https://github.com/user-attachments/assets/a5be9db9-dd79-4063-9c02-5d88076e0a36

it seems a bit unclear, what to do when replying with stickers when a quote is staged 

- android sends a quote+sticker in this case, and clears the quote - but not the text. somehow reasonable

- desktop sends the sticker without the quote, leaving quote and text as is - also reasonable

would be interesting what others, eg. telegram/whatsapp/signal are doing here, cc @adbenitez

**Comment by adbenitez** [comment]
> would be interesting what others, eg. telegram/whatsapp/signal are doing here, cc @adbenitez

Telegram allows to reply to a message with an sticker, just normally by swipe-to-reply and then selecting the sticker, as on DC-android, the behavior of Desktop should be considered a bug/limitation
