### ISSUE TITLE
Update core

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-ios#2289]
This contains important bugfixes (fixes panic in 1.142.8 and failure to connect to some SMTP servers in 1.142.9).

Desktop PR: https://github.com/deltachat/deltachat-desktop/pull/4094
Android issue: https://github.com/deltachat/deltachat-android/issues/3265

TODO: Check for latest release: https://github.com/deltachat/deltachat-core-rust/releases

**Comment by zeitschlag** [comment]
I'll close this as updating the core to the latest version is [part of the Release-process](https://github.com/deltachat/deltachat-ios/blob/main/RELEASE.md).
