### ISSUE TITLE
DC-iOS crashed after starting

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-ios#2301]
Recently DC-iOS crashed shortly after starting.
At first only the DC logo was visible and nothing happened. Then the home screen was displayed again. 
But DC was still in the task manager. After I selected it there, the logo was displayed again and then the home screen. I was able to reproduce this several times. After closing DC in the task manager and restarting the app, the same problem occurred again. Even restarting iOS couldn't solve it. 
Unfortunately, I was unable to save the log because the app would no longer open.
After deleting DC, restarting iOS and then reinstalling DC, the app runs normally again.

iPhone 14
iOS 17.6.1
DC-iOS 1.46.9

**Comment by rinchen** [comment]
This is resolved in my testing of 1.46.10 in test flight. See #2281

**Comment by r10s** [comment]
thanks for coming back! then close this issue, if the problem hallens again, please open a new one
