### ISSUE TITLE
tweak "large titles"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#232]
currently, the "large titles" are a mess.

i think, we should default to "small titles", esp. for deep nested viewcontrollers and for the login screen this is much better (and is on pair eg. with the system settings)

as the default also seems to be small titles, we can remove most of the preferLargeTitle and largeTitleDisplayMode settings - in fact, i would restart by removeing all of them.

after that, _only_ the view controllers directly reachable from the main screen - qr-code, contact-requests, chatlist and settings - should get the ability to enlarge their titles. `.automatic` makes this smart in the way the titles are only enlarged if the previous title was enlarged as well. also all of these screen start the list atop (which is not true eg. for the chatview)

should be targeted when #230 and #229 are done.

resources:

https://developer.apple.com/documentation/uikit/uinavigationbar/2908999-preferslargetitles
https://developer.apple.com/documentation/uikit/uinavigationitem/2909056-largetitledisplaymode

**Comment by cyBerta** [comment]
> also all of these screen start the list atop (which is not true eg. for the chatview)
@r10s Shall I alter the chat requests view controller so that always the first item / the top of the list is visible?

**Comment by r10s** [comment]
> @r10s Shall I alter the chat requests view controller so that always the first item / the top of the list is visible?

this also came into my mind. however, no, i would not do that. so, for now, seems as if a little mess stays.

have to think about a more prober solution ...

**Comment by cyBerta** [comment]
Another solution to the problem: https://stackoverflow.com/questions/46506401/how-to-turn-off-adjusting-large-titles-by-uitableview-in-ios-11?answertab=votes#tab-to

**Comment by r10s** [comment]
yeah, or as on irc, just go for small titles everywhere.

**Comment by nayooti** [comment]
I believe these are set
