### ISSUE TITLE
clear chat: DC always indicates a wrong number of messages

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-ios#2324]
### Expected behavior:

When clearing a chat history, DC displays the correct number of messages in the security prompt, which will be deleted after confirmation.

### Actual behavior:

When clearing a chat history, DC always displays one message too much in the security prompt.

### Steps to reproduce the problem:

- Start a new chat
- Write and send some messages, 
- Clear chat history

iOS 18.01
iPhone 14
DC-iOS 1.46.10

**Comment by r10s** [comment]
off by one :)

**Comment by r10s** [comment]
good catch @Raiden-GH! i did a fix at #2325
