### ISSUE TITLE
contact search erroneous

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#233]
the current contact search is just a filter about the whole list, done in the ui (the core is not used for searching contacts here)

this is fine for now, however, the search is not incremental as expected, but or-searches for every letter entered. so "hans" searches for all contacts containing "h" "a" "n" or "s"

**Comment by cyBerta** [comment]
it is important to mention that the order of the letters matters in the search. 
searching for 'hans' will match for `0h1an2s` but not for `anhs` or `anstrahlen` which also includes 'h', 'a', 'n' and 's'

For me that doesn't feel like a bug but rather like a different search strategy that is a little less strict. Anyway, I'll change it to an AND condition.

**Comment by r10s** [comment]
> Anyway, I'll change it to an AND condition.

i do not think that a simple switch to AND is sufficient. at least it would be still weird and unexpected.

assume you have the following contacts:

al
adam
berta
claudi
david
detlef

a search for "al" would also find "claudi" when just switching to AND (with OR _all_ are found btw)

i think the search should just be a substring-match - eg. when entering "al" only "al" is found. when entering "da", "adam" and "david" will be found. 

this would also match the well-known pattern "the more letters are entered, the less matches will be found"

**Comment by nayooti** [comment]
Following all the development. Great seeing you guys being so active.

Btw:
For the contact search there is a simple unit test setup for convenience. You’ll find it `deltachat-iosTests.swift` in case your interested.

**Comment by cyBerta** [comment]
> i think the search should just be a substring-match - eg. when entering "al" only "al" is found. when entering "da", "adam" and "david" will be found.

agreed. This is what I'm working on right now

**Comment by cyBerta** [comment]
Unfortunately I've found another bug with the current search. If you got your list of contacts:

al
adam
berta
claudi
david
detlef

and search for 'cla' 'claudi' will be shown. But if you click on 'claudi', the chat with 'al' opens (the first initial entry of the list). So recycling the list items doesn't work properly, I guess

**Comment by cyBerta** [comment]
> For the contact search there is a simple unit test setup for convenience. You’ll find it `deltachat-iosTests.swift` in case your interested.

Cool, thanks for the hint!
