### ISSUE TITLE
ContactRequestBar missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2356]
when receiving a message from someone not  being in contact before, the chat is shown as a so called "Contact Request" - that means, you first have to accept the chat, then you can write etc. 

Acceptance or Blocking is done using `ChatContactRequestBar`, that is shown _instead_ of the message input field.

however, probably as a side effect of #2315 or subsequent changes,  the `ChatContactRequestBar` is never shown and the chat looks like:

<img width=320 src=https://github.com/user-attachments/assets/b47c5ec2-5ecd-4c9e-b39e-32404e7f6ee4>

note, that the ContactRequestBar is also use to show a warning if the "guaranteed e2ee" is broken - also then, the user must not type a message, but deal with the state first.

cc @Amzd

**Comment by r10s** [comment]
@Amzd i played around a bit and came over https://github.com/deltachat/deltachat-ios/pull/2357

**Comment by Amzd** [comment]
You can also see the issue of no bottom safe area when missing the inputAccessoryView in that screenshot. I'll fix that coming weekend.

**Comment by r10s** [comment]
closed by #2357
