### ISSUE TITLE
After exporting a file from the chat, the input bar is no longer displayed.

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-ios#2363]
## Expected behavior:

After exporting a file in the chat history, the chat is displayed with the input bar.

## Actual behavior:

After exporting a file in the chat history, the chat is displayed without the input bar.
By reselecting the chat it will appear again.

## Steps to reproduce the problem:

- Select file in the chat history
- Share
- Save to files

iOS 18.1
iPhone 14
DC-iOS 1.46.10

**Comment by Amzd** [comment]
Fixed in latest TestFlight but there the message input bar is shown while share sheet is shown which a new issue.

**Comment by r10s** [comment]
closing, there is also a new testflight, and a new release probably soon (1.48.4); please reopen, ideally with additional information, if the issue persists

**Comment by r10s** [comment]
no problem, thanks a lot for coming back, for testing and reporting ❤️
