### ISSUE TITLE
new two-finger multi-select results in random background color

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2364]
when using the new  two-finger multi-select gesture from https://github.com/deltachat/deltachat-ios/pull/2349 , the background is often grey, but sometimes white.

it happens when scrolling around, did not find a way to reproduce it reliably. 

here an example - notice at the end, some checks have a grey background, some a white background:

https://github.com/user-attachments/assets/edddccbd-c9aa-4ab1-9c1a-393161e07929

i first thought, this is an issue because of unset reuse variables (so the random would result from either pined or non-pinned being reused) but that is not true (i tried by using other green/yellow for pinned/unpinned - still, the background was sometimes grey, sometimes not)

**Comment by Amzd** [comment]
Can probably be fixed with a `cell.selectionStyle = .none` and setting a custom background color when selected?

**Comment by r10s** [comment]
thanks for the hint! setting a background color to `selectedBackgroundView` did the trick. changing `selectionStyle` did not help or even prevent the checkboxes from working, at least in combination with `selectedBackgroundView`, but i also did not invetigate too deep as we have sth nicely working with #2365 now
