### ISSUE TITLE
Proxy: Make Proxy-Screen accessible from Chat-list

### ISSUE THREAD

**Issue by zeitschlag** [deltachat/deltachat-ios#2383]
- [x] Add a shield to Chat-list's NavigationBar if proxy is enabled (and a `shield.slash` if it's broken, not enabled, ...)
- [x] Show Proxy-Screen when tapping on that shield
- [x] `if iOS 13+ use SF Symbol else use Text Proxy`

**Comment by r10s** [comment]
> Add a shield to Chat-list's NavigationBar if proxy is enabled (and a shield.slash if it's broken, not enabled, ...)

ftr, this is what [android is doing](https://github.com/deltachat/deltachat-android/blob/main/src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java#L366) - as well as https://github.com/deltachat/deltachat-ios/pull/2391 at a first glance:

- if `proxy_url` is not empty and we're not in relay-mode, show a button, independent of `proxy_enabled`
- show button as disabled (so, shield.slash) in case `proxy_enabled` is false

connectivity does not play a role for the button - that seems to be fine, as the "connected" state is shown just beside.
