### ISSUE TITLE
core chat meta messages are not displayed correctly

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#245]
Either this issue results from latest refactorings in rust-core or changes with the string sources (e.g. PR #234)

see attached picture:

![core_bug_translations](https://user-images.githubusercontent.com/2614900/64608457-fba10880-d3ca-11e9-857d-8b6b0e79b814.png)

**Comment by cyBerta** [comment]
seems to be fixed on core side

**Comment by r10s** [comment]
yip, this was fixed by https://github.com/deltachat/deltachat-core-rust/pull/499
