### ISSUE TITLE
make "device owner verification string" translatable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2463]
the string "Delta Chat uses Face ID to protect backup creation or settings up a second device." is defined in `Info.plist` and is shown when the user is asked for granting access to "Face ID". 

it is fine, if the user does not grant, so there is no need for nudging or so, but we should make the string translatable - and fix the typo ("setting up", not "settings up")

translation is done by adding the corresponding string to the android repo, see the other info.plist strings to get an idea

**Comment by zeitschlag** [comment]
I'm confused: Don't we already have this in #2380?

**Comment by r10s** [comment]
indeed, i should just do it :)
