### ISSUE TITLE
reliably update contact requests

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#261]
Atm. the incoming contact requests are not always shown in the contact requests list. I've tested with an email-address that is not connected to a dc client and doesn't support autocrypt.

**Comment by r10s** [comment]
i think also the chatview and the chatlist is not always updated in a reliable way, not 100% sure, however.

**Comment by r10s** [comment]
the contact-requests are there, however, at the _end_ of this list - which is close to not being there when having some dozens of chats :)
