### ISSUE TITLE
tweak Contact Requests in Chat List

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#262]
For some reason, I've managed to get an entry `Contact Request` in the Chatlist. It disappeared after switching between the tabs again. Needs more debugging...

**Comment by r10s** [comment]
in generally, this is correct. fresh contact requests from other delta chat clients pop up in the chatlist. when viewing them (probably by switching to  the "contact request" tab), they are no longer fresh and disapear.

on android, we use a slightly different background (grey), we should also do that for ios. on a click, the user shoudl get the startChat/cancel/never question.

but i am just wondering why the contact request is at the bottom of the chatlist - it should be at the top. but this might also be a bug in the rust core; i would not care about that here for now.

**Comment by cyBerta** [comment]
I figured out that the contact request item only disappears from the chat list if you click on that list item. So it seems to work as intended.

**Comment by cyBerta** [comment]
The 'Contact requests' chat opened from Chats -> List Item 'Contact Requests' shows an input field. Sending any message to the contact requests chat has no effect. The input field should be hidden for contact requests.

![Screen Shot 2019-09-17 at 11 51 44](https://user-images.githubusercontent.com/2614900/65031774-2ac2f700-d942-11e9-932d-4ace9f2876f4.png)

**Comment by r10s** [comment]
a click on chatlist->contact request item should not open a chat but show the quesiton "start chat with ..." as on android.

for the contact request view reachable from the tab-bar, the input field is already hidden, so this is already fine.
