### ISSUE TITLE
share via DeltaChat

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#263]
Deltachat is not as in option in the native share menu. Share with DeltaChat should be an option there. (Example: sharing picture from gallery app)

(experienced on the current testflight version)

**Comment by r10s** [comment]
for the record, there are some first attempts at https://github.com/deltachat/deltachat-ios/pull/475 , we will pick up this later again, for now, we go for some more low hanging fruits :)

**Comment by r10s** [comment]
closing this in favor to the more concrete issues https://github.com/deltachat/deltachat-ios/issues?q=label%3A%22share+extension%22+
