### ISSUE TITLE
Smtp on iOS delta chat beta app Cuban nauta email

### ISSUE THREAD

**Issue by avivador** [deltachat/deltachat-ios#287]
- Device:
- iOS version: 12.4.1
- Delta Chat version: the last beta
- Expected behavior: just chat
- Actual behavior: smtp doesn’t work
- Steps to reproduce the problem:
I am using an android emulator so installed delta chat and export the account 
I opened the iOS beta delta chat and import the file. I saw the app but downs work. 
I wrote in avance configuration. imap.nauta.cu port 143 and smtp.nauta.cu port 26 (I realized the check mark was port 465). 
Right now I saw how the imap works but no smtp 
- Screenshots:
![DC1B9906-E217-4087-B91F-3E663BD9248A](https://user-images.githubusercontent.com/55469763/65350173-1f2a3700-dbb3-11e9-9bb2-b0bd1e6cf64c.jpeg)
![B340E74B-6A52-4442-A102-6C4A42246C07](https://user-images.githubusercontent.com/55469763/65350174-1f2a3700-dbb3-11e9-9b44-252fb6e5978c.png)
![12D1687E-485A-4908-B562-0BC43075F3AE](https://user-images.githubusercontent.com/55469763/65350175-1fc2cd80-dbb3-11e9-94fe-bf8f89bd8513.png)

- Logs:
Device model: iPhone 6s
System version: iOS 12.4.1
Console output:
2019-09-20 14:05:09.523 deltachat-ios[617:95530] <CATransformLayer: 0x282dc7ee0> - changing property masksToBounds in transform-only layer, will have no effect
2019-09-20 14:05:09.536 deltachat-ios[617:95530] <CATransformLayer: 0x282dc37e0> - changing property masksToBounds in transform-only layer, will have no effect
14:05:09.259 💙 INFO AppDelegate.application():66 - launching
14:05:09.339 💙 INFO AppDelegate.open():144 - open: /var/mobile/Containers/Data/Application/4987E45E-EEEC-4D84-8699-4E16EDB26391/Library/messenger.db
14:05:09.339 💙 INFO events.callbackSwift():27 - event: Opened "/var/mobile/Containers/Data/Application/4987E45E-EEEC-4D84-8699-4E16EDB26391/Library/messenger.db".
0
14:05:09.450 💙 INFO AppDelegate.start():171 - ---- start ----
14:05:09.455 💙 INFO AppDelegate.getCoreInfo():42 - deltachat_core_version=v1.0.0-alpha.1
sqlite_version=3.27.2
sqlite_thread_safe=1
arch=64
number_of_chats=2
number_of_chat_messages=44
messages_in_contact_requests=0
number_of_contacts=319
database_dir=/var/mobile/Containers/Data/Application/4987E45E-EEEC-4D84-8699-4E16EDB26391/Library/messenger.db
database_version=55
blobdir=/var/mobile/Containers/Data/Application/4987E45E-EEEC-4D84-8699-4E16EDB26391/Library/messenger.db-blobs
display_name=0
is_configured=1
entered_account_settings=maikeleduardo.pelaez@nauta.cu 0:***:0:143 0:0:0:0 IMAP_PLAIN 
used_account_settings=maikeleduardo.pelaez@nauta.cu maikeleduardo.pelaez@nauta.cu:***:imap.nauta.cu:143 maikeleduardo.pelaez@nauta.cu:***:smtp.nauta.cu:465 AUTH_NORMAL IMAP_PLAIN SMTP_SSL 
inbox_watch=1
sentbox_watch=1
mvbox_watch=1
mvbox_move=1
folders_configured=3
configured_sentbox_folder=Sent
configured_mvbox_folder=DeltaChat
mdns_enabled=1
e2ee_enabled=1
private_key_count=1
public_key_count=3
fingerprint=01FCB7BA84271A4F7114DFC9A71ED9D005BA5985
level=awesome
14:05:09.467 💙 INFO AppDelegate.registerForPushNotifications():285 - permission granted: true
14:05:09.470 💙 INFO AppDelegate.getNotificationSettings():293 - Notification settings: <UNNotificationSettings: 0x2806e5b90; authorizationStatus: Authorized, notificationCenterSetting: Enabled, soundSetting: Enabled, badgeSetting: Enabled, lockScreenSetting: Enabled, carPlaySetting: NotSupported, criticalAlertSetting: NotSupported, alertSetting: Enabled, alertStyle: Banner, providesAppNotificationSettings: No>
14:05:09.576 💙 INFO WiFi.reachabilityChanged():241 - network: reachable
14:05:09.576 💙 INFO events.callbackSwift():27 - event: Interrupting SMTP-idle...
14:05:09.576 💙 INFO events.callbackSwift():27 - event: Interrupting IMAP-IDLE...
14:05:09.576 💙 INFO events.callbackSwift():27 - event: Interrupting MVBOX-IDLE...
14:05:09.576 💙 INFO events.callbackSwift():27 - event: Interrupting SENTBOX-IDLE...
14:05:09.820 💙 INFO AppDelegate.registerBackgroundTask():264 - background task registered
14:05:09.820 💙 INFO events.callbackSwift():27 - event: SMTP-jobs started...
14:05:09.820 💙 INFO events.callbackSwift():27 - event: SMTP-job #4, action 5901 started...
14:05:09.820 💛 WARNING events.callbackSwift():82 - network: SMTP-LOGIN as maikeleduardo.pelaez@nauta.cu ok
14:05:10.204 💛 WARNING events.callbackSwift():30 - event: SMTP failed to send message: connection refused
14:05:10.229 💙 INFO AppDelegate.registerBackgroundTask():264 - background task registered
14:05:10.230 💙 INFO events.callbackSwift():27 - event: INBOX-jobs started...
14:05:10.325 💙 INFO events.callbackSwift():27 - event: INBOX-jobs ended.
14:05:10.621 💛 WARNING events.callbackSwift():30 - event: SMTP failed to send message: connection refused
14:05:10.629 💙 INFO events.callbackSwift():27 - event: SMTP-job #4 not succeeded on try #7, retry in ADD_TIME+2998 (in 2457 seconds).
14:05:10.630 💙 INFO events.callbackSwift():27 - event: SMTP-jobs ended.
14:05:10.630 💙 INFO events.callbackSwift():27 - event: SMTP-idle started...
shouldSelect
14:05:11.612 💛 WARNING events.callbackSwift():82 - network: IMAP-LOGIN as maikeleduardo.pelaez@nauta.cu ok
14:05:11.612 💙 INFO events.callbackSwift():27 - event: IMAP-capabilities: LITERAL+ MOVE IMAP4rev1 LIST-STATUS QUOTA THREAD=REFS ENABLE NAMESPACE SASL-IR SORT SEARCHRES THREAD=ORDEREDSUBJECT CATENATE CHILDREN I18NLEVEL=1 ESEARCH MULTIAPPEND BINARY LOGIN-REFERRALS ID IDLE UIDPLUS SORT=DISPLAY QRESYNC CONTEXT=SEARCH UNSELECT WITHIN URL-PARTIAL ESORT SPECIAL-USE CONDSTORE THREAD=REFERENCES LIST-EXTENDED
14:05:11.613 💙 INFO events.callbackSwift():27 - event: INBOX-fetch started...
14:05:11.617 💛 WARNING events.callbackSwift():82 - network: IMAP-LOGIN as maikeleduardo.pelaez@nauta.cu ok
14:05:11.617 💙 INFO events.callbackSwift():27 - event: IMAP-capabilities: MOVE ESEARCH CONTEXT=SEARCH THREAD=REFS QUOTA CATENATE NAMESPACE MULTIAPPEND I18NLEVEL=1 IDLE CONDSTORE UIDPLUS SORT LOGIN-REFERRALS ID URL-PARTIAL UNSELECT LIST-EXTENDED WITHIN SORT=DISPLAY SPECIAL-USE LIST-STATUS IMAP4rev1 THREAD=REFERENCES SASL-IR ENABLE LITERAL+ THREAD=ORDEREDSUBJECT SEARCHRES CHILDREN QRESYNC BINARY ESORT
14:05:11.617 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch started...
14:05:11.617 💛 WARNING events.callbackSwift():82 - network: IMAP-LOGIN as maikeleduardo.pelaez@nauta.cu ok
14:05:11.617 💙 INFO events.callbackSwift():27 - event: IMAP-capabilities: ID QRESYNC MULTIAPPEND SASL-IR UNSELECT LITERAL+ CONDSTORE I18NLEVEL=1 UIDPLUS NAMESPACE SEARCHRES SPECIAL-USE BINARY QUOTA ESORT IMAP4rev1 IDLE LOGIN-REFERRALS CONTEXT=SEARCH MOVE SORT THREAD=REFS CATENATE LIST-EXTENDED ESEARCH CHILDREN LIST-STATUS THREAD=ORDEREDSUBJECT WITHIN ENABLE THREAD=REFERENCES URL-PARTIAL SORT=DISPLAY
14:05:11.618 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch started...
14:05:12.761 💙 INFO events.callbackSwift():27 - event: 0 mails read from "Sent".
14:05:12.763 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch done in 228.683 ms.
14:05:12.763 💙 INFO events.callbackSwift():27 - event: 0 mails read from "DeltaChat".
14:05:12.763 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch done in 228.470 ms.
14:05:12.763 💙 INFO events.callbackSwift():27 - event: SENTBOX-IDLE will not be started as it was interrupted while not ideling.
14:05:12.764 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch started...
14:05:12.764 💙 INFO events.callbackSwift():27 - event: 0 mails read from "INBOX".
14:05:12.765 💙 INFO events.callbackSwift():27 - event: INBOX-fetch done in 234 ms.
14:05:12.765 💙 INFO events.callbackSwift():27 - event: INBOX-IDLE started...
14:05:12.765 💙 INFO events.callbackSwift():27 - event: MVBOX-IDLE will not be started as it was interrupted while not ideling.
14:05:12.765 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch started...
14:05:13.090 💙 INFO events.callbackSwift():27 - event: 0 mails read from "Sent".
14:05:13.090 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch done in 6.414 ms.
14:05:13.090 💙 INFO events.callbackSwift():27 - event: SENTBOX-IDLE started...
14:05:13.090 💙 INFO events.callbackSwift():27 - event: 0 mails read from "DeltaChat".
14:05:13.090 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch done in 6.217 ms.
14:05:13.090 💙 INFO events.callbackSwift():27 - event: MVBOX-IDLE started...
14:05:48.197 💙 INFO events.callbackSwift():27 - event: IMAP-IDLE has data.
14:05:48.198 💙 INFO events.callbackSwift():27 - event: IMAP-IDLE has data.
14:05:48.198 💙 INFO events.callbackSwift():27 - event: MVBOX-IDLE ended.
14:05:48.198 💙 INFO events.callbackSwift():27 - event: SENTBOX-IDLE ended.
14:05:48.199 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch started...
14:05:48.199 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch started...
14:05:48.218 💙 INFO events.callbackSwift():27 - event: 0 mails read from "DeltaChat".
14:05:48.218 💙 INFO events.callbackSwift():27 - event: MVBOX-fetch done in 5.338 ms.
14:05:48.219 💙 INFO events.callbackSwift():27 - event: MVBOX-IDLE started...
14:05:48.219 💙 INFO events.callbackSwift():27 - event: 0 mails read from "Sent".
14:05:48.220 💙 INFO events.callbackSwift():27 - event: SENTBOX-fetch done in 6.459 ms.
14:05:48.220 💙 INFO events.callbackSwift():27 - event: SENTBOX-IDLE started...
14:05:48.922 💙 INFO events.callbackSwift():27 - event: IMAP-IDLE has data.
14:05:48.923 💙 INFO events.callbackSwift():27 - event: INBOX-IDLE ended.
14:05:48.923 💙 INFO events.callbackSwift():27 - event: INBOX-jobs started...
14:05:48.924 💙 INFO events.callbac

**Comment by avivador** [comment]
It is important to say. A Cuban nauta account needs to configure security off and the port are 25 for smtp and 143 for imap. It is imposible right now to do this using the app.

**Comment by r10s** [comment]
thanks for filing an detauled issue.

the ios version is pretty beta.
if the account has worked on android, for the upcoming version, it is pretty probable that it will work with ios as well as they share the same rust-core.

so, this is probably not really an ios problem, although the port 26/25/465 looks confusing. _we should check out here, if port 25 works at all._ maybe the core does not get the data from the ui input (but on backup-import otoh, the ui is not really involved)
but, in general, i would wait for the next textflight release before diving into deeper details.

@adbenitez can you confirm that the rust-core generally works with nauta.cu? iirc, this was the case, but not sure :)

**Comment by avivador** [comment]
The trouble is not way to configure the right parameters. On the other hand I am sure the Android app is working and I exported the account very well. I think iOS app has the issue.

**Comment by r10s** [comment]
> The trouble is not way to configure the right parameters.

okay, so, the input field is not working as expected?

**Comment by cyBerta** [comment]
related: https://github.com/deltachat/deltachat-ios/issues/348
changes are currently not taken into account if the user doesn't click on login. The login button is not always enabled after a change though.

**Comment by r10s** [comment]
> After trying to connect with a misconfigured port 97, the core lib tries known ports and uses them. The app doesn't reflect that in the settings (eg port 97 is still visible in the settings instead of port 587)

yip, but this will probably be changed in the core at some point (that, if a port is set, no other ports are tested at all)

**Comment by cyBerta** [comment]
Shall I open a ticket for it? Or is "at some point" a rather long term plan :)?

**Comment by r10s** [comment]
if there is no issue, feel free to open one. but i am sure, we won't forget that, it is popping up over and over :)
