### ISSUE TITLE
remove Untranslated.stringsdict?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#289]
what are the Untranslated.stringsdict files for? they are placed in all locale directories and contain a german plurals form for all languages.

can the files be removed?

when adding a new language using Xcode, the files are not created.

@cyBerta do you have some more information about this?

i've just added hungarian and japanese and this seems to work without these files.

**Comment by cyBerta** [comment]
This should not have been added. But there's still an unfinished part, which I would consider as low prio: There's no untranslated.stringsdict file you can use to add new plural strings that are not yet in the android repository, similar to untranslated.xml
