### ISSUE TITLE
(pre)compile deltachat-ios directly from the deltachat-android java codebase?

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-ios#3]
Maybe it is quite easier (less work to setup and maintain) to build deltachat for iOS directly from the java code base by using an ahead of time compiler?:

http://robovm.mobidevelop.com/
https://github.com/MobiVM/robovm/wiki/Developer-Guide

Other project:
https://software.intel.com/en-us/multi-os-engine
https://discuss.multi-os-engine.org/t/thoughts-on-robovm-vs-moe/858/7

**Comment by r10s** [comment]
i think the UI on iOS is too different from Android to take real advantages of this approach - and the non-GUI-parts are already ported using the C-backend, however, i am no iOS expert - maybe @jonasreinsch has a more qualified opinion on this.

**Comment by testbird** [comment]
OK, I can't tell, only saw https://github.com/MobiVM/robovm/wiki/Developer-Guide has a section "XCode InterfaceBuilder integration"

**Comment by testbird** [comment]
Maybe helpful https://dkimitsa.github.io/2017/12/12/robovm-now-linux-windows/

Also, it seems libgdx, the project for which the robovm fork is maintained even contains instructions to deploy to desktops (win/mac/linux) and  web:  https://github.com/libgdx/libgdx/wiki/Deploying-your-application
