### ISSUE TITLE
chat view not updated on failed messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#315]
when sending a message that fails, the chat view is not update.

re-entering the chat view shows the failed message.

**Comment by cyBerta** [comment]
how do you reproduce that issue. The seems to be very "robust" wrt. misconfiguring ports after the initial setup. Also turning on Airplane mode and waiting for a long time didn't result in any timeout. The message keeps showing pending.

**Comment by r10s** [comment]
yip, in fact, these failures are not easy to reproduce, i got them some weeks ago as "encryption unexpected unavailable" or so :)
