### ISSUE TITLE
Add options to configure certificate checks

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-ios#322]
Options `imap_certificate_checks` and `smtp_certificate_checks` were added to the Rust core in deltachat/deltachat-core-rust#647

A way to configure them from the GUI is needed.

**Comment by r10s** [comment]
> A way to configure them from the GUI is needed.

but the default is still "accept everything"?

**Comment by link2xt** [comment]
Default is "automatic" which means "accept everything" for now but that is going to change in the future.

**Comment by r10s** [comment]
as for desktop and android, we'll use one control for both settings.
