### ISSUE TITLE
Need more helpful error messages during onboarding

### ISSUE THREAD

**Issue by trosel** [deltachat/deltachat-ios#328]
- Device: iPhone 8 plus
- iOS version: Latest
- Delta Chat version: Latest
- Expected behavior: 
  - Log in, or get an error message that tells me that I need to change some email settings in order for it to work.
- Actual behavior: Receive bizarre error messages. No clear fixes that I can provide. User can only just close the app and give up on it.
- Steps to reproduce the problem:  

Do not change any app advanced settings or default email settings for these providers. Just simply enter your emails and passwords.

- Screenshots:

Here is the error I got when I tried my iCloud email:
![icloud](https://user-images.githubusercontent.com/1299322/66396459-cecf1980-e9a7-11e9-88ed-aca5119e9413.jpg)

Here is the error I got when I tried my Gmail email:
![gmail](https://user-images.githubusercontent.com/1299322/66396478-d989ae80-e9a7-11e9-994b-6f13bcb98f1f.jpg)

**Comment by hpk42** [comment]
thanks for reporting, we'll look into it!

**Comment by r10s** [comment]
yip, these error messages come from core when trying to parse xml data from an 404-not-found-page (or even a soft-404-errors that is reported from the server as 200-okay).

but also not sure of ios really reports the "last error, top-level-error", see https://github.com/deltachat/deltachat-ios/issues/12

**Comment by r10s** [comment]
(the "bug (critical)" label is not really used on ios in general and not for priorization in special, not sure where it comes from. i removed the label completely)
