### ISSUE TITLE
show forwarded messages as such

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#329]
use dc_msg_is_fowarded() to check if a message is a forwarded message.

later on, we can also implement forwarding, however, this is less urgent - and more complicated :)

**Comment by cyBerta** [comment]
I would like to do that

**Comment by r10s** [comment]
great!

**Comment by cyBerta** [comment]
related PR https://github.com/deltachat/deltachat-ios/pull/349.

**Comment by cyBerta** [comment]
related core bug: https://github.com/deltachat/deltachat-core-rust/issues/724
