### ISSUE TITLE
tweak qr-code view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#335]
- add a "segmented control" with two items, show+scan, if possible, in the [blue flavor](https://www.ioscreator.com/tutorials/segmented-control-ios-tutorial)
- add option two swipe between the tabs, if possible
- default to show
- remember the last selected segment on re-entering

this is my rough idea:

<img width=380 src=https://user-images.githubusercontent.com/9800740/78990726-7ab01800-7b37-11ea-956c-d0b5ee776813.png>

**Comment by cyBerta** [comment]
>     * add two tabs, scan+show

in the main tabview?

**Comment by r10s** [comment]
no, the main tab-view shall stay as it is.

i am thinking more of a ["segmented control"](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/) above the qr-code (where the avatar and the name is now; they can go away)

bu we should do a little a/v before starting on this topic.

**Comment by r10s** [comment]
we'll target this later, for now https://github.com/deltachat/deltachat-ios/issues/436 is sufficient

**Comment by r10s** [comment]
reopened and refined the description, cc @nayooti
