### ISSUE TITLE
Delta Chat crashes in the chat creation window

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#339]
Hello @r10s,

You know that I'm blind and using VoiceOver. Today, I've updated Delta Chat. It  crashes when clicking Create button and swiping right.

**Comment by r10s** [comment]
thanks for reporting!
in fact, the entries "new contact" and "new group" allow swiping where they should not; they seem to access the data from the contact list below, a crash is easily imaginable, eg. when there are <2 contacts.
