### ISSUE TITLE
hang after terminating and reopening

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#342]
if the app is terminated (by swiping away from the chatlist) and opened quickly again, there is a hang of about 10 seconds before the app is restarted.

i think this is because the app was not really terminated completely, dc_close() cannot finish as the threads are not stopped gracefully.

https://github.com/deltachat/deltachat-ios/issues/100#issuecomment-536336197 gives some more information

compared to other bugs, this one is not that annoying and has a low priority. i think the threads will be refactored anyway sooner or later.

**Comment by flub** [comment]
Is this a (partial) duplicate of #651?  Can it be merged there as it proposes some debugging to get us a bit closer to an answer?

**Comment by r10s** [comment]
yip, this is a partial duplicate of https://github.com/deltachat/deltachat-core-rust/issues/651 ,  however, this issue is more about things that can be done better in ios eg. trying to terminate the threads before calling dc_close()

however, as said, the larget issue was the dc_maybe_network() thingie that causes the app to halt for seconds up to minutes.

**Comment by r10s** [comment]
just no longer true, there seems to be some changes in the core.
