### ISSUE TITLE
disable underlining of words that describe a date or a location

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#347]
currently words as "here", "morning" and so on are underlined an link to the calendar or whatever.

this is more irritating than helping, in many contexts, this does not really make sense, esp. when word of other languages seems are underlined ("hier"="here" in german, "hier"="yesterday" in french)

underlining links seems to be sufficient.

**Comment by cyBerta** [comment]
similar to that: currently you will be routed to the default emailing app if you click on a mail address in the chat view. I would like to disable this behavior as a first step.

 As a second step it would be nice to open a action sheet asking to chat with the contact. On tapping Start Chat, the corresponding chat opens or a new one will be generated.
@r10s would it be fine to implement it? Should not take long.

**Comment by r10s** [comment]
@cyBerta as discussed on irc: sounds good!
