### ISSUE TITLE
fix adding members to existing group

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#352]
it seems it is currently not possible to really add members to an existing group

- instead of the "reset" button, there should be a "ok" button in the upper right corner
- a "cancel" button in the upper left corner
- "add contact" -> "ok" should go back to the group-info directly

**Comment by cyBerta** [comment]
I've tested it, and it works for me. Did you have bad internet connection? If you press reset, it's resetting all changes (resetting newly selected contacts) and if you go back to the GroupDetailViewController the selected contacts get added using 
```
for contactId in selectedContactIds {
            dc_add_contact_to_chat(mailboxPointer, UInt32(chatId), UInt32(contactId))
        }
```

**Comment by cyBerta** [comment]
But I can change the labels of the upper left and right buttons.

**Comment by cyBerta** [comment]
It means also the behavior will change: cancel will close the screen without changes (contrary to reset), ok will close the view controller and save the changes

**Comment by r10s** [comment]
> I've tested it, and it works for me. Did you have bad internet connection?

this should not be affected by the internet connection. dc_add_contact_to_chat() works even when offline.

> It means also the behavior will change: cancel will close the screen without changes (contrary to reset), ok will close the view controller and save the changes

yip, that would be better. as a rule of thumb, also on ios, upper-left-corner=back/cancel upper-right-corner=save/ok. only if there is nothing in the upper-right-corner, the "back" in the upper left corner save (typically, things are already saved instantly in this case)

as real messages are sent out by dc_add_contact_to_chat(), this should be called on clicking save/ok only. a cancel should not do anything. dc_remove_contact_to_chat() is not needed for the whole functionality.
