### ISSUE TITLE
show number of unread messages in chatlist

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#358]
by https://github.com/deltachat/deltachat-ios/issues/344 we have now the number of total unread messages on the app icon - however, when opening the app, there is no hint, where the unread messages are.

- we should add a unread counter at the place where the checkmarks are for outgoing messages (this is mutual exclusive - either the last message is outgoing and there are not unread messages therefore of the last message is incoming and there may be unread messages)  
on android, we show the unread messages in a green badge, however, as these badges are red on ios, maybe we should prefer this color. but i do not have a string opinion on that.

- when on this, maybe also show the title in bold, and when changing this, maybe also fix the color for the darkmode (this would target #163 then)

**Comment by cyBerta** [comment]
I would like to fix the dark mode issue separately because I would like to implement dark mode as a color-wise not a component-wise feature (with each light mode color a ´a dark mode counterpart color can be defined)

**Comment by r10s** [comment]
> I would like to fix the dark mode issue separately

sure :)
