### ISSUE TITLE
Chat message menu item 'dismiss' doesn't work as expected

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#365]
In the contact requests view it is possible to do a long-press on a message.
The opening menu contains an entry "Dismiss". If you tap on it, there's no visible change. Internally, this action marks a message as noticed. 

From a users point of view, the message should disappear from the contact request list.

**Comment by r10s** [comment]
we should just remove the dismiss-entry.

deletion is available by the normal "delete" from #181 

so, for contact requests there are only "block contact" and "start chat" as special options.
