### ISSUE TITLE
contact requests broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#375]
currently, there is a sticky contact request (a normal mail) that is not discarded with 'not now'

- iirc 'not now' shall move the contact request away, without any action - is marknoticed_contact() working?
- swiping a contact request show the action for a chat, i think both are not needed

**Comment by r10s** [comment]
seems to be a core problem, on android not-now is also broken

**Comment by hpk42** [comment]
can you replicate via repl?  Or tell the steps so we could put it
into a python test?

**Comment by r10s** [comment]
i will check this out soon. beta.5 does not solve the problem, but i think it is core-related as it appeared on android+ios at the same time.

**Comment by r10s** [comment]
oh: and a click on "start chat" crashes ios - on android nothing happens :) i'll keep investigating ...
