### ISSUE TITLE
add option to attach files

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#376]
the option should pop up in the paper-click-menu, together with "Camera", "Gallery" etc.

i think there is a system view where the user can select the things to send, the selection just goes to [dc_msg_set_file()](https://c.delta.chat/classdc__msg__t.html#ae3d4b2a4ed4b10dbe13396ff7739160e) then.

EDIT: corresponding forum thread: https://support.delta.chat/t/beta-dc-ios-attaching-files/667

**Comment by avivador** [comment]
That’s would be great!
