### ISSUE TITLE
Can't see or even receive incoming messages

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-ios#38]
Beta 6, Installation at IOS 12.1, provider _web.de_
- All settings checked: Seemed to be ok
- Can't see any message which is incoming. Neither to an existing chat nor any other messages.

Android version has the logging facility where you can see the internal log by "settings->Info->About Delta Chat->(pushing text)".
Is this existing in IOS version too? When: How to use it? It would help to see if IMAP server is connected.

**Comment by csb0730** [comment]
What about "Contact Requests" ? Is this existing meanwhile? This would be very helpful too :-)

**Comment by r10s** [comment]
@jonasreinsch i have no recent web.de experiences.

**Comment by r10s** [comment]
would also be interesting if this issue is really related to ios - maybe the same happens on android or desktop.

**Comment by csb0730** [comment]
@jonasreinsch @r10s 
We found the reason for not receiving any mail from web.de: There seems to be a function at web.de account which separates incoming mails to known persons and unknown persons. All not known senders (me) are automatically moved to unknown persons and are not signaled to the device.
What we did is to move testmails from my address from _unknown persons_ folder to _known persons_ (by Web interface). After that, mails from me arrived at phone!

I got the information too, that there is not folder which is called INBOX or Posteingang or similar! This sounds strange to me and I want to double check this with my friend again.

So by now I can say that problem was caused by web.de account behaviour.

But with current IOS version it's very difficult to decide where the problem is because there seems to be no possibility to see interface behaviour (logring buffer). Will it be implemented soon?

**Comment by r10s** [comment]
thanks you for figuring this out. i've added a hint to the weird web.de inbox to the provider-overview in the support-forum.

wrt log: you can view the log by _shaking_ the device :)

as the initial question is solved and there is no actionable item left, i think we can close this issue.
