### ISSUE TITLE
improve onboarding after fresh setup

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#381]
if the user managed to setup an email account with DC, they get redirected to an empty chat list. 
We should implement a hint how to start to chat - similar to Android. The upper right icon is not super intuitive (from my point of view).

**Comment by r10s** [comment]
i think this won't be need as we add some "welcome" messages to the new _device-chat_ sooner or later - so the chatlist won't be empty.

moreover, there is the idea that also the _me-chat_ is shown by default, https://github.com/deltachat/interface/issues/26 , then, we have even two chats visible on each new installation.

**Comment by cyBerta** [comment]
ok, sounds like a plan. 
At the same time I want to point out that there's guidance missing how to create a new chat. To me, the upper right button is not self-explanatory. Adding an explanation to the device info chat would be fine, too. Changing the button could be another option.

**Comment by r10s** [comment]
i think the button is not that bad. it is exactly at the same position and has the same style as for whatsapp, telegram, signal, imessage and probably others. also, there are very few options to tap on, so, i would not change things there now.

**Comment by cyBerta** [comment]
ok, I'll close this ticket then
