### ISSUE TITLE
Support account switching instead of delete

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#388]
- [x] Remove delete account function or move it to a created account switching screen.
- [x] Provide known accounts implementation and support removability of accounts.
- [x] Take care this feature to use existing localization and interface same with desktop app for better user experience.

**Comment by r10s** [comment]
yip, multi account will probably come sooner or later. however, this issue tracker is only for bugs and for things, that are actually targeted by some devs.

feature requests or discussions should normally not go to this tracker, for this purpose, there is the support forum at https://support.delta.chat eg. this existing thread: https://support.delta.chat/t/multi-accounts-profiles-support/179

closing this for now.
