### ISSUE TITLE
forward messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#390]
this should be more or less the same as on android:

- long click on a messages should show "forward" to the already existing menu
- selecting this "forward", the chat-list should appear with the option to select a chat (we always forward to chats, not to contacts!). 
maybe we should re-use most of the normal chatlist-view, eg. we will add options to created-chats on-the-fly sooner or later.
- before forwarding is done, the question "forward to?" should appear, also same as on android.

**Comment by cyBerta** [comment]
>     * maybe we should re-use most of the normal chatlist-view, eg. we will add options to created-chats on-the-fly sooner or later.

@r10s Can you explain, what you mean by "reuse most"? What should be left out from the current chat-list?

**Comment by r10s** [comment]
> What should be left out from the current chat-list?

i just wanted to point out that, if possible, we should re-use the existing chatlist and add a "forward" flag or so. or re-use the list in a view. i just want to make sure we do not have to maintain two chatlists later :)
