### ISSUE TITLE
No alert for new messages

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-ios#40]
@jonasreinsch 

Current behaviour (beta 6):

- Only a vibration when a new message arrives. No indicator to be seen later.

Desired behaviour:
- When a new message arrives there should be a message or icon somewhere to indicate that DC has a new message (like Android version).
- Even when a chat is open new messages has to be added and marked is some way.

This is a very important feature for daily use and should be worked on with highest priority for next version!

**Comment by hpk42** [comment]
Just to be clear on the background of ios development: there is not a
whole lot of day-to-day active development on delta/ios -- apart from
some burst activities which improved ios quite a bit in the last 1-2 months.

**Comment by dignifiedquire** [comment]
The latest version on `master` has support for background notifications and I am using it regularly. It  is just at the mercy of the OS to be woken up to check new mails in the background atm

**Comment by csb0730** [comment]
is latest Version beta 6 ?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

Am 17. Januar 2019 16:40:36 MEZ schrieb Friedel Ziegelmayer <notifications@github.com>:

**Comment by csb0730** [comment]
and how to install then? Is it updated automatically by testflight?

**Comment by jonasreinsch** [comment]
@csb0730 Beta 7 should now be published in Testflight, this includes everyting up to https://github.com/deltachat/deltachat-ios/commit/9e558bae0b99a8204422f257ad3071f40c0b668e (see Changelog in master). If you have installed the Testflight app, you should receive a notification when new builds are published.

**Comment by csb0730** [comment]
Hi @jonasreinsch
just did some trials about new message alert at iphone. Unfortunately it's a little better than before but an alert is only rised if DC is open and screen not dark.
With this conditions DC is hardly to use in a standard way :-(

Is there a plan when implementing a reasonable alert for new messages? I think the basic aim of DC is to get an alert when a new message arrives.

I think this is the most important issue which prevents using DC in the moment at IOS.

By the way: Update to beta 7 worked fine 👍

**Comment by hpk42** [comment]
On Wed, Jan 23, 2019 at 15:02 +0000, Christian Schneider wrote:
> Hi @jonasreinsch
> just did some trials about new message alert at iphone. Unfortunately it's a little better than before but an alert is only rised if DC is open and screen not dark.
> With this conditions DC is hardly to use in a standard way :-(
> 
> Is there a plan when implementing a reasonable alert for new messages? I think the basic aim of DC is to get an alert when a new message arrives.
> 
> I think this is the most important issue which prevents using DC in the moment at IOS.

i doesn't prevent using it but it fails common expectations. 

it's tricky businesss neutralizing these "prevent background" strategy 
of Apple (and to a lesser but also annoying degree Android) forcing
everyone into centralizing over Apple/Google clouds. If we don't find
a way to run more reliably in iOS background some of us are considering
roughly the following: 

- implement and register a central global heartbeat server with Apple's
  cloud for all Appstore DeltaChat installs.  

- ping all devices every N minutes so they reconnect and check if
  there is anything new. 

wasteful but privacy preserving in that the central server (which we really
don't want to have, as you may imagine!) would never know of any messaging
metadata between devices.  It'd be an ugly hack increasing online traffic
for no good reason other than to circumvent the restrictions on having a
simple, efficient IMAP/PUSH socket with 0% cpu activity.

**Comment by thenktor** [comment]
What about:
https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

> For tasks that require more execution time to implement, you must request specific permissions to run them in the background without their being suspended. In iOS, only specific app types are allowed to run in the background:
> Apps that play audible content to the user while in the background, such as a music player app
> Apps that record audio content while in the background
> Apps that keep users informed of their location at all times, such as a navigation app
> Apps that support Voice over Internet Protocol (VoIP)
> Apps that need to download and process new content regularly
> Apps that receive regular updates from external accessories
> Apps that implement these services must declare the services they support and use system frameworks to implement the relevant aspects of those services. Declaring the services lets the system know which services you use, but in some cases it is the system frameworks that actually prevent your application from being suspended.
>

**Comment by csb0730** [comment]
Any news?

**Comment by r10s** [comment]
there seems to be some new approaches possible in the most recent ios version where background notifications may arrive faster, however, in general, as pointed out before, they arrive (with the mercy of the os) and in contrast to the initial issue, they are also shown as usual:


![image](https://user-images.githubusercontent.com/9800740/60670668-86b4ce00-9e71-11e9-8b90-8c5b8933ee85.jpg)

so the initial issue is fixed and this thread can be closed as there is no direct actionable item left.
as soon as we [manage to get the new version to testflight](- embedding a library on 5 platforms is not that simple -), it will also be easier testable

discussions about better approaches etc. of course can be continued - maybe better in the forum.
