### ISSUE TITLE
Chat does not show lock even if message was encrypted

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-ios#400]
- Device: iPhone SE
- iOS version: 13.2.3
- Delta Chat version: 0.950.0 (from testflight)
- Expected behavior: Show a lock for each message if it was encrypted.
- Actual behavior: No lock is shown.
- Steps to reproduce the problem: Send or receive a message with a mutually encrypting contact
- Screenshots:

![deltachat-ios-missing-lock-1](https://user-images.githubusercontent.com/57864086/69321260-0d145580-0c43-11ea-950a-f365b176568f.png)

![deltachat-ios-missing-lock-2](https://user-images.githubusercontent.com/57864086/69321273-11407300-0c43-11ea-96e7-57a671ddb967.png)

**Comment by cyBerta** [comment]
There are some UX questions around that. From what I recall from former discussions, we might omit the icon if the message is encrypted and only show an open lock if the message is not encrypted. But I'm not sure if this is the last word ;)

**Comment by hpk42** [comment]
at some point we will need to synchronize the behaviour on all UIs --
a good time to point to https://github.com/deltachat/interface
which we aim to use for such cross-app questions.

**Comment by pabzm** [comment]
Wouldn't it nonetheless be worthwhile to implement showing the locks? That would make the iOS-version catch up on Android and Desktop, which both show locks in both states.

**Comment by r10s** [comment]
> Wouldn't it nonetheless be worthwhile to implement showing the locks? That would make the iOS-version catch up on Android and Desktop, which both show locks in both states.

yip, i'd say for now it makes sense to show on ios the locks the same way as on android and desktop.  
as @hpk42 pointed out we can discuss further steps on https://github.com/deltachat/interface - but then we will do the changes cross-platform.
