### ISSUE TITLE
rename "profile photo" to "profile picture", use in contact lists

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#403]
first off all, the new profile photo image picker is great! good job, @cyBerta :)

some nitpicking i found out during testing:

- the thing should be called "profile picture", this more general and fits to the footer text ("your profile picture and name will be shown alongside your messages ...") as well as eg. whatsapp.

- the set profile picture should be shown in the contact list - eg. group members as well as for "new chat" (see android). to find out the profile image for a contact to be shown in a list, use [dc_contact_get_profile_image()](https://c.delta.chat/classdc__contact__t.html#a2ebee8ac3729e4db85041eaf35bfce73) (not: dc_get_config()!) - currently, this is implemented for SELF only, however, we will spead the profile image from other user soonish [in the core](https://github.com/deltachat/deltachat-core-rust/issues/807) and it is great if the uis are prepared for that.

on android, all this is already implemented.

nb: the contact-image is also be shown as chat-image for one-to-one-chats, however, this is also managed by the core already.

@Simon-Laux can you please check what the current state is on desktop? and file an issue for the missing items (select SELF-image via dc_get|set_config(), use all contact images via dc_contact_get_profile_image())

**Comment by Simon-Laux** [comment]
Using profile image for contacts that have it is long implemented in desktop.
For setting the profile image (https://github.com/deltachat/deltachat-desktop/pull/1151) we still need https://github.com/deltachat/deltachat-core-rust/issues/868 otherwise it'll be fairly useless.

**Comment by cyBerta** [comment]
rephrasing profile picture:
https://github.com/deltachat/deltachat-android/pull/1133/commits/b215ba1a4b3c32bd0c91287eeb040e542ffd59e9
