### ISSUE TITLE
headline redraw error

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#411]
the headline-rendering is trashed under some circumstances.

reproducible on an iphone7 with ios13 eg. at  chatlist -> new chat -> new group -> enter "x" as search -> hit "x" beside search -> hit "cancel" beside search -> hit "back" in the upper left corner.

![IMG_6E72693C78A2-1 2](https://user-images.githubusercontent.com/9800740/69752131-db265600-1150-11ea-9c95-8d41faf17ece.png)

**Comment by cyBerta** [comment]
hard to believe but it's an iOS bug! https://stackoverflow.com/questions/58134631/ios-13-uibarbuttonitem-not-clickable-and-overlapping-uinavigationbars-when-using

**Comment by r10s** [comment]
@cyBerta great finding! indeed, hard to believe :) however, the bug is fixed in iOS 13.2, i can confirm this.
