### ISSUE TITLE
Copy and pasted images cannot be sent

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#418]
One example to reproduce this bug:
- open a chat
- tap the message input bar
- chage the keyboard layout to the emoji selection
- select a Memoji the Memoji (= an image) will be pasted into the navigation bar
![Screen Shot 2019-12-04 at 11 12 54](https://user-images.githubusercontent.com/2614900/70134012-80788700-1687-11ea-882f-bcab0cd15e4b.png)
![Screen Shot 2019-12-04 at 11 14 11](https://user-images.githubusercontent.com/2614900/70134033-8b331c00-1687-11ea-9006-01ca6fe99e49.png)

- click on sent

![Screen Shot 2019-12-04 at 11 15 07](https://user-images.githubusercontent.com/2614900/70134050-92f2c080-1687-11ea-9e9c-d4e04059902b.png)

result:
- an empty message is sent

- occurs on current master

**Comment by r10s** [comment]
i think, for now, it would be fine if the image is just sent without the possibility to enter additional text (this is currently not possible even for attached imaged and would require a larger refactoring; i think at some point, we will introduce a staging area as on android, but not now)
