### ISSUE TITLE
avoid frequent appearing/disappearing of the input field

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#427]
in a chat, when eg. attaching an image or recording a voice-message the input bar disappears.

in between, it shortly reappears just to disappear again, this results in a bit annoying flickering.
also the whole screen is moved up and down.

same eg. if you select "delete" from the context menu and the actionSheet appears to ask for confirmation.

wondering if there are reasons why the input field disappears at all. it is grayed out and all controls lay over it.

**Comment by cyBerta** [comment]
The issue is in the InputBarAccessoryView library and I guess it's related to how the layout updates are done. Anyways, I couldn't find an easy fix for now. Maybe sb else can find out more.

**Comment by r10s** [comment]
this is currently fixed by #560 , however with some side-effects, #570 

also, #560 hides the but more coincidentally, so, might be it pops up again.

so, it may be worth having a closer looks, also as the quick disappearing and  reappearing is annoying. if we can fix this correctly, we can probably revert #560

**Comment by nayooti** [comment]
@r10s Can we close this?

**Comment by r10s** [comment]
it is still annoying and worth fixing. i think, we have a chance to fix it with #888

**Comment by cyBerta** [comment]
https://programming.vip/docs/ios-uses-uimenucontroller-without-hiding-keyboard.html
This might give us an hint how to handle the appearing/disappearing inputfield by tweaking the UIResponder chain.

**Comment by r10s** [comment]
looks complicated - not sure how many new issues that will produce :)
as mentioned, maybe target that after messageKitReplacement, also living with the current state seems to be a reasonable approach meanwhile :)

**Comment by r10s** [comment]
closing this, i just checked, at least it appears less annoying to be. might be because of "gallery" showed in cards, might be that the os is showing the things a bit smoother now.

**Comment by cyBerta** [comment]
https://github.com/MessageKit/MessageKit/issues/620

**Comment by r10s** [comment]
great! so, there is a chance in fixing that? in this case, please re-open :)

**Comment by cyBerta** [comment]
some things need time but will be fixed at some point :)

**Comment by r10s** [comment]
not sure if the re-appearing is really a bug, you'll notive sth. like that also in other apps. otherwise tracked in https://github.com/deltachat/deltachat-ios/issues/1737 now
