### ISSUE TITLE
Add explanatory screen(s)

### ISSUE THREAD

**Issue by flowinho** [deltachat/deltachat-ios#43]
I find the UI - especially the settings - currently rather incomprehensible. Given the fact that people over at r/privacy were asking “what is chat over email?” It might benefit the entire project to explain the idea with some Alice / Bob graphics.

Especially for people that download the app without having visited the website the current UI can be overwhelming if they do not grasp the concept behind DeltaChat.

Is this part of your MVP milestone? 

Best wishes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hpk42** [comment]
Lots of people agree it's a good idea to add some graphics and 
explanations and there are some thoughts on how to go about it. 

FWIW i wouldn't say that DC is exactly before the "MVP" stage because
delta is actually used (aka found useful) by quite a few people already.

**Comment by r10s** [comment]
the current onboarding screen is similar to the android screen - including explanations etc. - and is hugely improved to the version that was there at the beginning of the year. also the user is guided directly to the settings on the first start.

so i think this can be closed for now.
