### ISSUE TITLE
Support iCloud for backups

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#434]
May we support iCloud to import/export the backups? A normal user cannot be copy a file into iOS file system.

Also the backup not found message provides a wrong instruction. iOS does not contain a welcome screen. Backup not found screen shows the following message:

“Alternatively, press "Start messaging" to continue with the normal setup process.”

There is no "Start messaging" button on iOS because there is no welcome screen. I want to fix this, or can you implement a welcome screen?

**Comment by r10s** [comment]
we will add a "welcome" screen sooner or later, so the text will fit then.

wrt cloud backup - not really sure if we want to push users in this direction. compared to android, things on maverick are pretty straight forward - if you know what to do (iTunes is an unexpected app), things are working reliable.

i did not tried on catalina yet, however, as the file things go to the Finder there, it should be even simpler.

**Comment by r10s** [comment]
closing this, for the wording, i've opened #454
