### ISSUE TITLE
This beta test is full.

### ISSUE THREAD

**Issue by corppneq** [deltachat/deltachat-ios#44]
Can you please increase the amount of testers? I would like to try DeltaChat but TestFlight tells me the Beta is full.

**Comment by NightMachinary** [comment]
TestFlight limits to max 10k users. Perhaps this should go public beta on the app store?

**Comment by jonasreinsch** [comment]
@corppneq @NightMachinary  no there was a lower limit, I just increased it to the 10k now, so you should be able to download/install now. Could you let me know if it works?

**Comment by corppneq** [comment]
Thank you very much. It worked.

**Comment by cscipher** [comment]
Hey, can you increase the batch size, wanted to try the new features which are available on windows-app. 🙌
