### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by phmarek** [deltachat/deltachat-ios#45]
When trying to use `pop.easyname.com` and `smtp.easyname.com` as mail servers, delta chat returns SSL errors -- but the certificates look okay to me (`*.easyname.com`).

Would you please check whether it works for you? Thank you so much.

**Comment by adbenitez** [comment]
hello, please notice that you must provide an IMAP server, no a POP server, you are using `pop.easyname.com` which seems to be for a POP3 connection and Delta Chat works with IMAP, maybe it is `imap.easyname.com`

**Comment by hpk42** [comment]
please re-open this on https://github.com/deltachat/deltachat-core  if this remains an issue with imap srevers and provide an exercpt for the log.
