### ISSUE TITLE
Delta Chat doesn't work in the background

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#450]
If the user switches to another app, Delta Chat is closed. This shouldn't normally be the case.

**Comment by r10s** [comment]
we are not allowed to run in background on android.

however, apple gives us a timeslot here and then where we can check for new mails. we have no control about when and how often this happens, depends eg. on battery usage and if the device is moved and other factors - so this might be sth. between some minutes and an hour or so.

however, of course, if the user opens the app, messages are shown immediately.

**Comment by avivador** [comment]
‘ we are not allowed to run in background on ios‘. 

I would like to know how other messenger or mails app can do it. Just to learn. I am curious 😊

**Comment by r10s** [comment]
most other messenger use the "apple could" ([apn](https://en.wikipedia.org/wiki/Apple_Push_Notification_service), to be more precise) a to get their messages. 

so, if Alice sends a message to Bob, this message is routed at least partly over the apple servers - Alice pings apple and apple pings Bob.

as using these apn services require some unique identification, this is not easily doable with decentralized systems as e-mail, esp. the various e-mail-providers have to play this game.

**Comment by r10s** [comment]
while we can maybe improve the way we use the "timeslot", there is not much we can do on the initial issue. therefore we can close this ticket.
