### ISSUE TITLE
provide an unsigned .ipa

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#46]
the latest release at https://github.com/deltachat/deltachat-ios/releases seems to be pretty outdated, could you please provide the latest release, some people don't use TestFlight(people without Internet access) and prefer to install the app directly on their jailbraked devices.

**Comment by r10s** [comment]
i've just removed the .ipa file, however, i have no idea if and how we can provide a new one.

**Comment by Simon-Laux** [comment]
I propose that we we provide an unsigned ipa that could be installed with http://www.cydiaimpactor.com/ for example. But we must make sure that it's unsigned -> we should name the ipa something like `DeltaChat(unsigned)[version].ipa`.

I found this command on stackoverflow:
```
/usr/bin/xcodebuild -scheme MYSCHEME -workspace MYWORKSPACE.xcworkspace   
    -configuration Release clean archive -archivePath "build/APPNAME.xcarchive" 
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
```
https://stackoverflow.com/questions/25396299/generating-an-unsigned-ipa-ios-application

**Comment by dignifiedquire** [comment]
Impactor works pretty well, that is true.

**Comment by dignifiedquire** [comment]
Note: it does require to have a paid developer account to install using cydiaimpactor

**Comment by Simon-Laux** [comment]
> Note: it does require to have a paid developer account to install using cydiaimpactor

Really? I thought you can install for 7 days with normal apple id.

**Comment by r10s** [comment]
i think we can close this. there is a "new" testflight release, as soon as rust-core is stable again, we'll release a next release.

**Comment by Simon-Laux** [comment]
Its about providing an unsigned IPA on the releases page for use with jail broken devices in countries where testflight doesn't work as good, right @adbenitez?

**Comment by r10s** [comment]
ah, i see. thanks for reopening :)

**Comment by Simon-Laux** [comment]
@r10s can you upload a unsigned IPA on the github releases page?

**Comment by r10s** [comment]
apart from the links above - this is just another _target_ in xcode? with signing switched off? btw. wondering what the target deltachat-iosTests is for. 

anyway, i personally do not want to enter this new playground just now.

**Comment by Simon-Laux** [comment]
`/usr/bin/xcodebuild -exportArchive -archivePath build/DeltaChat.xcarchive` gives us an unsigned archive, from there we just need to convert that to an ipa.. though I haven't found out how to do that yet

**Comment by r10s** [comment]
closing this, no one is working on that and the issue tracker is about things that actually happen or ppl have subscribed to.

discussion about that, of course, can continue in the forum.
