### ISSUE TITLE
Create Verified groups

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#463]
Creating verified groups is not implemented yet. 
An entry should be added to Edit -> New Chat -> New verified group

**Comment by r10s** [comment]
there are some explaining hints in the string `verified_group_explain` now, see https://github.com/deltachat/deltachat-android/pull/1204, i think we should directly add this to the ios rework.

**Comment by cyBerta** [comment]
done with #464 and #474
