### ISSUE TITLE
requesting permissions more accutate

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#465]
to go to the app-store, we probably have to be a bit more concrete on asking the user for permissions:

see https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/

so it is needed to tell _why_ we want to access the camera, "Allowing access to the camera lets you take photos and videos" might be to general.

also the other permissions should be aligned to the apple-guidelines.

**Comment by OzancanKaratas** [comment]
I want to work for this at #461, please assign me.
