### ISSUE TITLE
Congratulation to Version 1.0

### ISSUE THREAD

**Issue by maitrenageur** [deltachat/deltachat-ios#468]
Is there a plan or road map to share Delta Chat with the Apple store?

**Comment by r10s** [comment]
thanks for the congratulations!

> Is there a plan or road map to share Delta Chat with the Apple store?

yip, we're along doing it these days. however, it may take a week or two until it is really there, depends on apple review timing/comments and some other things :)

**Comment by OzancanKaratas** [comment]
Actually, I think to release the App Store version would not be good before we implemented a important feature such as share function. The translations will be updated. We worked to show messages understandable by the users. We fixed most bugs and added many features. The team worked hard. In short, the App Store version should be perfect.

I greet you all respectfully and wish you peace.

**Comment by cyBerta** [comment]
it's released \ö/
That's why I'm closing this ticket.

**Comment by r10s** [comment]
\o/
