### ISSUE TITLE
No information about new messages

### ISSUE THREAD

**Issue by maitrenageur** [deltachat/deltachat-ios#469]
Hi,
With the new Version 1.0.0, the iPhone shows no information about new incoming messages, although options are switched on in Delta Chat and iOS system settings.
Best regards

**Comment by r10s** [comment]
did you get them before? afaik, there were no changes in this area, at for at least one device (mine ;) notifications work.

**Comment by maitrenageur** [comment]
With the new Version 1.0.2 it is solved.

**Comment by r10s** [comment]
thanks for re-checking, @maitrenageur
