### ISSUE TITLE
There are no Security option in the configuration

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#47]
In the registration view there are not Security IMAP and Security SMTP options, (to set SSL, STARTTLS, Off)

**Comment by andrew-thought** [comment]
also wondering about this issue, defaults to SSL, i need STARTTLS but no option to configure on IOS

**Comment by nayooti** [comment]
We altered the advanced setup by SMTP Security / IMAP Security in one of the previous PR. Should be available within the next Testflight-Release.

Need to mention though, that this are plain textfields at the moment (I will implement a dropdown menu within this month). I am going to close this issue for now.

**Comment by cocker-cc** [comment]
Is the Option `STARTTLS` already implemented?  I am testing "ddchat Version 1.0 (8)" fetched from Testflight today, and do not see that Option.

**Comment by nayooti** [comment]
In the `Settings`-Tab go to `Configure My Account` which will open the Account Setup (or Login Page).
In the Account Setup click on `Advanced` which will open advanced options.

`STARTTLS` you will find as an option in `IMAP Security` and `SMTP Security`.
Hope that helps.

**Comment by cocker-cc** [comment]
So I guess, the Version I got from Testflight is too old.  Thanks anyway.
