### ISSUE TITLE
App crashes showing network menu

### ISSUE THREAD

**Issue by avivador** [deltachat/deltachat-ios#479]
iPhone 6s 128 Gb
iOS 13.3
Delta Chat version: 1.0.1
Expected behavior: To see network menu
Actual behavior: The app crashes

**Comment by r10s** [comment]
what is the "network menu" you're talking about here? the one available from the debug toolkit when you shake the device?

**Comment by avivador** [comment]
I am talking about the menu when you shake the device, and then when you chose ‘network’.

**Comment by r10s** [comment]
yip, this is the debug toolkit.

**Comment by cyBerta** [comment]
The network entry is always empty for me. I propose to remove that completely.
