### ISSUE TITLE
get notification for Autocrypt setup messages

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#484]
At the moment it is hard to see that a new autocrypt setup message was fetched. It is shown in the saved messages chat, but neither an unread message badge is shown, nor a notification appears.

![Screen Shot 2020-01-09 at 16 44 58](https://user-images.githubusercontent.com/2614900/72108074-047ef800-3333-11ea-8415-1f29488968f1.png)

It would be nice to have a better visible indicator that the autocrypt setup message was fetched.

**Comment by r10s** [comment]
otoh, the sending device says: now go to your other device and open the ASM - so they do not arrive "just so" or unexpected.

**Comment by maitrenageur** [comment]
I have more or less the same issue. It is not real visible, that the messages are encrypted on the way or not. And the more than one device approach, especially with the "send to my self" option shows, that these messages are not encrypted.

For example: I send a message to a partner. The same message will be sent to me. The desktop app (Delta Chat for macOS) receive this message and shows the the same content. I check the encryption with my mail app and i see, this message is not encrypted, i can read it. I guess here is a bug.

**Comment by cyBerta** [comment]
Hey @maitrenageur, I think the issue you're describing relates rather to https://github.com/deltachat/deltachat-ios/issues/400
At the moment you can check if a message was encrypted by long-tapping on the message and tapping on the info button that appears.

**Comment by r10s** [comment]
closing this for, now. i do not think it has a high priority, as mentioned the asm is "sorted up" in the chat list, shown in bold etc.
