### ISSUE TITLE
Address book integration is somewhat broken (incomplete list of contacts)

### ISSUE THREAD

**Issue by grossbart** [deltachat/deltachat-ios#486]
- Device: iPhone X
- iOS version: 13.3
- Delta Chat version: 1.0.2

### Expected behavior

When I give Delta Chat access to my address book, I expect to search for email addresses within all my contacts.

### Actual behavior

Out of my 2600 contacts (300 in one account, the rest in another), only about 20 showed up. And these were mostly people I don't interact with much. After this, I have found no other way to re-sync the contacts or to add more from the address book, so I had to add them manually.

I'm not sure on what basis these 20 contacts were selected, most of my other contacts have email addresses in them, too.

On the other hand, I'm no glad that not all have been added, as it creates a contact for each email, which leads to some people showing up four times.

### Steps to reproduce the problem

This is on a first-time install and it asked me only once whether I want to connect my contacts, to which I said yes. (I would want to remove them again and try this again, but there is no functionality for this).

### Logs

It seems that the logs don't go back enough (I tried this in the morning and now it's afternoon and I can't see any log messages from the morning anymore in the Console).

**Comment by nayooti** [comment]
Thanks for submitting this issue.

I created this PR #488  to fix the issue. If the problem still exists with the next release we can reopen this issue.

FYI: DeltaChat v1.0x imports Contacts from the Default Account. To change your Default Account on your iOS-Device go to Settings -> Contacts -> DefaultAccount.

The fix will (hopefully) import contacts from all available accounts.
