### ISSUE TITLE
add "Delete chat" and "Archive chat" options to chat-profile-info

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#490]
currently, "Delete chat" and "Archive chat" are available only from within the chatlist.

so, if you're in a chat and decide, it can be archived/deleted, you have to go back to the chatlist and search the chat in the list which is a bit laborious.

android has a menu with these options inside the chat. as ios has no menu, i think we should add these options to the end of the chat-profie-info (where already "Leave group" and "Block contact" is) as follows:

![Screen Shot 2020-01-13 at 14 25 35](https://user-images.githubusercontent.com/9800740/72259649-48168200-3611-11ea-86e7-92afc170b6b4.png)
![Screen Shot 2020-01-13 at 14 20 48](https://user-images.githubusercontent.com/9800740/72259650-48168200-3611-11ea-9b90-47e3cca3e84c.png)

maybe a bit nicer, but you got the idea :)

the corresponding strings are `menu_delete_chat` and `menu_archive_chat`/`menu_unarchive_chat`. before deletion, there should be a quesion with an safeActionSheet as it is in the chatlist. the archive option does not need a quesion for now.

between "archive" and the red-options, i would add a gap and maybe title the red options with DANGER (there is string `danger` for that)

**Comment by nayooti** [comment]
@r10s Could you please specify, what exactly should happen, when the user taps on

- delete chat: the ChatDetail is usually presented on top of the chat which - given the deletion logic - shouldn't be there after the deletion - My suggestion would be: user taps on deletion,  the app navigates back to the chat list, and the deletion takes place there (could be animated).

- archive chat: same logic as above - could also navigate back to the chat list and handle archive operation there.

**Comment by r10s** [comment]
reopening to track the progress, i think the following are still missing:
- delete for group-profile is missing
- archive is not working on contact-profile and missing on contact-profile

**Comment by nayooti** [comment]
I am working on this right now. Almost done.

**Comment by r10s** [comment]
great!
