### ISSUE TITLE
VoiceOver silences when voice message button is pressed

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-ios#493]
In a chat window, VoiceOver silences after voice message button is pressed. I don't know why, but it does not happens in the WhatsApp and Skype.

**Comment by r10s** [comment]
hm, but this makes some sense, or?

**Comment by cyBerta** [comment]
What would be the expected behavior? 
Does VoiceOver not continue after the message was played?

**Comment by OzancanKaratas** [comment]
I don't know, I mentioned the recording behaviour. VoiceOver doesn't talk during voice recording. I double tapped the voice message button and VoiceOver stopped.
