### ISSUE TITLE
Apple Codelevel support

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#499]
We still have to free code level - technical support incidents until January 29.
We should use them.

An idea would be to ask them how we should do the receiving messages in the background as we can't use APN.

**Comment by Simon-Laux** [comment]
I guess we can still use them if we start the incidents TODAY.
For desktop we can ask them whether we can get away with using electron 4
https://github.com/deltachat/deltachat-desktop/issues/1134

**Comment by r10s** [comment]
> For desktop we can ask them whether we can get away with using electron 4
deltachat/deltachat-desktop#1134

@Simon-Laux yip, good idea! go for it :)

seems as if there are no concrete questions on ios currently, cc @nayooti
