### ISSUE TITLE
add local-help

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#501]
currently, there is a "help" item reachable at "settings" that opens the webpage https://delta.chat/help online.

this _online_-help should be replaced by a _local_-help which will also be available on no networks or on bad networks.

we've done this for android and desktop already, see https://github.com/deltachat/deltachat-android/pull/1207 and https://github.com/deltachat/deltachat-desktop/pull/1322 (both not released yet)

technically, the local help is currently a single html-file that should be added to the ios-resources somehow and should opened in a WBWebView as explained eg. at https://programmingwithswift.com/wkwebview-load-local-web-files-swift/ (UIWebView seems to be deprecated).

as a first step, the [android local-files](https://github.com/deltachat/deltachat-android/tree/master/assets/help) can just be copied, for updates, however, the [create-local-help-py script](https://github.com/deltachat/deltachat-pages/blob/master/tools/create-local-help.py) need to be adapted.

**Comment by Simon-Laux** [comment]
was fixed by #517
