### ISSUE TITLE
"group leave" button sometimes not available

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#504]
see https://support.delta.chat/t/to-leave-from-a-group-on-ios-app/761/6

the current master shows the button on my device, however, maybe there is also some bug, some weird condition or so, we should check that over.

**Comment by avivador** [comment]
Let me emphasize this, for me always I can’t see the leave button to exit from all the  groups. 
iPhone 6s
iOS 13.3
Delta chat v 1.02

**Comment by Simon-Laux** [comment]
Looks like it's hidden when `currentUser` is nil.

**Comment by r10s** [comment]
> Looks like it's hidden when currentUser is nil.

thanks for the hint!

in fact, there was such a condition for some reason at https://github.com/deltachat/deltachat-ios/blob/53021a5cdc80b4f2042b9a32aa23e35001cd7b39/deltachat-ios/Controller/GroupChatDetailViewController.swift#L127 - however, due to the last refactorings, the "leave" button is shown unconditionally, so i think this bug is fixed.
