### ISSUE TITLE
Color of ContactCell transparent -  Color Definitions are a bit misleading 

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#509]
The ContactCell background color is currently transparent. 

Look at `init` in `ContactCell.swift` you will see: 
`backgroundColor = DcColors.chatBackgroundColor`
`contentView.backgroundColor = DcColors.chatBackgroundColor`

and in `Colors.swift` it is defined as:
`static let chatBackgroundColor = UIColor.themeColor(light: UIColor(red: 255, green: 255, blue: 255, alpha: 0), dark: .black)`

The `alpha`-value is set to zero, meaning the color is transparent.

Is this intended?
Or should the Contact Cells-background not just be plain white? 

Also the ContactCell is used to display chats in the chatlist, where they appear white.

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-31 at 17 53 48](https://user-images.githubusercontent.com/5249565/73558086-c1f09d00-4452-11ea-8265-9a798727c72d.png)

**Comment by r10s** [comment]
> Or should the Contact Cells-background not just be plain white?

yip, they should be plain white, the transparency can be considered as a little ui bug :)

**Comment by nayooti** [comment]
ok, I'll fix that quickly
