### ISSUE TITLE
DeltaChat expiring in TestFlight

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#51]
I don't know anything about iOS, but some user wrote me to complain about Delta Chat is expiring in TestFlight.

**Comment by Simon-Laux** [comment]
in other words: we should do a new TestFlight update soon.

**Comment by DocVooDoo87** [comment]
Hello. DeltaChat is still available in TestFlight for 6 days. Is there an update in the next few days?
I would like to continue testing, because I really like the app and I'm looking forward to new features.

Greetings Marcel

**Comment by r10s** [comment]
@nayooti can you do an update this week?

**Comment by nayooti** [comment]
I could, but I don’t have Access to AppStore-Connect at the moment. It’s also protected by 2-Factor-Auth.

**Comment by r10s** [comment]
@jonasreinsch can you give @nayooti access? or what is needed to push a new version to the testflight?

**Comment by nayooti** [comment]
For this time, once the new built is finished (approx. 2 days), Jonas will ship this Testflight-Release.

In future, we are going to migrate the DC to an orga-account, where all active developers will gain access to.

Appstore-Connect-Accounts are protected by 2-factor-authentification. Logging in requires a code sent to the owner’s smartphone, which makes everything else but an orga account not maintainable.

**Comment by r10s** [comment]
@nayooti, @jonasreinsch  cool, thanks for taking care :)

**Comment by corppneq** [comment]
> "Delta Chat Beta" Beta expired.

![delachat](https://user-images.githubusercontent.com/4342880/56474364-1d7c0c00-6479-11e9-9efc-baa60fe94aa7.jpg)

**Comment by Simon-Laux** [comment]
@jonasreinsch

**Comment by jonasreinsch** [comment]
@nayooti @Simon-Laux @corppneq since the PR is not merged yet, I just released a build equivalent to the last one to start the 90 day countdown again.
