### ISSUE TITLE
profile-view avatar does not respect darkmode, name is missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#512]
this bug seems to be introduced in 1.1, it was already fine in 1.0 - in general, on all changes, we should also test the dark mode to not get regressions there :)

![Screen Shot 2020-02-01 at 21 46 17](https://user-images.githubusercontent.com/9800740/73598737-52ef7300-453c-11ea-9077-03eb65811f9d.png)

**Comment by r10s** [comment]
seems to be fixed already by https://github.com/deltachat/deltachat-ios/pull/508

**Comment by r10s** [comment]
hm, we're currently doing a 1.1 release, merging #508 still requires some work, so maybe we should do a quickfix.

**Comment by r10s** [comment]
i cannot reproduce this any longer :/

**Comment by cyBerta** [comment]
I think this is still an existing bug

**Comment by cyBerta** [comment]
![Screen Shot 2020-03-03 at 15 15 46](https://user-images.githubusercontent.com/2614900/75784294-4b510300-5d62-11ea-9123-9666ae18daf3.png)

**Comment by r10s** [comment]
maybe we can stop using the header at all and just reuse the corresponding cell.
