### ISSUE TITLE
Navbar color glitch during Push- and Pop-transition

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#518]
On push- and pop-transition between two ViewControllers the NavigationBar has a darker color glitch during the Animation.

![IMG_D1DC29B54889-1](https://user-images.githubusercontent.com/5249565/73925483-6d27a900-48ce-11ea-8f50-d2bdaf87c1d0.jpeg)

**Comment by r10s** [comment]
yip, i also would like to be this fixed :)
