### ISSUE TITLE
Settings - Help-Button click event doesn't always go through

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#519]
Realised it while working on the new HelpViewController:

When tapping in Settings-Tab on Help-Button it always gives optical feedback but the underlying event is not always triggered in 1 out of 10 cases. 
It's really hard to reproduce. It's seem to happen randomly on my Iphone 11 Pro and I could not trigger the error at all from my Iphone SE, both on iOS 13.3.  My feelings say it happens more often after restarting the app.

I tried setting a print-statement inside 
`openHelp`-method and it is indeed not printing anything when the error occurs. 

I assume it has something to do with the `QuickTableViewController`-library  and the way it triggers events. 

Btw: Originally I thought it is caused by the new HelpViewController that fetches HTML-data from disk. But it's not.

**Comment by cyBerta** [comment]
I agree with your assumtion. Maybe you can refactor the whole screen and throw out QuickTableViewController.

**Comment by nayooti** [comment]
ok.

**Comment by nayooti** [comment]
After ditching QuickTableViewController the bug is still there.

**Comment by r10s** [comment]
hm, however, getting rid of QuickTableViewController was a good idea anyway :)

**Comment by nayooti** [comment]
Can be reproduced:
Settings - Scroll up -> in TabMenu switch tab -> in TabMenu switch tab back to settings -> Scroll down -> tap help -> bug

**Comment by nayooti** [comment]
The more and more I look into this I think this is a feature rather than a bug.

I believe what happens is that my test device is misinterpreting my touch gesture.
I have two test devices. Iphone SE (mid-range-phone) and  Iphone 11 Pro (newest pro device). As stated the so called bug only happens on the latter one.
It got clear to me, when I set `tableView.delaysContentTouches = false`. Now even scroll gestures trigger cell highlights without calling the `didSelectRowForIndexPath`-delegate-function.
I think when you tap a cell strongly it always selects the cell. But if you tap slightly my Pro-device thinks my intention was to scroll or whatever.
Apart from this:
`tableView.delaysContentTouches = false` is actually pretty nice, since it provides direct feedback. I would leave it like this.

**Comment by r10s** [comment]
i think you're right.

the issue only happens when tapping really _fast_ - so it can be provoked pretty easily - tapping eg. "help" -> "back" -> "help" again - does not open help, another tap is needed.

if you do this only a _bit_ slower, things work as accepted.

i tested this with the system-settings-app - and this one has exactly the same behavior - so, yes, the system seems to threat these clicks as accidental, unwanted clicks - and, in practise, using the phone with one hand in the rain etc. this is probably right :)
