### ISSUE TITLE
UIBug: status Indicator shown in ConactCell if archived

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#526]
![IMG_752DCA92BA96-1](https://user-images.githubusercontent.com/5249565/74524669-cbccd280-4f1f-11ea-85cc-404e4b313134.jpeg)

**Comment by r10s** [comment]
took me a moment to understand: the bug is the checkmark shown above the summary-text :)

**Comment by r10s** [comment]
the indicator and also the archived-label is still shown as an overlay in contact-profile/shared-chats.
the bug is only visible after scrolling up/down a bit, probably a recycler-error or so.
