### ISSUE TITLE
add a hint for fetching submodules to README

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#54]
It might fail with an access denied like this:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Options to solve it:
A: get an ssh key registered with your GitHub account and have it setup in a way that git on your system can use it.
B: after a failed attempt open the file '.git/config` and change the git/ssh urls into https ones (example `https://github.com/deltachat/deltachat-ios.git` instead of `git@github.com:deltachat/deltachat-ios.git`).

**Comment by r10s** [comment]
there is now the hint `git submodule update --init --recursive` and afaik, there are no special rights for keys needed for checking out the repos. so i think, this can be closes. if i missed a point, please just do a pr to the README.
