### ISSUE TITLE
Reinitiate device chat and saved messages ...

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#544]
...after the user switched the email account.

Currently, after deleting an email account from the device and setting one up again, the default device message chat and and saved messages chat are not visible anymore and an empty list is left in the chats tab.

My expectation would be that both chats would appear as if the user installed Delta Chat from scratch. 

This probably needs some work on the core though, @r10s?

**Comment by r10s** [comment]
hm, the core provides everything needed. at least in theory, this should work. 

- the default device message chat and and saved messages chat are added by dc_update_device_chats() resp. updateDeveiceChats() which is called unconditionally in ChatListController::init() - so everytime the chatlist is dispayed.

- dc_update_device_chats() adds the chats - if they have never been added to a database before - whould should be the case as the database is delete before reopened - or maybe this `FileManager.default.removeItem(at: dburl)` in AccountSetupController is not working as expected?

**Comment by r10s** [comment]
i got the issue, the updateDeviceChats() is called on init of ChatListViewModel() - this is actually not done when the database is replaced.

another issue is that the device chats are initialized even if the database is not yet configured - this results in a 3-unread-messasges-badge even for unconfigured accounts.

i'll do a fix.
