### ISSUE TITLE
fix info message layouting

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#556]
The info messages in a chat view (like "Location streaming enabled", "Location streaming disabled" should be centered in the chat view. For some reason these messages are after a orientation change alternating between left- and right-alignment but they're never centered. Scrolling the list up and down "fixes" the issue.

![infomessagebug](https://user-images.githubusercontent.com/2614900/76434768-68b34c00-63b6-11ea-81e3-9b483ccd2ee9.png)

**Comment by adbenitez** [comment]
IIRC, that is an issue that is also present in Android version

**Comment by r10s** [comment]
afaik, in general, this is okay on android, info-messages are centered there. iirc, there is a minor issue that the centering is not perfect when switching from portrait to landscape, sth. like that, not sure.

**Comment by adbenitez** [comment]
yes, that is what I meant, I though it was the same issue here of orientation changes
