### ISSUE TITLE
use flutter？

### ISSUE THREAD

**Issue by godot0413301** [deltachat/deltachat-ios#56]
I wander maybe this software using flutter is batter.Beause flutter is design by compile both ios and android.
我觉得，deltachat使用flutter框架会更好。因为flutter框架同时编译ios和安卓

**Comment by nayooti** [comment]
Hi there,

Thanks for your suggestion.

We had a quick chat about this lately, so from this I can maybe answer this:

- DC-clients are aiming a native look on both platforms, which can‘t be easily done with Flutter (with Flutter both clients will moreless look „materialish“).
- At the current stage (Android-client available in AppStore, iOS-client in production) we are committed to native development. At least for now.



Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: godot0413301 <notifications@github.com>
Gesendet: Sonntag, April 21, 2019 3:22 AM
An: deltachat/deltachat-ios
Cc: Subscribed
Betreff: [deltachat/deltachat-ios] use flutter？ (#56)


I wander maybe this software using flutter is batter.Beause flutter is design by compile both ios and android.
我觉得，deltachat使用flutter框架会更好。因为flutter框架同时编译ios和安卓

**Comment by Simon-Laux** [comment]
@godot0413301, If you want to try a flutter dc client you can try https://github.com/open-xchange/ox-talk . OX Talk is a deltachat based COI client made with flutter and deltachat core.

**Comment by Simon-Laux** [comment]
@godot0413301 I think your suggestion/question is better asked in the forums(https://support.delta.chat)
because it's not specific to iOS development, rather it's mobile development in general and with the use of flutter hummingbird its probably also web/desktop.

**Comment by Simon-Laux** [comment]
I'll close this now, see you on the forums @godot0413301
