### ISSUE TITLE
playback of voice message stops when screen is turned off

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#561]
probably the same issue with other audio.

would be great if we can use the system-player for that (the one that eg. spotify uses, safari with youtube videos etc.)

we could also support prev/next easily then, with [dc_get_next_media()](https://c.delta.chat/classdc__context__t.html#a9bb2762236dc193c7e5fd155d66c80d5) - this would also be already one step to a shared playlist player (ppl can create a group to share mp3 and play them easily directly from delta)

**Comment by nayooti** [comment]
I tested how other apps are treating this, and I think this is the default behaviour. And it makes sense to me (at least in the case of voice over) to have a short cut to mute the voice over.

**Comment by r10s** [comment]
> I tested how other apps are treating this, and I think this is the default behaviour

also, when the screen is just dimmed/turned off after 30 seconds or so?

**Comment by cyBerta** [comment]
https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/configuring_the_audio_playback_of_ios_and_tvos_apps
