### ISSUE TITLE
Notifications not shown instantly

### ISSUE THREAD

**Issue by tompatulpan** [deltachat/deltachat-ios#569]
No notifications are shown until DC is opened. In standby there is no (push) notifications.

- Device: iphone X
- iOS version: 13.3.1
- Delta Chat version: 1.2.1
- Expected behavior: show notification on locked phone.
- Actual behavior: dont show anything until DC is opened, then the red dot shows if new messages.
- Steps to reproduce the problem:
- Screenshots:
- Logs:

Let me know what logs to collect if needed.

**Comment by croessner** [comment]
Same problem here. I get not informed about new messages until I open the app

**Comment by stefanbesler** [comment]
Same here

**Comment by seehma** [comment]
same here, this continuous check does not work. I only see the emails coming in my mailbox, but the app does not check. When i open the app -> the messages are arriving.

Is the mail App also continuously checking the server, or how does the notification of new email work in those mail apps (Outlook, Apple Mail, ...)

iOS 13.6
deltaChat App: 1.10.1
iPhone 11

**Comment by r10s** [comment]
as we do not apples push service, currently, Delta Chat can only check for new mail when the operating-system allows us to do so. if the app is "in frequent use", that may be every 10 minutes or so, however, this timespan may grow endlessly when the app is not in use.

**Comment by csb0730** [comment]
I got the same complaints from a friend of mine.

No chance to do anything? For standard WA users (focus is at WA) this issue makes delta quite unusable :-(

**Comment by croessner** [comment]
What, if ActiveSync was supported? I use SOGo with ActiveSync to have push working. Would it be possible to implement this for delta chat, too?

**Comment by hpk42** [comment]
There recently were some successful experiments with a Delta/iOS version and a 
notification provider that integrates with Apple's notification cloud. 
It worked on dev phones but there is a number of things that need doing
to get this releasable, among them legal/GDPR questions.

**Comment by csb0730** [comment]
Isn't it possible to have at least a fix time interval to wake up DC when sleeping? Maybe 10min or similar? Even an hour would be better than nothing!

**Comment by r10s** [comment]
without the help of the server, as far as i know, a "fix time interval" is not possible, only intervals chosen by the system  as mentioned at https://github.com/deltachat/deltachat-ios/issues/569#issuecomment-663457132

**Comment by masvil** [comment]
I hope a kind of notification will be implemented. In the while we can rely on "standard" incoming email notification in some way.

**Comment by cyBerta** [comment]
There is also a bug, which will be fixed with https://github.com/deltachat/deltachat-ios/pull/986. If the app is in foreground notifications never arrive. It leads to the situation where the message badge counter is > 0 but no related notification appears.

**Comment by thenktor** [comment]
> No chance to do anything? For standard WA users (focus is at WA) this issue makes delta quite unusable :-(

To be honest: the lack of notification makes Delta Chat unusable for quite everyone 😉 Probably everybody expects instant notification from an instant messenger.

**Comment by masvil** [comment]
> To be honest: the lack of notification makes Delta Chat unusable for quite everyone 😉 Probably everybody expects instant notification from an instant messenger.

I agree 100%, it should be a high(er) priority.

**Comment by hpk42** [comment]
On Tue, Mar 16, 2021 at 03:00 -0700, masvil wrote:
> > To be honest: the lack of notification makes Delta Chat unusable for quite everyone 😉 Probably everybody expects instant notification from an instant messenger.
> 
> I agree 100%, it should be a high(er) priority.

development on this is happening this week probably :)

**Comment by r10s** [comment]
in the next version, the app will wake much more often, see recent commits and pull requests.

closing this issue as there are more concrete ones that are beeing worked on, see https://github.com/deltachat/deltachat-ios/pulls?q=label%3Anotify+
