### ISSUE TITLE
gallery is no longer full screen

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#570]
introduced by one of the most recents merges, the gallery (opened from a chat) is no longer fullscreen. or is this intended? then it looks still weird ;) cc @cyBerta

**Comment by r10s** [comment]
i think this was introduced by the QLPreviewController, at https://github.com/deltachat/deltachat-ios/pull/560 , so, maybe it is fine, maybe we should add a "close" or so to the bar.

at least for now, there is no actionable item.

**Comment by nayooti** [comment]
I’ll look into this.

I actually added a Close-item manually in case the QLController is pushed.

Am 17. März 2020, 22:25 +0100 schrieb bjoern <notifications@github.com>:

**Comment by r10s** [comment]
thanks, did a closer look, i think we should try to get fullscreen back, esp. the "black" view on the second tap is weird.

not sure, if a fully black view (without visible stuff behind) is doable by a  QLPreviewController - if not, let me try to fix the initial issue first (retarget #558)
