### ISSUE TITLE
cannot send messages with web.de account

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-ios#571]
- Delta Chat version: v1.2.1 from AppStore
App has been installed for the first time at device.
Reading of local adressbook not granted.
Then web.de address in DC has been configured.
All preparations at web.de done. 

- Expected behavior: 
Receiving and sending of msgs should run out of the box.

- Actual behavior:
Receiving of msgs is possible.
Writing msgs possible. They are shown as sent in DC chat view, but in reality they are not sent and they are neither arrive at mailserver nor at receivers device. 

- Logs:
Log at IOS app not available?! Cannot find it.

**Comment by r10s** [comment]
> Log at IOS app not available?! Cannot find it.

if you shake the device, you will enter some debug mode (yip, this is a bit weird)

**Comment by csb0730** [comment]
Would recommend to implement here the same log menu entry than android version has.
Big effort?

**Comment by r10s** [comment]
yip, i would also like to see that - but it is just not done yet.

**Comment by csb0730** [comment]
Or to reduce workload now, just place a text at desired position that shake gesture provides function and where to find the log then.

**Comment by csb0730** [comment]
Regarding the issue itself, my friend unfortunately stopped now using DC because of non function so I can't get any log. Could not convince him to try again :-(

We should keep this issue open for a while that others can see it when they have the same issue.

At the end we seem to have an issue with smtp connection, but can't see it at users level. Maybe DC should give some verbose messages in device chat when such a problem occurs.

**Comment by r10s** [comment]
> At the end we seem to have an issue with smtp connection, but can't see it at users level.

[showing the smtp-error directly to the user (not only a toast or a log) is on the "roadmap"](https://github.com/deltachat/deltachat-core-rust/issues/1341), we had a similar issue with yandex that wants the user to click a link returned in the smtp-error message ...

**Comment by csb0730** [comment]
web.de in general works.
I can confirm this because I'm using a test accout there by myself.

Even another colleague who is using ios version of DC is using this. There it works too!
I'm asking about his' DC version.

**Comment by webratte** [comment]
I can confirm that.

My web.de account also works.
In the first three month after it was new created I realized a limit of 10 messages per hour to send.

**Comment by r10s** [comment]
> In the first three month after it was new created I realized a limit of 10 messages per hour to send.

one more reason for showing the smtp-error directly and permanently in the chat.

**Comment by csb0730** [comment]
To mitigate determining a server error maybe show automatic selected settings to the user.
In the moment user sees only "automatic", but not real choosen settings in detail.

That would help in first step if there are server issues.

By the way, standard user will not have a chance to find these infomations in log.

**Comment by r10s** [comment]
k, so we can close this, web.de in general works, the mentioned issues are handled separately and not directly related. no actionable item left for ios.
