### ISSUE TITLE
a tap on the avatar does not perform any action

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#573]
in the chatlist, in the contact-list, in the profiles, a tap on the avatar is ignored completely.

it should do the same action as tapping the rest of the cell.

(only for the avatar in the profile-header we will want an "enlarge avatar" function soonish and have a different action on an avatar-tap therefore, so, if possible, it would be cool to stay a bit flexible)

**Comment by nayooti** [comment]
it's possibly fixed in #577 
https://github.com/deltachat/deltachat-ios/pull/577/files#diff-b9a1ec185d87b439e1d753d577216c34

I removed the TapGesture of avatarCell here, because it didn't do anything except for blocking the delegation of touchEvents to the underlying cell-selection-event.

**Comment by r10s** [comment]
yip, it is fixed with the new chatlist :)
