### ISSUE TITLE
Rename some classes 

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#576]
Currently **ContactCell** is used to display Contacts and Chats, so the name _ContactCell_ is a bit misleading.

Any suggestions? What does Signal use on Android?

@r10s does not like Avatar...cell.

Also suggest **other classes**/variables where the naming is a bit off.

This issue should be addressed once the PR-count hits zero.

**Comment by r10s** [comment]
signal uses the wording `Recipient` for objects that may be contacts or chats (or similar things), we do the same on android. just saying, i am not suggesting to do the same on ios.

maybe sth. as `StandardCell`?

but, thinking it over, i would also be fine with `AvatarCell`, i have no better suggestion :)

**Comment by r10s** [comment]
`ContactDetailHeader` is maybe also a bit misleading, it is used for groups and for contact profiles, so this might be `AvatarHeader` then?

**Comment by r10s** [comment]
closing this for now, we'll refactor when we're on it.
