### ISSUE TITLE
add counter to search-headers

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#579]
the search-headers currently read only "CHATS", "CONTACTS", "MESSAGES".

it would be great, if we can add the number of results to each header, so "5 CHATS", "6 CONTACTS", "7 MESSAGES".

the strings needed for that are already available and translated as `n_chats`, `n_contacts` and `n_messages` (the strings have different singular/plural forms, grep for n_members to get an idea how to use it)

btw, this is what it looks like on android:

<img width=320 src=https://user-images.githubusercontent.com/9800740/77214470-9d8a7600-6b0f-11ea-92c7-a3df624bf399.png>

**Comment by nayooti** [comment]
@r10s are you sure that current master contains the required strings already?

**Comment by r10s** [comment]
fixed by #583
