### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-ios#58]
iOS needs to support localization -- a bit unclear how soon as it's probably more interesting to get some basic features first (as of May 2019). 

_next paragraph is from @r10s, sorry, @hpk42 for writing in your issue. but such feature lists are rather useful ;)_
- [x] target the issue of strings used as IDs as written down [below](https://github.com/deltachat/deltachat-ios/issues/58#issuecomment-510063762)
- [x] check which format is used by ios
- [x] write a shell or python script that pulls strings.xml translations in all languages from transifex and converts them to the format used by ios
- [x] replace hard-coded strings by replaceable strings in the way this is done typically by ios
- [x] make sure, delta chat is shown in the system language

**Comment by r10s** [comment]
before localization can be done, things as https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/Controller/SettingsController.swift where titles are used as ids MUST be refactored.
