### ISSUE TITLE
search should scroll up on entering new characters

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#584]
the new additive search from #577 should scroll up, when not already atop of the list.

example: the user types in "a", scrolls somewhere down and then changes the input to "ab" - now the search should snap back to scrolling position 0 - the manually scrolled position is somewhat random.  
same when deleting characters, so, in short, on any changes wrt search term.

EDIT: also, when the search-cancel button is hit, we should scroll back to the top (btw. scrolling may be done using tableView.scrollToTop() - but maybe there are other ways :)

this is the behavior eg. in the system address book and for other searched, play around there to get an idea.

**Comment by nayooti** [comment]
We should also implement this on `NewChatViewController`

**Comment by r10s** [comment]
yip!
