### ISSUE TITLE
improve share UI

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#599]
**_IF_** we want to have a similar UX as signal on iOS has (to the user it looks like the host app is opened when sharing data because the UI is reused in the extension) we need show the chat list UI first and on entering a chat we would have to add the shared data to a draft section (which is still missing at all). It woule be basically the same workflow as on Android

**Comment by cyBerta** [comment]
as discussed with r10s we will probably not reuse existing UI and also not follow the signal UX approach.

**Comment by r10s** [comment]
we have meanwhile share-to-contact and more concrete issues for the remaining things, https://github.com/deltachat/deltachat-ios/issues?q=label%3A%22share+extension%22
