### ISSUE TITLE
Enable real Push-IMAP when app is in foreground

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#6]
currently there is a workaround for `__APPLE__` at https://github.com/deltachat/deltachat-core/blob/master/src/mrimap.c#L1352 that uses a poll when mrimap_idle() is started (the fallback is normall only for servers that do not support Push-IMAP at all)

- check why Push-IMAP failed for iOS
- remove the `#ifdef __APPLE__` hack

**Comment by jonasreinsch** [comment]
@r10s as I understand it, this can be closed now with the update to the new deltachat core, right?

**Comment by r10s** [comment]
@jonasreinsch sure :)
