### ISSUE TITLE
are adaptions for ios 13 needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#603]
just noticed that there was another deadline from apple wrt ios13 and ipad, the deadline was april 13 but was just delayed by 2months because of the corona crisis.

https://www.golem.de/news/coronavirus-krise-apple-lockert-strenge-anforderungen-an-apps-2003-147536.html

question: are adaptions needed if we want to continue to ship for ios and ipad? cc @cyBerta @nayooti @dignifiedquire

**Comment by nayooti** [comment]
iOS 13 has this scene-concept, and we probably should add that to our project as well.

**Comment by r10s** [comment]
what is the scene-concept good for?

**Comment by r10s** [comment]
delta runs fine on ios 13, so we can close this issue.
