### ISSUE TITLE
allow account creation by qr-code-scan

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#608]
- add a button "Scan QR code" to the new welcome screen

- on tapping, open a new screen with the option to scan a qr-code, check the scanned qr-code as usual with [`dc_check_qr()`](https://c.delta.chat/classdc__context__t.html#a34a865a52127ed2cc8c2f016f085086c)  
of course, the scan-screen also needs a "cancel" button as the manual-setup screen.

- if a `checkQr()` returns with `lot.state` set to `DC_QR_ACCOUNT`, ask the user if he wants to create a new account on the domain given as `lot.text1`

- if the user wants to do so, pass the whole scanned qr-code to [`dc_set_config_from_qr()`](https://c.delta.chat/classdc__context__t.html#ac95d7275f01862fba70169b8cbb937c0) and continue with `dc_configure()` as usual.

- if things work out, the user ends in the chatlist as usual - on errors, the user should be redirected to the welcome or, if possible, to the scan-qr screen.

this is how things look like on android - the alert is shown over the welcome-screen for $technicalReasons, i would prefer them laying over the scan-screen, if possible on ios:

<img width=300 src=https://user-images.githubusercontent.com/9800740/78052146-fca58180-737e-11ea-857a-951dba0ca94c.png> <img width=300 src=https://user-images.githubusercontent.com/9800740/78052150-fdd6ae80-737e-11ea-9ca0-8aa85e0d822f.png>

**Comment by r10s** [comment]
needed strings: https://github.com/deltachat/deltachat-android/pull/1276/files#diff-4691bafd7791e471b30c492e6f43d65b - you can use the constants as placeholders already, the strings will be uploaded to transifex soon.

**Comment by nayooti** [comment]
@r10s: 
Let's assume: 
User scans (valid) qr-code, but somehow we get`dcContext.configureAccountFromQR(qrCode: code) == false`.

I implemented it as specified, but I am missing some kind of error message here. Currently the user is redirected to the QRCodeReader without any information that something went wrong.

**Comment by r10s** [comment]
when configure() returns, the configuration is typically not even started, so you have to listen to DC_EVENT_CONFIGURE and DC_EVENT_ERROR  events - actually, this is already implemented, so i maybe we can just give control to the AccountSetupController somehow.

nb, re-opening as this seems to be closed accidentialöy
