### ISSUE TITLE
Login form should be cleared after successful login

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#615]
Currently the LoginViewController seems to be reused if the User deleted an account with the help of the corresponding settings option. After tapping on the login button on the welcome screen, the prefilled login form appears (until the app was killed by the system or the user). 
This is a security issue, because after the deletion of the account there shouldn't be a possibility to login again without reentering the credentials.

**Comment by r10s** [comment]
i also noticed that, wondering where this comes from.

i also miss the forward-to-welcome sometimes. hitting "delete account" a second time in these cases (which should not be possible as the "delete account" button is not present on initial setup) seems to show the welcome-screen and really forgets the credentials.

might be that it does not really forward to welcome-screen the first time and the old from is just displayed again.
