### ISSUE TITLE
Improve ChatView 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-ios#62]
properly show dates, fine-tune the distances of speach "bubbles", adjust colors, maybe allow backgorund image, try to get metadata (dates etc.) into speach bubbles so it better works with custom backgrounds.

**Comment by nayooti** [comment]
I had been tweaking this a bit lately, but honestly, the chosen library is quite a pain to work with. Until I haven't found a better library I will leave it like this for now (including my tweaks).
