### ISSUE TITLE
Gracefully handle non existing chatId

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#630]
Currently delta chat crashes if the last used chat id saved in UserDefaults doesn't exist. While switching forth and back during the development it happend to me that the chatid was not existent and I needed to comment out the logic in  AppStateRestorers `restoreLastActiveChatId`. For me this looks like a potential call for trouble in production when the user updates DC or recovers DC from a backup. Therefore we should check on start up if a  chat id to restore exists and then try to navigate to the according chat. 

The crash comes from initializer in DcChat: 
```
init(id: Int) {
        if let p = dc_get_chat(DcContext.shared.contextPointer, UInt32(id)) {
            chatPointer = p
        } else {
            fatalError("Invalid chatID opened \(id)")
        }
    }
```

**Comment by r10s** [comment]
yip, in general, we should probably be careful with this fatalError() and never call it for the reason of bad incoming data. just saying, doing a quick grep over "fatalError", in general, this looks good :)

**Comment by nayooti** [comment]
In Swift we have **optional Initializers** .  Looks like a good place to actually try them  :)
