### ISSUE TITLE
follow-up qr-account review

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#631]
i was a bit too slow with my comments for #611 - so here:

- https://github.com/deltachat/deltachat-ios/pull/611/files#diff-45adb9fd753fd8259342d6146d208462R137: the used string is wrong, please just use `login_header` for now (`qraccount_use_on_new_install` is not the title but a message that should be shown when an account-creation code is scanned accidentally)

- in find the spinning wheel in the welcome screen together with the percentage in the overlaying dialog weird. please just remove the spinning wheel - and let the alert-dialog pop up a bit sooner (it is delayed for whatever reason)

- the string `qraccount_config_failed` is probably not needed, in case of error, just show `AppDelegate.lastErrorString` - wondering if this is done on manual account creation, if not, it has to be done there as well

but apart from that - the account creation works!!!!!111one111eleven!

**Comment by nayooti** [comment]
I don't have a QR-Code that actually fails during account creation.

**Comment by nayooti** [comment]
One more issue: pressing Cancel during the creation process doesn't actually cancel anyting.

**Comment by r10s** [comment]
> I don't have a QR-Code that actually fails during account creation.

you can use most others qr-code for that, eg:

![qr](https://user-images.githubusercontent.com/9800740/79555748-5bb60680-80a0-11ea-9a97-1a21b9515e91.png)

to generate, you can use eg. the commandline-tool `qrencode TEXT -o FILE` or `https://duckduckgo.com?q=qr+TEXT`

**Comment by r10s** [comment]
this one should fail _during_ account creation:

![qr3](https://user-images.githubusercontent.com/9800740/79556763-d0d60b80-80a1-11ea-9ffc-dc48fab5d3de.png)

(generated with `qrencode "DCACCOUNT:https://wontwork.local/new_email?t=foobar" -o qr.png`)
