### ISSUE TITLE
Export and Import DC data

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-ios#64]
for moving from testflight to appstore it would be good to support export/import functionality like it is done on Android.  @jonasreinsch do you know how we can export to a local file and import that file from another app (which we'll have if we release to appstore).  If export/import proves too hard we can also drop it especially for the may release.

**Comment by r10s** [comment]
https://stackoverflow.com/questions/11727883/ios-shared-file gives some advices

**Comment by r10s** [comment]
related #161 and #160 - so in general this seems to work.

**Comment by r10s** [comment]
importing any backup is possible by:

- install a fresh delta chat
- connect to itunes
- upload backup via itunes to "delta chat/shared files"
- in delta chat, click "import" on loging screen - unfortunately there is no confirmation nor a progress bar yet, see #160 , but the import should work

the file to import can be exported by android (settings / chat / export) or by ios (settings / export). cave: on ios, the exported files may be deleted when the app is uninstalled! so make sure to copy them away if you want to uninstall the app.
