### ISSUE TITLE
future of "contacts" tab

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#65]
currently, we have a "contacts" tab on the main screen.

it is currently unclear if it is needed and wanted at all as it has some drawbacks as:

- there is no real "contacts" or "address" database in deltachat, the current dc_contact_t are mainly used to make chats work and are indented to be used more as input help. showing the contacts in this rather prominent way may raise some expectations we just cannot fulfill currently
- eg. if a contact is deleted it will be re-added automatically when a mail with this contact comes in (blocking, however, is possible)

not saying, we shall delete the tab, however, i would suggest for now not to depend from the user flow on the "contacts" tag, eg. creating chats, blocking contacts, viewing profiles should be possible without it.

**Comment by Simon-Laux** [comment]
_hmm... apps like whatsapp and telegram also have a contacts tab. It might be an expectation that a normal user has.. just throwing that in here.._

**Comment by r10s** [comment]
yip, this might be a good reason to keep the page. also the most-left icon in the button bar seems not to be that prominent for ios-users as it would be for android-users.

so, yes, maybe just keep it; having a similar functionality as the "+" button then.

**Comment by nayooti** [comment]
In WhatsApp iOS there is no contact tab, though.
[Status, Calls, Cam, Chats, Settings]

**Comment by Simon-Laux** [comment]
@nayooti I'm 90% sure they had it before, but you're right not there anymore, might got replaced by the status tab.. _i think.._

**Comment by nayooti** [comment]
Ok, for now we keep the discussed tab. I added some functionality and I will add a search bar (and probably an option to add new contacts) within the next couple days.

I close this issue for now.
