### ISSUE TITLE
LoginController - some considerations

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#650]
Here are some personal thoughts on our "LoginController" aka `AccountSetupController`:

If we are "logged-in"  I find it weird, that the login-button is still shown and it is actually clickable - which triggers a "re-login". 
The email-form is still editable, and the password-field is still there. You can actually count the number of characters which I think is pretty uncommon. 

My suggestion is:
If the user is "logged-in":
- the email-form should be non-editable. 
- the login-button should be disabled at least. (I personally wouldn't mind having a button that says 'logout' - rather than 'delete account'). 
- the password-cell should actually be not shown at all.
 
This way the user has to sign-out first, before signing up to with another account. 
Since we do have the WelcomeViewController now, with a growing number of login-options I think we should consequently funnel the login-process via the WelcomeViewController.

**Comment by r10s** [comment]
in general, the login-form is also needed after a successful login, on the _same_ account the password may have changed as well as sever settings. wrt email-address, this is a bit unclear, but i would also not change this for now.

also, the Log-in button is required therefore, currently, there is no log-out.

the name of the button is maybe not optimal, but a "Done" or "Ok" would imply the other settings needs this button to be pressed as well. and "OK" would also require a "Cancel" button which would also need some additonal testing. as the name of the button was also "log in" on the view the user has already used, this is at least a bit recognizable - so, "Log in" is probably not the worse choice.

so, i would not change things here for now.
