### ISSUE TITLE
scan of qr-code sometimes crashes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#664]
in ~~many~~ some cases, the first scan of a qr-code led to an app crash. if could reproduce this on iphone7 as well as on iphone se.

**Comment by r10s** [comment]
after the move from `unowned` to `weak`, at least on the few first tries, i did not got this crash.

so, this _might_ be fixed by https://github.com/deltachat/deltachat-ios/pull/701 , in fact, `unowned` was also used in the context of qr-code scanning. 

we'll see ...

**Comment by r10s** [comment]
it is not fixed, just go the error again:

- completely new installation of current master to iphone-se
- create account by qr-scan (works!)
- scan qr-code from other phone -> crash
- the second try works as expected

**Comment by nayooti** [comment]
I don't get a crash when trying this scheme.

**Comment by r10s** [comment]
it does not happen always, only sometimes. otherwise it would be easy to fix :)

**Comment by r10s** [comment]
i did not got this crash for some time, closing this for now, we can reopen if it happens again.
