### ISSUE TITLE
Messages only on refresh in the app / No Notification / No Badge

### ISSUE THREAD

**Issue by MalteKiefer** [deltachat/deltachat-ios#667]
- Device: iPhone XR
- iOS version: 13.3.1
- Delta Chat version: 1.3.0
- Expected behavior: 
Somebody writes a message I get a notification
- Actual behavior:
From time to time I got to the app. I open the App, I wait 5 Seconds, a refresh is doing, I see the new messages.
No Notification, no Badges. In the Settings Notifications are allowed for Delta.

**Comment by r10s** [comment]
normally, the messages should arrive, at least after some time.

unfortunetly, iOS does not allow us to keep a connection to your server open while the app is in background. therefore, we try to check from time to time, but the operating system gives use these time slides, we cannot do anything on that - it may be a few minutes or much longer.

this is a known issue, we have several ideas how this can be improved, however it is not that easy for apps as Delta Chat that do not have a central server or service.

**Comment by seehma** [comment]
same here, this continuous check does not work. I only see the emails coming in my mailbox, but the app does not check. When i open the app -> the messages are arriving.

Is the mail App also continuously checking the server, or how does the notification of new email work in those mail apps (Outlook, Apple Mail, ...)

iOS 13.6
deltaChat App: 1.10.1

**Comment by r10s** [comment]
closing this issue as it is a duplicate or at least very similar to #569
