### ISSUE TITLE
QrTab nitpicking #1 - persist last selected segment

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#679]
This is the first part of #660:

although i stated things differently in the past, i think it is worth remembering the selected section (show or scan) between program starts, so it would be great if it can be persisted in addition to the main selection (qr, chats, settings)
the reason for that is that "scan" is typically done more often than "show", but, anyway, the default should stay unchanged as "show"

I had two failed attempts implementing this, therefor a separate issue.

**Comment by r10s** [comment]
> I had two failed attempts implementing this, therefor a separate issue.

it is not that important, let's give that up for now. maybe it is even better to have the qr-view by default, we can do this later, if really needed.
