### ISSUE TITLE
improve gallery layout

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#682]
- implement a gallery grid similar to android containing section headers for different dates (last week, last month, month XYZ). 
- Tapping on a thumbnail should open the QLPreviewController allowing to see the file in detail and being able to swipe to the next or previous one. 
- if possible hide the list icon in the QLPreviewController as it is not needed in our case

**Comment by nayooti** [comment]
Should the list icon be removed for this specific case (PreviewController in Gallery) or for alls cases (includes PreviewController used in ChatView)?
