### ISSUE TITLE
play gifs in chat

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#683]
currently gifs are shown as files in a chat
instead they should be displayed and automatically play in a loop

optionally, as discussed with @r10s: 
in the context menu (long tap) we can implement an option to stop the animation 
the message id's of chats with stopped animations are held in a list on runtime but are not persisted. During the cell updates the list will be checked for the cell's new message id.

**Comment by r10s** [comment]
to the stop-animation: i suggest postpone that, we can improve that later in another round if needed.
