### ISSUE TITLE
iOS 12.4 - AccountSetupController behind UITabBarController

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#686]
I realised this when I implemented #679 and tested on a iOS 12.4 device on simulator. On fresh install I logged in manually via ProfileInfo. After I logged in successfully and the app redirected me to the chats tab as normal. But then when I switched to the QR Tab I got this: 

![screenshot](https://user-images.githubusercontent.com/5249565/81161575-0cbb0d00-8f8c-11ea-9d81-265dc9fb74fe.png
![screenshot](https://user-images.githubusercontent.com/5249565/81279849-f084a200-9057-11ea-80dd-d35bd487f0b0.png)

I assume that ScrollView has no background color in iOS 12 and this way the underlying viewController shines through. But obviously there should be nothing behind the TabBarViewController. 

I did some analysing.
Here is what you get when you inspect the view layers:

![image](https://user-images.githubusercontent.com/5249565/81161063-40e1fe00-8f8b-11ea-8145-a137d8d1ebf0.png)

It seems that behind the UITabBarController is still some AccountSetupController somehow.

I haven't looked into this too deeply, but it seems that under iOS 13 the issue does not occur.

**Comment by r10s** [comment]
good catch, what a mess!

yip, we should definitely clean up here, i have the feeling, we can solve this by throwing  code away instead of adding new one :)

**Comment by r10s** [comment]
@nayooti how do you get the graphic?

**Comment by nayooti** [comment]
You set a break point und trigger it to create a 'snap shot'.

Then in the debug pane you go to *Debug View Hiearchy" (7th from left):
![image](https://user-images.githubusercontent.com/5249565/81163314-da5edf00-8f8e-11ea-8f23-7f2c224614dc.png)

**Comment by r10s** [comment]
@nayooti ca you please check if the "Debug View Hierarchy" looks better with #696
