### ISSUE TITLE
backup progress alert is hidden

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#697]
Currently the progress alert is 'hidden' when a backup has been triggered. It is attached to the top of the settings views table list so that you need to scroll up to see the progress alert. 
Instead the progress alert should be always visible and not be able to scrolled away

**Comment by r10s** [comment]
i want to get rid of this `HudHandler` anyway, it is not needed and it is not nice.

i suggest to use the default `UIAlertController` as we do for configure/export/etc, no need to handle export differently.
