### ISSUE TITLE
Notification observer adding create retain cycles

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#699]
Basically all notification observers create retain cycles. 

NewGroupController:
in `viewWillAppear` 2x in  `nc.addObserver ...`

ChatListController:
in `viewWillAppear` 4x in  `nc.addObserver ...`

And I found a few more when fixing this.
 
self needs to be declared **unowned** or **weak**

**Comment by r10s** [comment]
i do not really understand, can you be a bit more specific and describe things in more detail :)

**Comment by r10s** [comment]
@nayooti: as i cannot reach you on irc nor Delta Chat: can you please have a look at #696 - we can also do an a/v on that.

**Comment by nayooti** [comment]
wasn't in office the other day ...

**Comment by r10s** [comment]
sure, np, just noticed today that there was some github noise - and i took this chance :)
