### ISSUE TITLE
message 'nothing found' missing in search

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#720]
when a search is started, and nothing is found, there should be a hint, that nothing was found. 

otherwise, the user does not know if the search is still going on or if nothing was found.

currently, just a white screen is shown.

we have the string `search_no_result_for_x` for that purpose.

i suggest to do that similar to android.

**Comment by nayooti** [comment]
There is an open PR #713 where our empty-state-labels were redefined.

**Comment by nayooti** [comment]
When using `search_no_result_for_x` I got a runtime error. I figured out that when **tweaking the placeholder** from  `"No results found for \"%s\""` to `"No results found for \"%1$@\""`
 it works.
@r10s Am I allowed to change this?

**Comment by r10s** [comment]
it has to be changed in the sources, i will have a look. thanks for the hint.
