### ISSUE TITLE
link preview

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#730]
nice to have, not urgent

the new MessageKit version will implement UI for link previews in chats. We could grab source code from there. see https://github.com/MessageKit/MessageKit/pull/1310

**Comment by webratte** [comment]
I think I would like it 😀

**Comment by r10s** [comment]
a like preview is easily a privacy leakage, we should keep that in mind.

**Comment by cyBerta** [comment]
Also, we will drop MessageKit soonish. I would not implement that until we have a new chat layout. That's why I'll close this issue for now.
