### ISSUE TITLE
Fix image compression

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#733]
Currently the image compression is broken, both when sending images from the gallery as well as from the share extension.

**Comment by r10s** [comment]
maybe this is a good reason to get that to the core.

**Comment by r10s** [comment]
once https://github.com/deltachat/deltachat-core-rust/pull/1563 is merged, we can remove the corresponding code in ios, a simple dc_send_msg() is sufficient then :)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-core-rust/pull/1563
