### ISSUE TITLE
ChatView Navbar does not like landscape on "notch"-devices

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#734]
![image](https://user-images.githubusercontent.com/5249565/82365791-7833be80-9a11-11ea-9374-c186c9e57a45.png)

on landscape you'll get this:

![image](https://user-images.githubusercontent.com/5249565/82365829-88e43480-9a11-11ea-9b89-320c6bc5bb66.png)

meh ...

**Comment by r10s** [comment]
good catch!
