### ISSUE TITLE
In chat view: consider removing titleview font adjustment

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#736]
Discussion:

Do we want this (current state):

![image](https://user-images.githubusercontent.com/5249565/82368741-348f8380-9a16-11ea-84ed-f2fbac4d98a5.png)

or (iOS-default):

![image](https://user-images.githubusercontent.com/5249565/82368808-4ec96180-9a16-11ea-8840-bebd74a89fea.png)

Using the `adjustsFontSizeToFitWidth`-attribute on UILabels is very uncommon. In fact I can't remember that I've ever seen this on an Apple-app or any other top rated app.

I 100% prefer using the default behaviour.

**Comment by cyBerta** [comment]
@nayooti Then let's remove that. Please double check how it looks like on a small screen if location streaming is enabled. Tbh your example is rather extreme ;). I think for the vast majority of cases there are just 1-5 chars missing

**Comment by r10s** [comment]
i agree for the title that can be of any length theoretically, esp. when it comes from some non-delta-mua through the subject.

but for the subtitle, usually showing the email-address, it is probably better to show the complete address, even when the font is a bit smaller then.
