### ISSUE TITLE
Fix MessageLabel numberOfLines

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#741]
MessageLabel has the property numberOfLines to define the maximum amount of allowed lines. 
For some reason it is impossible to restrict the numberOfLines to 3 while using linkebreakMode `.byTruncatingTail`. The desired effect would be to ellipsize Text if it exceeds the maximum number of lines. Instead, a single ellipsized line is shown.

**Comment by nayooti** [comment]
Without having looked into this the UILabel´s `intrinsicContentSize`-Attribute could help here.

**Comment by nayooti** [comment]
@cyBerta I looked into this and I don't really understand the issue. I see that we're always setting `messageLabel.numberOfLines = 0` (which is default for multiline labels), but I don't see in which way this leads to unexpected or mis behaviour.

**Comment by cyBerta** [comment]
@nayooti I've updated the desciption. setting massageLabel.numberOfLines=0 is not the issue, but setting any other value to it.

**Comment by cyBerta** [comment]
I experienced it when I was working on the file message cells. I wanted to restrict the maximum numbers of lines for the file name.

**Comment by cyBerta** [comment]
I leave this ticket open - even though #799 was merged - because ellipsizing is still missing while restricting the number of lines.

**Comment by nayooti** [comment]
@cyBerta  what exactly is ellipsizing?

**Comment by nayooti** [comment]
@cyBerta Is this issue still existent after dumping MessageKit?

**Comment by cyBerta** [comment]
I think this ticket can be closed for now.
