### ISSUE TITLE
Location streaming indicator not removed from Chat title

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#747]
After location streaming ended and the user has opend the corresponding chat at that time the location indicator doesn't get removed from a chat title. Leaving a chat and reentering it "fixes" the situation.

**Comment by r10s** [comment]
the event that should be sent out is DC_EVENT_CHAT_MODIFIED, i had a quick look at the core, seems so, that this is actually the case, https://github.com/deltachat/deltachat-core-rust/blob/19a6a30fe28c575d4b2cca6fa79681ec4169b0c2/src/location.rs#L230

would be interested, if ios actually updates the title bar on this event at all - eg. if remote changing of a group name works.

**Comment by cyBerta** [comment]
> would be interested, if ios actually updates the title bar on this event at all - eg. if remote changing of a group name works.

It does.

**Comment by nayooti** [comment]
> would be interested, if ios actually updates the title bar on this event at all - eg. if remote changing of a group name works


When reviewing the correspoding PR this  chatView.updateTiteBar() does not get called on my device. (Had location streaming enabled for 5 mins). Any ideas what I am doing wrong @cyBerta
