### ISSUE TITLE
When sharing more than 1 item add a badge counter to the share preview

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#764]
Currently only one item will appear in the share image preview even if more items have been previously selected for sharing. 
As an easy solution to indicate there are more media items that will be sent we can show a little badge at the lower right corner of the share image preview.

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
