### ISSUE TITLE
ContactList shows UVO 

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#769]
UVO stands for Unidentified View Object.

To Trigger:
In GroupDetail -> Add Member -> the UVO shows up centered in ContactList(I assume some empty-state-banner is not hidden).

Or:
New Chat -> UVO centered in ContactList

**Comment by r10s** [comment]
nice, i also noticed a "dot" in the middle of the screen in the "blocked contact" view, seems to be also fixed by #770
