### ISSUE TITLE
app gets slower when used for some time

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#772]
as if some viewcontrollers or maybe loaded images are not freed or so. or some large images.

@nayooti you have some experiences with the debug tools, can you please have a look at that? and try to reproduce that?

**Comment by nayooti** [comment]
probably #748.

Before @cyberta created this ticket I didn't notice the lagging etc. but suddenly it's quite significant.

I already started working on this, but unfortunately it's not that easy to fix.

**Comment by r10s** [comment]
hm, not sire, might also be another problem, i mean opening a chat after startup is super-fast - later on it gets slower. i would assume that with already generated thumbnails things are faster :)

**Comment by r10s** [comment]
further observations:

this happens only if the app is running for _several hours without being killed_ because of location streaming enabled. 

so, at least, it is not an initial annoyance as normally background fetch is done only every few minutes and the app is killed all the time.

**Comment by cyBerta** [comment]
we have memory leaks. When entering a chat with large data like video messages the used memory increases significantly with each entrering & leaving.

**Comment by cyBerta** [comment]
I've found some missing weak declarations in closures

**Comment by nayooti** [comment]
@cyBerta Do you need any help with this?
This view here is very helpful:
![image](https://user-images.githubusercontent.com/5249565/85014894-60ae3980-b167-11ea-91a7-fb419f13e36e.png)

**Comment by cyBerta** [comment]
I think this one is fixed with #798, I'll close it for now. If it reappears, we can reopen this ticket.

**Comment by r10s** [comment]
yip, i can confirm, things are much better meanwhile :)
