### ISSUE TITLE
Gallery follow-up: remove list button in gallery detail

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#785]
Go to Chat -> Chat Detail -> Gallery -> tap any image -> the Gallery Detail (`PreviewController.swift`) view is now showing:

In the bottom right there is an icon showing:
![IMG_7F8B30D09FE1-1](https://user-images.githubusercontent.com/5249565/84627996-2aaf5200-aee8-11ea-9f0e-4d097b5baca1.jpeg)

The icon is no longer needed and should be removed.

**Comment by nayooti** [comment]
Ok, I spend way too long trying to achieve this. I haven't found a stable way to hide this button for good. 

 I come to a conclusion that Apple really wants this list button.

**Comment by r10s** [comment]
k, then we know that, i do not think, this is a big problem.

@nayooti can you please add a comment with your findings somewhere to PreviewController and point to this issue/pr.
so that the next one that thinks, the button can be removed does not start at zero :)

then, we can close this issue.

**Comment by nayooti** [comment]
In case someone is picking up this ticket, I documented my findings in this PR #793 where I tried different approaches 
- traverse search the ui elements -> attempts to manipulate them 
- covering the toolbar -> manipulate alpha to simulate swipe down events. 
- in the code you will find things like AccessibilityIdentifiers of the UIElements in question

**Comment by cyBerta** [comment]
closing for now
