### ISSUE TITLE
improve document-gallery layout

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#790]
we need sth. similar to https://github.com/deltachat/deltachat-ios/issues/682 also for the documents.

- tapping on "profile / document" should open the overview, not the latest document
- a grid is not needed, one row per document
- for the document-item-row, the item from the chat view shall be used, they're just reworked by @cyBerta, have icons, size view and all :)
- tapping on a document-item should open the full-screen-view as now

**Comment by nayooti** [comment]
@r10s: 

> * a grid is not needed, one row per document

What about Ipads?

**Comment by r10s** [comment]
> What about Ipads?

just use the same layout there, as said in the last a/b it is not to have "square" items but having rectangled items (as now when opening the existing Message-Kit-overview) - this is also good for ipad.
