### ISSUE TITLE
Timing for IOS version - current state?

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-ios#8]
What is the timing for a planned IOS version?
How far is the current version?

**Comment by r10s** [comment]
@csb0730 you can test the version yourself: https://github.com/deltachat/deltachat-ios#testing

**Comment by csb0730** [comment]
I for myself do not have an iphone, but many friends do!

How is it installed? When I ask a friend to support what can I say to ?

**Comment by jonasreinsch** [comment]
@csb0730 If someone wants to install the test version, they write an email to us (see link in comment above by @r10s ). We then add them to the Testflight (a service provided by Apple) test group. Afterwards they get instructions via mail, but basically they first install the Testflight app via the App Store, the Deltachat beta is then installed via the Testflight app. Alerts for new versions are also distributed via the Testflight app and they can also check themselves inside the Testflight app for new versions of Deltachat. If you are interested in reading more check https://developer.apple.com/testflight/ - but from a testers perspective, it is pretty self-explanatory. Thank you for telling your friends about Deltachat iOS - perhaps one thing to keep in mind for them - please be a bit lenient with the app, there is still a pretty big TODO ahead and many rough corners.
