### ISSUE TITLE
new contact should also start new chat

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#80]
... or at least have an option to start new chat.

ATM you are coming back to contact list and have to search for the contact you just created.

**Comment by hpk42** [comment]
On Tue, May 28, 2019 at 05:15 -0700, nayooti wrote:
> ... or at least have an option to start new chat.
> 
> ATM you are coming back to contact list and have to search for the contact you just created.

on android after "add contact" (or rather "new chat" or "+") you get asked
"do you want to chat with ..." and then you land at the chat window.

**Comment by nayooti** [comment]
When I grep the “violating” functions it looks like they are used in the rpgp-library.

**Comment by nayooti** [comment]
Since we create contact in the "new chat" section, it makes sense to start new chat right after contact creation. Done by upcoming PR.
