### ISSUE TITLE
move empty state labels always to visible area

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#807]
When searching through the members list, an empty state label appears if no result has been found. It is always centered and thus partly covered by the keyboard. 
The state label should be moved up if the keyboard is opened so that the user can still read the message. 

![Screen Shot 2020-06-22 at 13 56 35](https://user-images.githubusercontent.com/2614900/85285207-c6186800-b490-11ea-898d-94d0eca1e3ff.png)

**Comment by cyBerta** [comment]
Probably all contact search related view controllers are affected.

**Comment by nayooti** [comment]
I think we need to change the concept of empty state labels here.

In NewChatController there are 3 static cells above the cells. 
If you rotate to landscape in Iphone SE there is hardly any space to show an emtpy state label at all. 

So 2 solutions come to my mind:
a) hide 3 static cells when search is active 
b) display empty search label within a cell + scroll to that cell during search

@r10s, @cyBerta  what do you think? Any other suggestions

**Comment by cyBerta** [comment]
I would say, keep it simple. Adding the emty stale label within a cell + scroll handling + separate cell selection handling sounds more error prone than hiding the static cells if the search is ongoing.

**Comment by r10s** [comment]
keep it simple yes. 

not sure how the empty-state labels work in detail currenty, however, in case of search-empty-state-labels, maybe we can just show the hint atop of the screen? (plus some padding). this is also the area focused by the users eyes as typing takes place there.

all other empty-state-labels can stay vertically centered, so maybe add a flag or so.

**Comment by nayooti** [comment]
![IMG_5476](https://user-images.githubusercontent.com/5249565/87547575-98979680-c6ab-11ea-9934-d87798bbc85e.PNG)
![IMG_5477](https://user-images.githubusercontent.com/5249565/87547579-9af9f080-c6ab-11ea-8fd1-68338fb384b6.PNG)

Not so happy with this.

Here is how Telegram solves this. This is probably my favourite.
@r10s, @cyBerta What do you think?

![IMG_4467](https://user-images.githubusercontent.com/5249565/87548454-cd581d80-c6ac-11ea-9385-5d5b12a8bb55.PNG)

**Comment by r10s** [comment]
the telegram screenshot is the in-chat search, this is a bit different as the up/down arrows are there anyway.

however, it seems we have to sync the different add-member-to-group views before - why is "new member" available on from add-member but not from within new-group?

once done, we have at least. a "new contact" item whenever there is no search result, so, the view is not really emtpy and we should not use an empty-view-label. 

i suggest, just to use the footer of the "new contact" item for the hint.
