### ISSUE TITLE
Document Gallery layout is broken

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#818]
- see attachment:
* some audio files are shown as empty entries (e.g. wav files) 
* sometimes the UI elements are overlapping and upper-left aligned
* file size labels are cropped at the bottom

![Screen Shot 2020-06-30 at 12 28 45](https://user-images.githubusercontent.com/2614900/86116185-4e1ff280-bacd-11ea-9a50-7d029e895305.png)

**Comment by r10s** [comment]
this is new, or? it was fine for me one week ago.

when on that: i think we should reverse the order, so that new files are atop, however, i file a separate issue for that.
