### ISSUE TITLE
Existing Group - adding new GroupMembers doesn't work

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#835]
Create GroupChat - go to ChatView -> Group Detail on top -> AddMember -> select New GroupMember -> Done -> The selected members don't appear in the member section

**Comment by r10s** [comment]
but the member is actually added, or? otherwise, this would be a blocker.

**Comment by r10s** [comment]
i just tested that, for me adding members work :) puh.

> The selected members don't appear in the member section

what exatly does not work for you? what is "the member section" here? can you please try over?

**Comment by nayooti** [comment]
Yes, my groups work fine now.
