### ISSUE TITLE
tweak profile background colors

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#838]
- the background of the shared-chats and of the member-list should be the same background than a button item.  
this is correct for light-member-list, dark-member-list, light-shared-chats but _not correct_ for dark-shared-chats

- the overall header with the avatar in the first row is currently a header afaik and should have the same background color than used below the other headers. this is correct in dark-mode, but not correct in light-mode.

having #831 (enlarge profile images) in mind: if it is easier, i would also be fine with turning the avatar-header to a normal row (if this is not yet the case), iirc, clicks in headers are complicated.

when tweaking, maybe just add an option or so, the items are used at many places and it is so easy to fix this issue and open a new one in another list :)

**Comment by nayooti** [comment]
I think I added the avatarView as t`ableView.tableViewHeaderView` to avoid the gap which you get when using UITableView.style.**grouped**.
I originally used our default `ContactCell` as headerView in the process, but this caused issues (header disappeared), so I had to transform it into an `UIView`.
