### ISSUE TITLE
add values to some profile rows

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#839]
the rows gallery, document and disappearing-messages all have the .disclosureIndicator instyle, i think it would be useful to make some more value of that:

- gallery, document can show the number of items in them, 0 for none
- disappearing-messages can just get the works On/Off (there are already strings for that) (showing the concrete selection is more tricky as too long, two line style is ugly and not used elsewhere etc. so i would not target that now)

**Comment by cyBerta** [comment]
it would be great if we could this after #810 was merged, since this change is rather small and would need to be done twice otherwise (because of some refactorings in #810).
