### ISSUE TITLE
[login screen] Collapsed footer overlaps buttons

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#84]
It is fine on first open, but clicking "show" and the "hide" creates the following:

![Screenshot 2019-05-29 at 11 41 35](https://user-images.githubusercontent.com/790842/58546989-cfd88900-8206-11e9-8059-a91f80046d64.png)

**Comment by nayooti** [comment]
ok, I opened this as issue #70 already, but I thought, that this has been fixed by one of the last PRs.

 I'll look into this.

**Comment by nayooti** [comment]
To reproduce this error:
in login tap on ADVANCED -> tap on "IMAP server" (this activates textfield) -> tap on "Imap Security" (navigates to Imap Security) ->   tap on back (navigates back) -> tap on "Hide".

**Comment by nayooti** [comment]
fixed by latest PR
