### ISSUE TITLE
show ephermeral state in chat title

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#842]
if disappearing messages are enabled for a chat, this should be shown by a stopwatch icon (for now, maybe we change that later) in the titlebar.

the stopwatch icon should be shown left of the avatar, where also the location streaming icon might appear additionally.

on android, this looks like the following:  https://github.com/deltachat/deltachat-android/pull/1480 (however, as said, on ios we want the icon left of the avatar)

**Comment by cyBerta** [comment]
fixed by #848
