### ISSUE TITLE
profile image picker shows recent photos and there is no way to pick photo from album

### ISSUE THREAD

**Issue by Gozala** [deltachat/deltachat-ios#847]
- Operating System (Linux/Mac/Windows/iOS/Android): iOS
- Delta Chat Version: v1.8.1
- Expected behavior: Native image picker (that most apps use on iOS) that lets me navigate across albums, e.g contacts app.
- Actual behavior: Shows all photos ordered by recency
- Steps to reproduce the problem:
  - Go to settings, Your profile info, Profile Picture (click camera)
  - Pick Gallery option

**Comment by nayooti** [comment]
@r10s I am currently working on #437 integrating the native iOS camera globally, no longer using the CameraViewController.
Since the CameraViewController and the ImagePicker mentioned in this ticket are part of the same library I don't see any reason to continue using it.

**Comment by r10s** [comment]
@nayooti yeah, would be great if you can fix that!

**Comment by cyBerta** [comment]
tested on iOS 13.5 iPhone SE and could not reproduce that issue.
