### ISSUE TITLE
[login screen] unable to login with regular account credentials

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#85]
I have a test account (alice@librechat.net) which works fine in all other settings, but I am not able to login with it anymore on the latest `master`

```
11:39:49.303 ❤️ ERROR events.callbackSwift():104 - network: Cannot login as alice@librechat.net.

Response from w017f238.kasserver.com: Unsupported authentication mechanism.
```

Is the error I get

**Comment by dignifiedquire** [comment]
I have a build with the new rust-core, exact some issue, also tried different accounts

**Comment by r10s** [comment]
@nayooti so, as it happens with the c-core as well as with the rust-core, maybe some credentials are not passed correctly to the core?

**Comment by nayooti** [comment]
@r10s I will check this out by tomorrow.

**Comment by dignifiedquire** [comment]
looking at the logs I suspect it is trying oauth, even though it shouldn't, but not sure

**Comment by nayooti** [comment]
I found potential source of bug and it kinda seem to work now. 

Currently I can login at
- gmail 
- outlook 
accounts without using oAuth2.

But it's hanging for a couple minutes at 92%: 
Generating keypair with 2048 bits, e=65537 

And Web.de-accounts seem to fail. Any idea why? @r10s 
Other Email-providers I should try?

**Comment by dignifiedquire** [comment]
- the hanging is likely due to a debug build of the crypto libs being triggered (need to enforce release builds always) 
- can you push what you have, then I can test with the accounts that I have here

**Comment by nayooti** [comment]
Apparently fixing regular login caused oAuth not working anymore. I will look into this.

Also canceling an ongoing login does not work properly at the current state.

**Comment by nayooti** [comment]
@dignifiedquire Any chance that Rust-core affects oAuth2 login?

I cloned pre-Rust as seperated project - oAuth2-login worked fine.
I copied that pre-Rust AccountSetupController into current project (that uses Rust-Core) - oAuth2 fails.

**Comment by dignifiedquire** [comment]
that is possible, oauth was reworked and that well tested yet

**Comment by dignifiedquire** [comment]
if you can push the fix I can work on fixing it

**Comment by nayooti** [comment]
@dignifiedquire I blew my built today unfortunately right before I had to leave. Will recover tomorrow morning and push at around 10am.

**Comment by nayooti** [comment]
You can checkout Branch 
regularLoginFix

Here oAuth-login and regular login both work under non-rust-core.
Both login types take about 5 seconds to complete.

**Comment by nayooti** [comment]
I hope you don't mind, if I close this issue and create new Issue for this.
