### ISSUE TITLE
in settings, "my profile" disappears row sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#851]
i assume, this is related to #810 - when i tested that, i've first noticed it, since then 2 more times. and _i_ have never seen the issue before #810.

scrolling down and up in the settings let the "my profile" reappear.

i cannot really say how this can be reproduced, it happens when the app is active after some time, maybe there is some issue wrt cell-reusing etc. iirc we had similar things in the past. @cyBerta maybe you have an idea.

<img width=360 src=https://user-images.githubusercontent.com/9800740/87541581-c2e45680-c6a1-11ea-80ad-c618b04d625b.png>

**Comment by nayooti** [comment]
I think this happens when using UITableViewCell as UITableView HeaderView.
