### ISSUE TITLE
NewGroupController - tap groupMember - selection stays

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#863]
in Chats -> New Chat -> New Group -> Add Members (add some members to group) 

Now: tap on Members in list.
- This will induce a visual selection (which personally should only be visible if there it actually induce some action)
- worse the selection state stays. 

I think since tapping on a cell doesn't do anything the cells shouldn't be selectable.

**Comment by r10s** [comment]
> I think since tapping on a cell doesn't do anything the cells shouldn't be selectable.


yip, however, when removing the selectability, we should keep in mind that swipe-left allows removing a contact.
