### ISSUE TITLE
maybe wrong orientation on image picking

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#865]
@nayooti can you please, after your holidays, re-check the image-orientation-problem you encountered in #858 - i could not reproduce the issue although trying hard nor find any recent information.

the workaround from #858 introduces some follow-up issues and i removed it therefore from the pr.

if needed, we can create a separate pr.

**Comment by cyBerta** [comment]
tested on iOS 13.5 iPhone SE and could not reproduce that issue.

**Comment by cyBerta** [comment]
@r10s I propose to close that ticket. Neither you nor I could reproduce the bug on multiple devices and OS versions

**Comment by r10s** [comment]
yip, let's close, more details are needed.

**Comment by nayooti** [comment]
Yes close this. I am not able to reproduce the issue anymore.

What happened was that some profile images had incorrect orientations. Something like this:
https://stackoverflow.com/questions/10850184/ios-image-get-rotated-90-degree-after-saved-as-png-representation-data 
or this
https://stackoverflow.com/questions/53949421/selecting-images-with-uiimagepickercontroller-auto-rotates-them
