### ISSUE TITLE
Improve import backup onboarding experience

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#872]
When importing a backap after a fresh DC installation, a an alert message appears if no backup has been found. The alert message tells the path to the directory DC will look for an backup file. At that point the directory is not created yet. Therefore the user will need to remember the path in the alert message and create manually the directory, move a backupfile there and retry the import process. 

My proposal is that  
a) the directory will be automatically generated as soon as the user tries to import an backup and if that directory is not yet existing. This directory will be used later on for other DC config files anyways (wal sqlite file for example). This way, the user will find the target folder where to move the backup to (using the Files app) more easily.

b) the user can choose the file from a file picker: the file will be copied to the apps documents folder (which will be created if it's not yet existing) and the backup starts immediately afterwards. This implies additional error handling, if the app has not the permission to access the selected file. The documents picker logic could be reused from the attach documents context.

@r10s @nayooti I would like to know what you think about it

**Comment by r10s** [comment]
there are [ongoing efforts in core to move to tar](https://github.com/deltachat/deltachat-core-rust/issues/1729), this is not directly related, however, before updating the backup import on ios, i would wait until that is finished. might be core also adapt api or so.

**Comment by r10s** [comment]
tar-move is done, and meanwhile we also have a more thorough documentation for the whole process at https://support.delta.chat/t/import-backup-to-ios/1628 

next step might be to do at least multi-device-setup without the need of an backup, cmp. https://github.com/Frando/sendtar , for multi-device-setup, which is a common usecase of backup import, that would improve the whole process.

therefore, i am not sure if b) is worth the effort currently, things will stay complicated and the time put into that would maybe missing elsewhere.

for a), however, if it is still true that the directory is not created, that could be a one-liner that makes things much easier.

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
