### ISSUE TITLE
improve autocrypt-setup-message dialog

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#878]
Currently there's an alert dialog containing a long input field for entering the fingerprint / validation code. 
It's hard to keep track of the long code while entering since there's no visual help.

We should implement an autocrypt setup dialog as it was done on Android. The latter has multiple input field blocks, separated by some space.

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
