### ISSUE TITLE
Adjust Keyboard Layout in UITextFields

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#894]
On UITextFields we are using the default keyboard layout showing an 'ENTER'-key most of the time. Since UITextFields are single-line the 'Enter'-key is a bit misleading.

Positive example:
In DC-app create a new contact.
![IMG_4600](https://user-images.githubusercontent.com/5249565/89634086-19117780-d8a5-11ea-9a04-e8b98c813ba0.PNG)
- keyboard shows **Next-Button**
![IMG_4601](https://user-images.githubusercontent.com/5249565/89634090-1b73d180-d8a5-11ea-8878-8bdf790661f1.PNG)
- keyboard shows **Done-Button**

If there are several UITextFields chained together we should use the **Next** + **Done**-logic.

Why is this needed? 
It can be really annoying if there is no way to dismiss the keyboard, and sometimes the keyboard covers other elements, for example in our `GroupViewController`. Having a done-button is the most intuitive way to dismiss the keyboard.

![IMG_4599](https://user-images.githubusercontent.com/5249565/89633001-6f7db680-d8a3-11ea-9036-d7eef40af29a.PNG)

Apparently we're not using an UITableViewController here, so the tableView's contentInsets are not adjusted on keyboard appearance.

Where are adjustments needed:

AccountSetupController -> PasswordCell: 'Done'
NewGroupController -> GroupNameCell (maybe different after #893)
EditGroupViewController -> groupNameCell

**Comment by cyBerta** [comment]
In 'New contacts' screen, the next button is not working correctly, too (iOS 14, iPhone SE)
