### ISSUE TITLE
got autocrypt setup message on same phone not the new phone

### ISSUE THREAD

**Issue by ddgg** [deltachat/deltachat-ios#895]
- Operating System (Linux/Mac/Windows/iOS/Android):ios
- Delta Chat Version: 1.12.0
- Expected behavior: got autocrypt setup message on different phone
- Actual behavior: autocrypt message can only be seen on same phone
- Steps to reproduce the problem: login with same account on two iphones, email service is mailo.com
- Screenshots:
- Logs:

**Comment by r10s** [comment]
the autocrypt-setup-message should appear on _all_ phones. 

@ddgg can you please try to send a "normal" message in the "saved messages" chat - does that appear on the other phone? (maybe unreadable as the key is missing)

**Comment by cyBerta** [comment]
I've set up a mailo.com account. The autocrypt setup message is caught by the spam filter. @ddgg can you please change your spam filter settings? 
In the meanwhile we should figure out if we can avoid being detected as spam. There's already a ticket for it: https://github.com/deltachat/deltachat-core-rust/issues/1750

**Comment by ddgg** [comment]
I put email address of myself in addressbook, autoecrypt setup email is not spam now and can be received on both devices, and autocrypt setup is successful, thanks for the help
