### ISSUE TITLE
Important daily usage options are missing

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-ios#9]
This is a summary issue for some important points to use IOS version daily:

1. Alert for incoming mails is not guaranteed and stable. Phone is vibrating but no further hint for new messages. New messages are only seen if a chat is closed and shown again (similar to that). No tune, no number at icon.
2. no possibility to send attachments
3. no possibility to add new contacts or to use contacts in address book

In the moment even basic operation is not possible. At least point 1-3 should be solved to hand over the application to a user. Point 1. is the most important. Without this even simplest message exchange is not possible reasonable!

All this is a feedback from a fried which agreed to make a try with that early IOS version.

**Comment by r10s** [comment]
hi @csb0730 - yes there are some important points still missing. the ios version is a very early release and not yet meant to be use productive.

@allareinsch, @jonasreinsch, @hpk42 and me tried to define a _minimal viable version_ some weeks ago; this was our outcome:

(the first entries have a higher priority):

- use new deltachat-core-api and
  adapt threads to the following scheme:
  https://deltachat.github.io/api/
  (the current ios-implementation relies on
  threads created by deltachat-core; this is no longer done)

- threads should be created when going to foreground
  and removed when going to background.
  we could say, for the first version, we're a foreground app
  and figure out background things later

- allow group creation
  (afaik groups created on other devices are
  already displayed)

- ui-polishing, eg.
  - smarter time/date display
    (time beside messages, date as headlines)
  - adapt avatars (use the colored images from the chatlist
    also in the chat, no avatars beside outgoing messages
  - show e-mail-address in the chat-title and/or open profile
    when clicking on chat-title

- allow sending of images
  and taking+sending photos directly from the camera.
  (videos and voice messages
  and other attachments can be done in a later version)

- allow advanced configuration options on setup
  to make sure users can connect if the autoconfig fails
  (imap-server, imap-port, imap-flags, same for smtp -
  if not yet implemented
  (cannot test currently, iphone-battery is empty))

@allareinsch maybe you can copy this to another issue with the name "Minimal viable version" and tick the points that are done. i am not 100% sure about the progress.
i would also add the notifications and contact adding (thought this is already possible, have no iphone here currently)

**Comment by jonasreinsch** [comment]
Thank you for your feedback, @csb0730 - at least for the first part of your 3rd point: contact creation is possible - (maybe not obvious, but I think it is the same flow as in the Android version):

(1) New Chat -> (2) New Contact -> (3) Enter email and (optionally) name -> (4) -> press Done.

We will include your points bullets to our TODO / roadmap if not already there (point 2 is included (we will do images / photo attachments first)), the second part of point 3 is also included ('read address book for contact suggestions').

The roadmap for the minimum viable version is in the README.md
the progress is logged with checkboxes. The progress there discribes the progress in the source, not in the test builds - for the test builds, you see below a Changelog. E.g. in the current (third) test build, *automatic configuration via DC_EVENT_HTTP_GET event* is not yet supported, even though it is if you build from source.

@r10s do you suggest that we duplicate the progress / TODO for the minimum viable version to an issue or was it just not clear that TODO / progress is in the README (as well as the changelog for the builds)? The reasoning for putting it in the README was to make it more prominent, but maybe it is more easily overlooked there?

![grafik](https://user-images.githubusercontent.com/144326/44956480-5c972600-aec5-11e8-93b1-5ba441571513.png)

![grafik](https://user-images.githubusercontent.com/144326/44956501-87817a00-aec5-11e8-9459-402df0f7a8ab.png)

**Comment by r10s** [comment]
@jonasreinsch sorry, i've just forgot about the points in the README :)
i've added the notification issue, there, so, there is no need for an additional issue imho. from my view, this issue can be closed then.

@csb0730 wrt notifications we should also keep in mind that the "minimal viable version" will probably a foreground-only versions, so it won't even detect messages arriving in background and we probably do not even need them for now.
