### ISSUE TITLE
canceling on-going login process not working

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#90]
running 
`dc_stop_ongoing_process` 
on main-thread causes UI to freeze.

running
`dc_stop_ongoing_process` 
on background-thread doesn't freeze UI, but all buttons are not responsive anymore.

**Comment by nayooti** [comment]
@dignifiedquire 
turns out that 
`dc_stop_ongoing_process`
also worked nicely under pre-Rust-builds.

**Comment by dignifiedquire** [comment]
I believe the change is that the old core was much more agressive, while the new version waits for existing work to finish. Could you change the behavior to not block the ui thread when calling this method, as the fix in core itself might take a bit to be figured out.

**Comment by dignifiedquire** [comment]
ignore my comment for now, need to check some things first

**Comment by r10s** [comment]
closed by #282
