### ISSUE TITLE
react to mailto: links on iOS 14

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#900]
[heise.de](https://www.heise.de/news/iOS-14-und-macOS-11-Apple-News-kapert-Web-Links-4869012.html) reports that starting with iOS 14 the user can decide which app shall handle `mailto:` links.

if possible, we should offer this option to the user/the system.

**Comment by cyBerta** [comment]
closing in favor of #1126

**Comment by r10s** [comment]
ahh, there was already an issue :) thanks for closing this one and cleaning up :)
