### ISSUE TITLE
'+cyclone' is not a recognized feature for this target (ignoring feature)

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#901]
building recent rust core, results in thousands of these error messages, compiling seems to take much longer (in fact, current master does not finish within a time that usually succeeds, still waiting :)

[long log with the error messages](https://gist.github.com/r10s/dac57570f95358c8cef5ac08ca0de95b)

**Comment by cyBerta** [comment]
This issue will vanish by updating the toolchain to rust 1.46+

**Comment by r10s** [comment]
great, so we just have to wait (toolchain is updated in the core afaik).

**Comment by r10s** [comment]
we're on rust 1.49 meanwhile, so we can close that :)
