### ISSUE TITLE
Multiple messages causes multiple notification storm on Apple Watch

### ISSUE THREAD

**Issue by ctheune** [deltachat/deltachat-ios#903]
- Operating System (Linux/Mac/Windows/iOS/Android): iOS
- Delta Chat Version: 1.12
- Expected behavior: for multiple messages in a chat I only get a single notification (last message? first message? indicator of "there are more messages") or even no notification if the message was already read on a different device
- Actual behavior: i got about 10 messages in a chat and then a few minutes later the watch sent me 10 individual notifications that I had to dismiss. i ended up disabling notification mirroring for the watch to avoid going insane. ;)
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by r10s** [comment]
thanks for filing the issue. yes, the notification need some more love, indeed.

**Comment by cyBerta** [comment]
I think we need a watch :)

**Comment by r10s** [comment]
wondering if that works somehow in the emulator ...

**Comment by r10s** [comment]
we are grouping notifications with the upcoming release, maybe this improves the situation also for the watch.

**Comment by r10s** [comment]
> Though to be fair this is also how it happens on whatsapp for example

k, then this is maybe the expected behavior. iirc, we do not do special things for the notifications and leave throttling up to the operating system.

closing this is a bit stale issue, also there are no further reports the last 2y. if we find an actionable item, we can reopen.
