### ISSUE TITLE
[login screen] discuss business logic of login-model

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#91]
Given that user logged in successfully,
visiting the Account Settings afterwards shows
email-field and password-fields filled in (password is hidden obv). But the login-button is still enabled, which is kinda awkward.

On the other hand the app is missing a logout-option. 

Two possible approaches:
Szenario 1: At least the login-button should be disabled once the user has logged in. Once the user made any changes to the credentials the login-button should be re-enabled, so the user can "switch" to another account.
Szenario 2: After user is logged in the login-button will turn into logout-button. And the credential fields are "greyed out" and not editable. Once the user pressed "logout" the credentials are back editable and the user can re-login.

Any thoughts?

**Comment by Simon-Laux** [comment]
How about:
- Logout button should display a confirm and then log the user out (deleting all data + confirm needs typing in account email)
- "Edit Credentials" button -> unlocks fields / show a login windows with confirm and cancel button.

**Comment by nayooti** [comment]
We have a DeleteAcount-option in Settings Controller which also is a bit discuss-worthy and is also part of the login-model.
As far as I understand this one wipes data from the device, and logout the user. But it doens't actually delete any accounts, am I right? 

A default-user might think this butten will actually delete the real email-account.

**Comment by Simon-Laux** [comment]
> A default-user might think this butten will actually delete the real email-account.

How about the message:
```
You're about to logout the account [email] from deltachat. 
This will delete both your private keys and all **local** chat history.
 You probably want to make a backup first.

| Backup |    | Cancel |    | Continue |
```
then after continue:
```
Type your email address in the box bellow to confirm the logout of [email] on deltachat.
Remember to make a backup first when you want to keep your chat history.
[ Input field which enables the "Logout"-button ]
| Cancel |  | Logout |

**Comment by Simon-Laux** [comment]
> But it doens't actually delete any accounts, am I right?

You're right. The keys get deleted too so if the user has no second device setup or an backup his access on the chats gets lost.

**Comment by nayooti** [comment]
I implemented a temporary simple solution for now:

User is logged in (login-button is disabled)
User starts editing email-field (login-button will be re-enabled)

Should reconsider once  #90, #92 is fixed.
