### ISSUE TITLE
streamline avatar selection menu in profile after qr-account-scan

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#912]
- order should be "camera" atop and "gallery" below (as in chat)
- ~~group avatar selection lacks the option "delete"~~

in the group-profile and normal-profile, this was streamlined in #879, however, if was overseen for the the after-qr-scan-profile

**Comment by nayooti** [comment]
Can you be more specific, where this camera-gallery-dialogue can be triggered?
Screenshot maybe?

Where exactly should I be able to delete group avatars? Inside group -> edit -> tap on Avatar -> I get this: 

![IMG_6815A784CC21-1](https://user-images.githubusercontent.com/5249565/98942847-ec49ad80-24ee-11eb-8226-37c3b41f89cc.jpeg)

**Comment by r10s** [comment]
it is all about the avatar selection that is done after setting a new account via a qr-code-scan.

after the scan, you are redirected to a ViewController where you can enter name+avatar, for that ViewController:
- order should be adapted
- "delete" is missing when an avatar is actually selected
