### ISSUE TITLE
opening gallery slow

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#936]
opening the simple image gallery is slow if there are many images in the gallery.

reason is that all message-objects are loaded before the image is displayed, which, however, is not needed - opening the gallery should be only a call to [dc_get_chat_media()](https://c.delta.chat/classdc__context__t.html#a344a82b9f288b5eb5d39c7cf475cddb7) plus loading the image to display.

all other images should be loaded as needed.

on my iphone7, things get slow on chats with >500 images, it takes half a second to open. so that is not _that_ slow, but i still would consider this as a bug - you may have 2k images and you may have slower phones.

**Comment by nayooti** [comment]
@r10s Sorry for asking, but is this issue about the `GalleryViewController`? 
Because in the GalleryViewController we already do only create message-objects on demand. So I am confused.

**Comment by r10s** [comment]
@nayooti this issue is about `PreviewController` that requires urls as arguments, instread of message IDs. to create the  URLs, all messages have to be loaded.

see eg. opening from the `GalleryViewController` at https://github.com/deltachat/deltachat-ios/blob/89904d942affe434f6273deb2bf064644730ce5f/deltachat-ios/Controller/GalleryViewController.swift#L214 - the compactMap is evil there.

in `ChatViewControllerNew` (cave: `ChatViewController` is deprecated and will be removed soon) there are similar things, URLs are collected previousMediaURLs and nextMediaURLs, this is probably unneeded as well.
