### ISSUE TITLE
[chat view] Strange header image

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#97]
![Screenshot 2019-06-03 at 23 10 37](https://user-images.githubusercontent.com/790842/58834932-d6c32980-8654-11e9-90ee-8040900cf895.png)

**Comment by nayooti** [comment]
@dignifiedquire 
I reverted the ChatView changes, where this error likely occurred.
Could you please verify that the issue still occur on latest master?

**Comment by r10s** [comment]
i think this is fixed and fine now.
