### ISSUE TITLE
group creation issues

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#975]
creating a group has some minor issues, some may regarded as bugs even:

1. when using "New contact" in the process, an additional one-to-one-chat is created with the added contact, this is unexpected

2. when entering an exiting contact in the "New contact" dialog, this contact is not added as a member

3. when hitting "New contact" and the search contains an email-address,  we should use that to prefill the "New contact" dialog

4. when leaving the "New contact" dialog via "Done" button, currently, we go back to the "Add members" screen, the user has no clue if the added member is added or not. it is better to go back to the "Create group" screen where the user can directly see the added member (we should not forget to also add normally checked members)  
this is one click more when adding another member, but i think, this is more straight-forward.

nb: szenario i have in mind: 10 ppl sitting together and want a collective group; each ppl tells the group creator their email address. or the group-creator has a list of addresses that should go to a group.

**Comment by cyBerta** [comment]
we'll discuss 4. in a further iteration. Maybe we can sort selected contacts to the top of the list.
