### ISSUE TITLE
[chatview] placeholder is a bit generic

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#98]
it says `Aa` currently
![Screenshot 2019-06-03 at 23 11 58](https://user-images.githubusercontent.com/790842/58834992-03774100-8655-11e9-822a-061eb3f3a444.png)

**Comment by r10s** [comment]
already suitable for tooth doctors :)

**Comment by nayooti** [comment]
It will now show 'Message' (as in Telegram). Facebook-Messenger shows 'Aa' btw. 

In case you prefer something else, let me know.
