### ISSUE TITLE
avatar preview not updated after selection on some phones

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#990]
eg. on iphone12mini emulator, when selecting eg. an image for a newly created group, the image is not updated in the group selection dialog, instead grey circle is shown - while the image actually is set. 

<img width="350" alt="Screen Shot 2020-11-16 at 11 50 23" src="https://user-images.githubusercontent.com/9800740/99244162-fecf2a00-2801-11eb-810c-e338a3e4544b.png">

also, the "camera" placeholder is not shown. same for self-profile image.

i thought first, this is an emulator issue, however, on iphone7-emulator, this works.

iirc, we had a similar issue in the past.

**Comment by cyBerta** [comment]
what's the emulator's iOS version?

**Comment by cyBerta** [comment]
I can reproduce the bug now

**Comment by r10s** [comment]
great :)
