### ISSUE TITLE
Expose Send-Copy-To-Self option

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#992]
Currently the send-copy-to-self setting is too hidden, so that users have difficulties to setup multi device usage. The option should be on the first level in the settings and I propose to place it at the bottom of chats and media.

In addition to that the wording should be reconsidered, which should not stop us from doing the first step above though. There's an ongoing discussion in the forum https://support.delta.chat/t/rename-send-copy-to-self-setting/1019

My propsal is to have in a subsequent step a separate section Multidevice, where we add the switch sent copy to self, but I guess we need to discuss that further :)

**Comment by prologic** [comment]
is this setting visible at all in the iOS client? I can't find it 😅

**Comment by prologic** [comment]
okay I found it finally! 😅 I _think_ the problem is that finding and accessing the "Account" settings is actually rather difficult to find or non-obvious.

**Comment by r10s** [comment]
moving  issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48); i think, at some point, we will streamline the options anyway, across all UIs.
