### ISSUE TITLE
Quotes for Document, Audio and Voice messages

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#996]
currently there's no graphical representation for audio/voice messages and attached files, only the message text appears in a quote. If a message doesn't contain any message text, there's no indication (besides the sender information) wich message is quoted.

* For document, voice and audio messages without any message text, the message summary should be shown as quote text
* if a preview of a document can be rendered, a small image of the pdf should be shown, otherwise the corresponding document icon
* voice message quotes should have the play button as graphical representation

**Comment by r10s** [comment]
> For document, voice and audio messages without any message text, the message summary should be shown as quote text

i think, core provides exactly that, dc_msg_get_quoted_text() should never be an empty string (it is null, if there is no quote, howver)

for the other points - well, images are shown, and, at least for now, the other types seems not to be worth the effort.

**Comment by cyBerta** [comment]
Shown quotes did already show the right string, only for the draft area where I was working on at that moment I wasn't yet there :roll_eyes: 
So what remains is the missing preview/icon for documents and maybe a visual representation for audio messages. The latter isn't implemented in android either though.

**Comment by r10s** [comment]
> So what remains is the missing preview/icon for documents and maybe a visual representation for audio messages.

i think all of them are not urgently needed needed for _quotes_.

for the staging-area, however, it is a different thing. but this is about quotes, or?

**Comment by cyBerta** [comment]
yes, that's about quotes
